<template>
  <div class="app-container rates-page">
    <header v-if="!embedded"><div><span class="eyebrow">FINANCE · INTERNAL COST</span><h1>{{ t('title') }}</h1><p>{{ t('intro') }}</p></div><el-button icon="Refresh" :loading="loading" @click="loadPeople">{{ t('refresh') }}</el-button></header>
    <el-alert v-if="!embedded" :title="t('boundary')" type="info" :closable="false" show-icon />
    <el-alert v-else title="在这里设置成员的用人成本，用于人员预算和工作成本核算。按生效日期保存新版本，已确认的历史成本保留原计算依据。" type="info" :closable="false" show-icon />
    <section class="rates-panel">
      <div class="toolbar"><el-select v-model="selectedUserId" :disabled="embedded" filterable :placeholder="t('person')" style="width:min(440px,100%)" @change="loadPolicies"><el-option v-for="person in people" :key="person.userId" :value="person.userId" :label="`${person.nickName || person.userName} · ${person.companyName || ''}`" /></el-select><el-button v-if="canManage" type="primary" icon="Plus" @click="openCreate">{{ embedded ? '设置用人成本' : t('add') }}</el-button></div>
      <p v-if="selectedPerson" class="person-line"><b>{{ selectedPerson.nickName || selectedPerson.userName }}</b> · {{ selectedPerson.companyName }}</p>
      <el-empty v-if="!selectedUserId" :description="t('selectPerson')" />
      <el-alert v-else-if="!rawCostVisible" :title="t('forbidden')" type="warning" :closable="false" />
      <el-table v-else :data="policies" v-loading="loading" :empty-text="t('empty')">
        <el-table-column :label="t('version')" width="85"><template #default="{row}">v{{ row.policyVersion }}</template></el-table-column>
        <el-table-column :label="t('rate')" min-width="145"><template #default="{row}"><b>{{ money(row.unitCost) }} {{ row.currency }}</b><small>{{ modeLabel(row.costMode) }}</small></template></el-table-column>
        <el-table-column :label="t('basis')" min-width="190"><template #default="{row}"><template v-if="row.costMode !== 'HOURLY'">{{ row.rateMinutesPerDay || 480 }} {{ t('minutesPerRateDay') }}<small v-if="row.costMode==='MONTHLY'">{{ row.standardWorkDays ?? '—' }} {{ t('daysPerMonth') }}</small></template><span v-else>60 {{ t('minutesPerHour') }}</span></template></el-table-column>
        <el-table-column :label="t('period')" min-width="220"><template #default="{row}">{{ row.effectiveFrom }} → {{ row.effectiveTo || t('ongoing') }}</template></el-table-column>
        <el-table-column :label="t('status')" width="100"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?t('active'):t('voided') }}</el-tag></template></el-table-column>
        <el-table-column :label="t('evidence')" min-width="220"><template #default="{row}">{{ row.remark || '—' }}<small>{{ t('references') }} {{ row.referenceCount || 0 }}</small><small v-if="row.voidReason">{{ row.voidedUserName }} · {{ row.voidReason }}</small></template></el-table-column>
        <el-table-column v-if="canManage" :label="t('action')" width="100" fixed="right"><template #default="{row}"><el-button v-if="row.status==='ACTIVE'" link :type="canDelete(row)?'danger':'warning'" :loading="retiring===row.policyId" @click="retire(row)">{{ canDelete(row)?t('delete'):t('void') }}</el-button></template></el-table-column>
      </el-table>
    </section>
    <el-dialog v-model="dialog" :title="t('newVersion')" width="min(620px,94vw)" append-to-body :close-on-click-modal="false">
      <el-alert :title="t('immutable')" type="info" :closable="false" />
      <el-form :model="form" label-position="top" class="rate-form" require-asterisk-position="left">
        <div class="form-grid"><el-form-item :label="t('personName')"><el-input :model-value="selectedPerson?.nickName || selectedPerson?.userName || '—'" disabled /></el-form-item><el-form-item :label="t('region')"><el-input :model-value="regionName" disabled /></el-form-item></div>
        <div class="amount-grid"><el-form-item :label="amountLabel" required><el-input-number v-model="form.unitCost" :min="0" :max="9999999999.9999" :precision="4" :controls="false" style="width:100%" /></el-form-item><el-form-item :label="t('currency')" required><el-select v-model="form.currency"><el-option :label="t('CNY')" value="CNY"/><el-option :label="t('VND')" value="VND"/><el-option :label="t('USD')" value="USD"/></el-select></el-form-item></div>
        <div class="cost-preview" aria-live="polite"><span>{{ t('preview') }}</span><b>{{ costPreview }}</b><small>{{ hourlyPreview }}</small><small v-if="form.costMode==='MONTHLY'">{{ t('standardDays') }}：{{ defaultStandardDays ?? '—' }}</small></div>
        <el-alert v-if="form.costMode==='MONTHLY' && !defaultStandardDays" :title="t('missingRegion')" type="warning" :closable="false" show-icon />
        <div class="form-grid"><el-form-item :label="t('from')" required><el-date-picker v-model="form.effectiveFrom" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item :label="t('to')"><el-date-picker v-model="form.effectiveTo" type="date" value-format="YYYY-MM-DD" :disabled-date="disableEndDate" clearable /></el-form-item></div>
        <el-form-item :label="t('remark')" required><el-input v-model="form.remark" type="textarea" :rows="2" maxlength="500" show-word-limit :placeholder="t('remarkHint')" /></el-form-item>
        <el-collapse v-model="advanced" class="cost-advanced"><el-collapse-item name="settings" :title="t('advanced')">
          <el-form-item :label="t('mode')" required><el-select v-model="form.costMode"><el-option v-for="mode in ['MONTHLY','DAILY','HOURLY']" :key="mode" :value="mode" :label="modeLabel(mode)" /></el-select></el-form-item>
          <p class="hint">{{ t('conversion') }}</p>
        </el-collapse-item></el-collapse>
      </el-form>
      <template #footer><el-button @click="dialog=false">{{ t('cancel') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ t('save') }}</el-button></template>
    </el-dialog>
  </div>
</template>

<script setup name="BusinessCostPolicies">
const props=defineProps({staffUserId:{type:Number,default:null},embedded:{type:Boolean,default:false}})
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import useUserStore from '@/store/modules/user'
import { getBusinessStaffCostOptions, getBusinessStaffCostPolicies, saveBusinessStaffCostPolicy, deleteBusinessStaffCostPolicy, voidBusinessStaffCostPolicy } from '@/api/business/staff'

const { t } = useI18n({ useScope:'local', messages:{
  'zh-CN':{personName:'人员',region:'国家/地区',CN:'中国',VN:'越南',unknownRegion:'未设置',CNY:'人民币（CNY）',VND:'越南盾（VND）',USD:'美元（USD）',monthlyCost:'月度用人成本',dailyCost:'每日用人成本',hourlyCost:'每小时用人成本',preview:'系统折算',perDay:' / 人天',perHour:' / 小时',advanced:'高级设置：计价方式',missingRegion:'请先在人员管理中设置国家/地区：中国按21.75天、越南按26天折算。',remarkHint:'例如：转正后调整月度用人成本',invalidPeriod:'失效日期不能早于生效日期',invalidRateDay:'一个费率人天须为1至1440分钟',title:'用人成本',intro:'填写月度用人成本，系统自动折算日成本和小时成本，用于项目预算与已确认投入核算。',boundary:'内部费率不等于员工工资。工作日历决定容量，工作量单位决定分钟，费率人天基准决定计价；三者分别保存版本。',refresh:'刷新',person:'选择授权范围内的人员',add:'设置用人成本',selectPerson:'先选择人员查看费率历史',forbidden:'没有查看该人员内部费率的授权',empty:'尚未配置费率，确认投入后将保留待计价状态',version:'版本',rate:'内部费率',basis:'计价换算基准',minutesPerRateDay:'分钟 / 费率人天',daysPerMonth:'标准工作日 / 月',minutesPerHour:'分钟 / 小时',period:'生效区间',ongoing:'长期',status:'状态',active:'有效',voided:'已作废',evidence:'依据与历史',references:'来源引用',action:'操作',delete:'删除',void:'作废',newVersion:'设置用人成本',immutable:'已保存的费率以新版本变更。已确认的成本快照保留原依据；缺失费率补齐后可在核算页重试计价。',mode:'计价单位',MONTHLY:'每月',DAILY:'每人天',HOURLY:'每小时',currency:'币种',unitCost:'内部成本单价',standardDays:'月度标准工作天数',rateDayMinutes:'一个费率人天的分钟数',conversion:'月度成本按人员地区自动折算：中国21.75天，越南26天；换算规则由系统统一维护。',from:'生效日期（含）',to:'失效日期（含，可选）',remark:'调整依据',cancel:'取消',save:'保存新版本',saved:'费率版本已保存',required:'请填写单价、币种、生效日期和调整依据',invalidDays:'请填写月度标准工作天数',deleteConfirm:'删除未生效且未被引用的费率版本？',voidPrompt:'请填写作废原因，已核算历史快照仍会保留',confirm:'确认',done:'处理完成'},
  vi:{personName:'Nhân sự',region:'Quốc gia / khu vực',CN:'Trung Quốc',VN:'Việt Nam',unknownRegion:'Chưa thiết lập',CNY:'Nhân dân tệ (CNY)',VND:'Việt Nam đồng (VND)',USD:'Đô la Mỹ (USD)',monthlyCost:'Chi phí nhân sự mỗi tháng',dailyCost:'Chi phí mỗi ngày công',hourlyCost:'Chi phí mỗi giờ',preview:'Quy đổi tự động',perDay:' / ngày công',perHour:' / giờ',advanced:'Nâng cao: cách tính',missingRegion:'Thiết lập quốc gia trong quản lý nhân sự: Trung Quốc 21,75 ngày, Việt Nam 26 ngày.',remarkHint:'Ví dụ: điều chỉnh chi phí khi hết thử việc',invalidPeriod:'Ngày kết thúc không được trước ngày bắt đầu',invalidRateDay:'Một ngày đơn giá phải từ 1 đến 1440 phút',title:'Đơn giá nội bộ',intro:'Quản lý đơn giá và đơn vị theo ngày hiệu lực để hạch toán công việc đã xác nhận.',boundary:'Đơn giá nội bộ không phải tiền lương. Lịch quyết định năng lực, đơn vị khối lượng quy đổi phút, cơ sở ngày của đơn giá quyết định định giá. Ba phiên bản được lưu riêng.',refresh:'Làm mới',person:'Chọn nhân sự trong phạm vi được phép',add:'Thêm phiên bản đơn giá',selectPerson:'Chọn nhân sự để xem lịch sử đơn giá',forbidden:'Không có quyền xem đơn giá của nhân sự này',empty:'Chưa có đơn giá; công việc đã xác nhận sẽ chờ định giá',version:'Phiên bản',rate:'Đơn giá nội bộ',basis:'Cơ sở quy đổi',minutesPerRateDay:'phút / ngày đơn giá',daysPerMonth:'ngày chuẩn / tháng',minutesPerHour:'phút / giờ',period:'Khoảng hiệu lực',ongoing:'Không giới hạn',status:'Trạng thái',active:'Hiệu lực',voided:'Đã hủy',evidence:'Căn cứ và lịch sử',references:'Số tham chiếu',action:'Thao tác',delete:'Xóa',void:'Hủy hiệu lực',newVersion:'Thêm phiên bản đơn giá nội bộ',immutable:'Thay đổi bằng phiên bản mới. Chi phí đã xác nhận giữ căn cứ cũ; bổ sung đơn giá rồi thử định giá lại trong hạch toán.',mode:'Đơn vị tính',MONTHLY:'Mỗi tháng',DAILY:'Mỗi ngày công',HOURLY:'Mỗi giờ',currency:'Tiền tệ',unitCost:'Đơn giá chi phí nội bộ',standardDays:'Số ngày chuẩn trong tháng',rateDayMinutes:'Số phút trong một ngày đơn giá',conversion:'Chi phí tháng tự quy đổi theo khu vực: Trung Quốc 21,75 ngày, Việt Nam 26 ngày; hệ thống quản lý cơ sở quy đổi.',from:'Ngày bắt đầu (bao gồm)',to:'Ngày kết thúc (tùy chọn)',remark:'Căn cứ điều chỉnh',cancel:'Hủy',save:'Lưu phiên bản mới',saved:'Đã lưu phiên bản đơn giá',required:'Điền đơn giá, tiền tệ, ngày hiệu lực và căn cứ',invalidDays:'Điền số ngày chuẩn trong tháng',deleteConfirm:'Xóa phiên bản chưa có hiệu lực và chưa được tham chiếu?',voidPrompt:'Nhập lý do hủy; ảnh chụp chi phí lịch sử vẫn được giữ',confirm:'Xác nhận',done:'Đã xử lý'}
} })
const route=useRoute(),user=useUserStore(),people=ref([]),policies=ref([]),selectedUserId=ref(null),loading=ref(false),dialog=ref(false),saving=ref(false),retiring=ref(null),form=reactive({}),advanced=ref([])
const hasCostPermission=computed(()=>user.permissions.includes('*:*:*')||user.permissions.includes('business:staff:cost')||props.embedded&&user.permissions.includes('business:staff:list'))
const selectedPerson=computed(()=>people.value.find(p=>p.userId===selectedUserId.value))
const rawCostVisible=computed(()=>hasCostPermission.value&&selectedPerson.value?.rawCostVisible===true)
const canManage=computed(()=>rawCostVisible.value&&selectedPerson.value?.canManageCost===true)
const modeLabel=mode=>['MONTHLY','DAILY','HOURLY'].includes(mode)?t(mode):mode
const money=value=>value==null?'—':Number(value).toLocaleString(undefined,{maximumFractionDigits:4})
const defaultStandardDays=computed(()=>({CN:21.75,VN:26}[selectedPerson.value?.countryRegion]??null))
const regionName=computed(()=>['CN','VN'].includes(selectedPerson.value?.countryRegion)?t(selectedPerson.value.countryRegion):selectedPerson.value?.countryRegion||t('unknownRegion'))
const amountLabel=computed(()=>t(({MONTHLY:'monthlyCost',DAILY:'dailyCost',HOURLY:'hourlyCost'})[form.costMode]||'unitCost'))
const amountText=value=>value==null||!Number.isFinite(value)?'—':Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:4})
const dailyRate=computed(()=>form.unitCost==null?null:form.costMode==='MONTHLY'?(form.standardWorkDays>0?Number(form.unitCost)/form.standardWorkDays:null):form.costMode==='DAILY'?Number(form.unitCost):null)
const costPreview=computed(()=>form.costMode==='HOURLY'?`${amountText(form.unitCost)} ${form.currency}${t('perHour')}`:form.costMode==='MONTHLY'?`${amountText(form.unitCost)} ÷ ${form.standardWorkDays||'—'} = ${amountText(dailyRate.value)} ${form.currency}${t('perDay')}`:`${amountText(dailyRate.value)} ${form.currency}${t('perDay')}`)
const hourlyPreview=computed(()=>form.costMode==='HOURLY'?'':`${amountText(dailyRate.value!=null&&form.rateMinutesPerDay>0?dailyRate.value*60/form.rateMinutesPerDay:null)} ${form.currency}${t('perHour')}`)
const disableEndDate=date=>!!form.effectiveFrom&&date.getTime()<new Date(`${form.effectiveFrom}T00:00:00`).getTime()
const today=()=>{const date=new Date();return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
let sequence=0
async function loadPeople(){if(!hasCostPermission.value)return;loading.value=true;try{people.value=(await getBusinessStaffCostOptions()).data||[];const requested=props.staffUserId||Number(route.query.userId)||selectedUserId.value;if(people.value.some(p=>p.userId===requested))selectedUserId.value=requested;else selectedUserId.value=props.embedded?requested:people.value[0]?.userId||null;await loadPolicies()}finally{loading.value=false}}
async function loadPolicies(){const current=++sequence;policies.value=[];if(!rawCostVisible.value)return;loading.value=true;try{const response=await getBusinessStaffCostPolicies(selectedUserId.value);if(current===sequence)policies.value=response.data||[]}finally{if(current===sequence)loading.value=false}}
function openCreate(){Object.assign(form,{userId:selectedUserId.value,costMode:'MONTHLY',unitCost:null,currency:'CNY',standardWorkDays:defaultStandardDays.value,rateMinutesPerDay:480,effectiveFrom:today(),effectiveTo:null,remark:''});advanced.value=[];dialog.value=true}
async function save(){if(!canManage.value||saving.value)return;const body={...form,currency:form.currency?.trim().toUpperCase()};if(body.unitCost==null||!['CNY','VND','USD'].includes(body.currency)||!body.effectiveFrom||!body.remark?.trim())return ElMessage.warning(t('required'));if(body.costMode==='MONTHLY'&&!defaultStandardDays.value)return ElMessage.warning(t('missingRegion'));delete body.standardWorkDays;delete body.rateMinutesPerDay;if(body.effectiveTo&&body.effectiveTo<body.effectiveFrom)return ElMessage.warning(t('invalidPeriod'));body.remark=body.remark.trim();saving.value=true;try{await saveBusinessStaffCostPolicy(body);dialog.value=false;ElMessage.success(t('saved'));await loadPolicies()}finally{saving.value=false}}
const canDelete=row=>row.status==='ACTIVE'&&row.effectiveFrom>today()&&!(Number(row.referenceCount)>0)
async function retire(row){if(!canManage.value)return;try{if(canDelete(row)){await ElMessageBox.confirm(t('deleteConfirm'),t('confirm'),{type:'warning',confirmButtonText:t('confirm'),cancelButtonText:t('cancel')});retiring.value=row.policyId;await deleteBusinessStaffCostPolicy(row.policyId)}else{const {value}=await ElMessageBox.prompt(t('voidPrompt'),t('void'),{inputType:'textarea',inputValidator:v=>!!v?.trim()&&v.length<=500,confirmButtonText:t('confirm'),cancelButtonText:t('cancel')});retiring.value=row.policyId;await voidBusinessStaffCostPolicy(row.policyId,value.trim())}ElMessage.success(t('done'));await loadPolicies()}catch(error){if(!['cancel','close'].includes(error))throw error}finally{retiring.value=null}}
onMounted(loadPeople)
</script>

<style scoped>
.amount-grid{display:grid;grid-template-columns:minmax(0,1fr) 175px;gap:18px}.amount-grid .el-select{width:100%}.cost-preview{display:grid;gap:6px;padding:14px 18px;margin:0 0 18px;background:#f0f7f6;border-radius:8px;color:#315850}.cost-preview>span{font-size:12px}.cost-preview>b{font-size:17px}.cost-advanced{margin-top:10px}.cost-advanced :deep(.el-collapse-item__header){color:#526971}.rate-form>.el-alert{margin-bottom:16px}@media(max-width:450px){.amount-grid{grid-template-columns:1fr;gap:0}}
.rates-page{max-width:1500px;margin:auto}.rates-page header{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:20px}.eyebrow{font-size:11px;letter-spacing:2px;color:#64827f}.rates-page h1{font-size:28px;margin:8px 0;color:#243e45}.rates-page header p,.hint{color:#74848d;line-height:1.7}.rates-panel{margin-top:22px;border:1px solid #e3e9ed;border-radius:12px;background:#fff;padding:22px}.toolbar{display:flex;justify-content:space-between;gap:14px}.person-line{color:#526971;margin:20px 0}.rates-page small{display:block;color:#89969f;font-size:12px;margin-top:5px}.rate-form{margin-top:20px}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.form-grid .el-select,.form-grid :deep(.el-date-editor),.form-grid .el-input-number{width:100%}.hint{font-size:12px;margin-top:0}@media(max-width:650px){.rates-page header{align-items:flex-start}.rates-panel{padding:14px}.toolbar{flex-wrap:wrap}.form-grid{grid-template-columns:1fr;gap:0}}
</style>
