import request from '@/utils/request'
export const getFeishuConnections = () => request({ url:'/business/feishu/connections', method:'get' })
export const createFeishuConnection = data => request({ url:'/business/feishu/connections', method:'post', data })
export const getFeishuPeople = id => request({ url:`/business/feishu/${id}/people`, method:'get' })
export const getFeishuMappings = id => request({ url:`/business/feishu/${id}/mappings`, method:'get' })
export const createFeishuMapping = (id,data) => request({ url:`/business/feishu/${id}/mappings`, method:'post', data })
export const retireFeishuMapping = (id,data) => request({ url:`/business/feishu/mappings/${id}/retire`, method:'put', data })
export const getFeishuRuns = id => request({ url:`/business/feishu/${id}/runs`, method:'get' })
export const syncFeishu = (id,data) => request({ url:`/business/feishu/${id}/sync`, method:'post', data })
export const getFeishuRecords = params => request({ url:'/business/feishu/records', method:'get', params })
export const getFeishuQueryOptions = () => request({ url:'/business/feishu/query-options', method:'get' })
export const getFeishuCutoverStatus = (id,params) => request({ url:`/business/feishu/${id}/cutover-status`, method:'get', params })
export const validateFeishu = (id,data) => request({ url:`/business/feishu/${id}/validation`, method:'post', data })
export const activateFeishu = (id,data) => request({ url:`/business/feishu/${id}/activate`, method:'post', data })
export const getFeishuIssues = id => request({ url:`/business/feishu/${id}/issues`, method:'get' })
export const resolveFeishuIssue = (id,issueId,data) => request({ url:`/business/feishu/${id}/issues/${issueId}/resolve`, method:'post', data })
export const getFeishuReaders = id => request({ url:`/business/feishu/${id}/readers`, method:'get' })
export const getFeishuReaderCandidates = id => request({ url:`/business/feishu/${id}/reader-candidates`, method:'get' })
export const saveFeishuReader = (id,data) => request({ url:`/business/feishu/${id}/readers`, method:'post', data })

export const getFeishuDirectory = id => request({ url:`/business/feishu/${id}/directory`, method:'get', timeout:180000 })
export const batchFeishuMappings = (id,data) => request({ url:`/business/feishu/${id}/mappings/batch`, method:'post', data, timeout:180000 })
export const getFeishuSyncOverview = id => request({ url:`/business/feishu/${id}/sync-overview`, method:'get' })
