import request from '@/utils/request'

export const listBusinessProjects = params => request({ url: '/business/project/list', method: 'get', params })
export const getBusinessProject = id => request({ url: `/business/project/${id}`, method: 'get' })
export const getBusinessProjectSettlementStatus = id => request({ url: `/business/project/${id}/settlement-status`, method: 'get' })
export const closeBusinessProjectAccounting = (id, data) => request({ url: `/business/project/${id}/accounting-close`, method: 'post', data })
export const getBusinessProjectManagementFee = id => request({ url: `/business/project/${id}/management-fee`, method: 'get' })
export const saveBusinessProjectManagementFee = (id, data) => request({ url: `/business/project/${id}/management-fee`, method: 'put', data })
export const payBusinessProjectManagementFee = (id, data) => request({ url: `/business/project/${id}/management-fee/payment`, method: 'post', data })
export const listBusinessUsers = keyword => request({ url: '/business/project/user-options', method: 'get', params: { keyword } })
export const addBusinessProject = data => request({ url: '/business/project', method: 'post', data })
export const updateBusinessProject = data => request({ url: '/business/project', method: 'put', data })
export const getBusinessOperatingConfig = id => request({ url: `/business/project/${id}/operating-config`, method: 'get' })
export const updateBusinessProjectBudget = (id, data) => request({ url: `/business/project/${id}/budget`, method: 'put', data })
export const saveBusinessProjectKpi = data => request({ url: '/business/project/kpi', method: 'post', data })
export const retireBusinessProjectKpi = (projectId, kpiId) => request({ url: `/business/project/${projectId}/kpi/${kpiId}`, method: 'delete' })
export const saveBusinessStaffAllocation = data => request({ url: '/business/project/staff-allocation', method: 'post', data })
export const removeBusinessStaffAllocation = (projectId, allocationId) => request({ url: `/business/project/${projectId}/staff-allocation/${allocationId}`, method: 'delete' })
export const changeBusinessProjectOwner = (id, data) => request({ url: `/business/project/${id}/owner`, method: 'put', data })
export const submitBusinessProjectAcceptance = (id, data) => request({ url: `/business/project/${id}/acceptance`, method: 'post', data })
export const reviewBusinessProjectAcceptance = (id, data) => request({ url: `/business/project/${id}/acceptance/review`, method: 'put', data })
export const submitBusinessProjectStageAcceptance = (id, data) => request({ url: `/business/project/${id}/stage-acceptance`, method: 'post', data })
export const reviewBusinessProjectStageAcceptance = (id, milestoneId, data) => request({ url: `/business/project/${id}/stage-acceptance/${milestoneId}/review`, method: 'put', data })
export const transitionBusinessProject = (id, data) => request({ url: `/business/project/${id}/transition`, method: 'post', data })
export const saveBusinessProjectMember = data => request({ url: '/business/project/member', method: 'post', data })
export const removeBusinessProjectMember = (projectId, userId, retainTodayCost = false) => request({ url: `/business/project/${projectId}/member/${userId}`, method: 'delete', params: { retainTodayCost } })
export const saveBusinessMilestone = data => request({ url: '/business/project/milestone', method: 'post', data })
export const removeBusinessMilestone = (projectId, id) => request({ url: `/business/project/${projectId}/milestone/${id}`, method: 'delete' })
export const saveBusinessTask = data => request({ url: '/business/project/task', method: 'post', data })
export const submitBusinessTaskReport = data => request({ url: '/business/project/task-report', method: 'post', data })
export const submitBusinessProjectProgressReport = data => request({ url: '/business/project/progress-report', method: 'post', data })
export const removeBusinessTask = (projectId, id) => request({ url: `/business/project/${projectId}/task/${id}`, method: 'delete' })
export const enableBusinessTask = (projectId, id) => request({ url: `/business/project/${projectId}/task/${id}/enable`, method: 'post' })
export const saveBusinessRoutine = data => request({ url: '/business/project/routine', method: 'post', data })
export const removeBusinessRoutine = (projectId, id) => request({ url: `/business/project/${projectId}/routine/${id}`, method: 'delete' })
export const enableBusinessRoutine = (projectId, id, data) => request({ url: `/business/project/${projectId}/routine/${id}/enable`, method: 'post', data })
export const saveBusinessRoutineDailyTarget = data => request({ url: '/business/project/routine-daily-target', method: 'post', data })
export const submitBusinessRoutineReport = data => request({ url: '/business/project/routine-report', method: 'post', data })
export const saveBusinessRisk = data => request({ url: '/business/project/risk', method: 'post', data })
export const removeBusinessRisk = (projectId, id) => request({ url: `/business/project/${projectId}/risk/${id}`, method: 'delete' })
export const getBossBusinessDashboard = params => request({ url: '/business/boss/dashboard', method: 'get', params })
export const getBossBusinessPending = params => request({ url: '/business/boss/pending', method: 'get', params })
export const getBossProjectDirectory = () => request({ url: '/business/boss/project-directory', method: 'get' })
export const getMyBusinessDashboard = () => request({ url: '/business/my/dashboard', method: 'get' })
export const getBusinessOwnerWorkbench = projectId => request({ url: '/business/owner/dashboard', method: 'get', params: { projectId } })
export const getBusinessWorkDashboard = params => request({ url: '/business/work/dashboard', method: 'get', params })
export const saveBusinessWorkEffort = data => request({ url: '/business/work/effort', method: 'post', data })
export const confirmBusinessEffortWeek = (projectId, anchorDate) => request({ url: `/business/owner/${projectId}/effort-week/confirm`, method: 'post', params: { anchorDate } })
export const confirmBusinessMemberEffort = (projectId, memberUserId, data) => request({ url: `/business/owner/${projectId}/member/${memberUserId}/effort/confirm`, method: 'post', data })
export const returnBusinessMemberEffort = (projectId, memberUserId, data) => request({ url: `/business/owner/${projectId}/member/${memberUserId}/effort/return`, method: 'post', data })
