<template>
  <section class="business-product plan-panel" v-loading="loading">
    <header class="product-head">
      <div><h2>{{ tx('项目计划与变更','Kế hoạch và thay đổi') }}</h2><p>{{ tx('统一维护立项框架、按月收支和预算；生效后保存新版本，历史记录不会被覆盖。','Duy trì phạm vi, thu chi theo tháng và ngân sách theo phiên bản.') }}</p></div>
      <div class="row-actions"><el-button v-if="data.canRequestChange" v-hasPermi="['business:project:edit']" type="primary" @click="open(false)">{{ tx('申请计划变更','Đề nghị thay đổi') }}</el-button><el-button v-if="data.canForecast" v-hasPermi="['business:project:edit']" @click="open(true)">{{ tx('更新预测','Cập nhật dự báo') }}</el-button><el-button @click="load">{{ tx('刷新','Làm mới') }}</el-button></div>
    </header>
    <el-descriptions v-if="data.forecast" :column="2" border><el-descriptions-item :label="tx('预测结束日','Ngày kết thúc dự báo')">{{ data.forecast.forecastEndDate }}</el-descriptions-item><el-descriptions-item :label="tx('预测成本','Chi phí dự báo')">{{ data.forecast.forecastCost ?? '—' }} {{ project.baseCurrency }}</el-descriptions-item><el-descriptions-item :label="tx('预测依据','Căn cứ dự báo')">{{ data.forecast.reason }}</el-descriptions-item></el-descriptions>
    <h3>{{ tx('待办与变更记录','Yêu cầu và lịch sử thay đổi') }}</h3>
    <el-table :data="data.changes || []"><el-table-column prop="changeId" label="ID" width="70"/><el-table-column prop="baseVersion" :label="tx('原计划版本','Phiên bản gốc')" width="110"/><el-table-column :label="tx('状态','Trạng thái')" width="115"><template #default="{row}">{{ status(row.status) }}</template></el-table-column><el-table-column prop="requestUserName" :label="tx('申请人','Người đề nghị')"/><el-table-column prop="reason" :label="tx('变更原因','Lý do')" min-width="180"/><el-table-column prop="reviewReason" :label="tx('复核意见','Ý kiến duyệt')"/><el-table-column :label="tx('操作','Thao tác')" min-width="185"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看内容','Xem nội dung') }}</el-button><template v-if="row.canReview"><el-button v-hasPermi="['business:project:manage']" link type="success" @click="review(row,'APPROVED')">{{ tx('批准','Duyệt') }}</el-button><el-button v-hasPermi="['business:project:manage']" link type="warning" @click="review(row,'RETURNED')">{{ tx('退回','Trả lại') }}</el-button></template></template></el-table-column></el-table>
    <h3>{{ tx('已生效计划版本','Kế hoạch có hiệu lực') }}</h3>
    <el-table :data="data.baselines || []"><el-table-column prop="baselineVersion" :label="tx('版本','Phiên bản')" width="90"/><el-table-column :label="tx('授权方式','Cách phê duyệt')"><template #default="{row}">{{ source(row.authorizationSource) }}</template></el-table-column><el-table-column prop="authorizedUserName" :label="tx('确认人','Người xác nhận')"/><el-table-column prop="createTime" :label="tx('时间','Thời gian')"/><el-table-column :label="tx('操作','Thao tác')"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看快照','Xem bản chụp') }}</el-button></template></el-table-column></el-table>

    <el-dialog v-model="dialog" :title="forecast?tx('更新预测','Cập nhật dự báo'):tx('申请计划变更','Đề nghị thay đổi')" :width="forecast?'min(720px,96vw)':'min(1220px,96vw)'" append-to-body destroy-on-close>
      <el-form label-position="top" class="change-form">
        <template v-if="!forecast">
          <section class="change-section"><h3><span>01</span>基本信息</h3><el-row :gutter="16"><el-col :span="18"><el-form-item label="项目名称" required><el-input v-model="form.projectName" maxlength="160"/></el-form-item></el-col><el-col :span="6"><el-form-item label="优先级" required><el-select v-model="form.priority"><el-option label="低" value="LOW"/><el-option label="中" value="MEDIUM"/><el-option label="高" value="HIGH"/><el-option label="紧急" value="URGENT"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item :label="tx('范围与目标','Phạm vi và mục tiêu')" required><el-input v-model="form.objective" type="textarea" maxlength="1000" :rows="3"/></el-form-item></el-col><el-col :span="12"><el-form-item :label="tx('验收标准','Tiêu chí nghiệm thu')" required><el-input v-model="form.acceptanceCriteria" type="textarea" maxlength="2000" :rows="3"/></el-form-item></el-col><el-col :span="24"><el-form-item label="立项说明"><el-input v-model="form.applicationReason" type="textarea" maxlength="2000" :rows="2"/></el-form-item></el-col><el-col :span="8"><el-form-item :label="tx('计划开始日期','Ngày bắt đầu kế hoạch')" required><el-date-picker v-model="form.planStartDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-col><el-col :span="16"><el-form-item :label="tx('计划结束日期','Ngày kết thúc kế hoạch')" :required="!openEnded"><el-date-picker v-model="form.planEndDate" type="date" value-format="YYYY-MM-DD" :disabled="openEnded"/><el-checkbox v-model="openEnded" class="open-ended" @change="handleOpenEndedChange">{{ tx('不限期','Không thời hạn') }}</el-checkbox></el-form-item></el-col></el-row></section>

          <section class="change-section"><div class="section-head"><div><h3><span>02</span>收入计划</h3><p>字段与立项表单一致，按月份维护计划收入。</p></div><el-button type="primary" plain @click="addRevenue">增加收入</el-button></div><el-form-item label="收入模式"><el-input v-model="form.revenueModel" type="textarea" maxlength="1000" :rows="2" placeholder="说明项目如何获得收入"/></el-form-item><el-table :data="form.revenueLines" size="small" empty-text="暂无收入计划"><el-table-column label="收入方式" width="130"><template #default="{row}"><el-select v-model="row.revenueType"><el-option v-for="(label,key) in revenueTypes" :key="key" :label="label" :value="key"/></el-select></template></el-table-column><el-table-column label="收入项目" min-width="145"><template #default="{row}"><el-input v-model="row.itemName" maxlength="160"/></template></el-table-column><el-table-column label="预计金额" width="145"><template #default="{row}"><el-input-number v-model="row.expectedAmount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="发生方式" width="115"><template #default="{row}"><OccurrenceSelect v-model="row.occurrenceType"/></template></el-table-column><el-table-column label="收入月份 / 开始" width="145"><template #default="{row}"><ProposalMonthPicker v-model="row.expectedDate" :start-date="form.planStartDate" :end-date="openEnded?null:form.planEndDate" :before-start-months="6" :after-end-months="6"/></template></el-table-column><el-table-column label="测算依据" min-width="165"><template #default="{row}"><el-input v-model="row.assumptionText" maxlength="500"/></template></el-table-column><el-table-column width="52"><template #default="{$index}"><el-button link type="danger" @click="form.revenueLines.splice($index,1)">删</el-button></template></el-table-column></el-table></section>

          <section class="change-section"><div class="section-head"><div><h3><span>03</span>支出计划</h3><p>修改后与收入、人员成本一起重新计算每月盈利。</p></div><el-button type="primary" plain @click="addExpense">增加支出</el-button></div><el-table :data="form.expenseLines" size="small" empty-text="暂无支出计划"><el-table-column label="类别" width="120"><template #default="{row}"><el-select v-model="row.expenseCategory"><el-option v-for="(label,key) in expenseTypes" :key="key" :label="label" :value="key"/></el-select></template></el-table-column><el-table-column label="支出项目" min-width="135"><template #default="{row}"><el-input v-model="row.itemName" maxlength="160"/></template></el-table-column><el-table-column label="具体用途" min-width="150"><template #default="{row}"><el-input v-model="row.purpose" maxlength="500"/></template></el-table-column><el-table-column label="金额" width="140"><template #default="{row}"><el-input-number v-model="row.amount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="发生方式" width="115"><template #default="{row}"><OccurrenceSelect v-model="row.occurrenceType"/></template></el-table-column><el-table-column label="支出月份 / 开始" width="145"><template #default="{row}"><ProposalMonthPicker v-model="row.occurDate" :start-date="form.planStartDate" :end-date="openEnded?null:form.planEndDate" :before-start-months="6" :after-end-months="6"/></template></el-table-column><el-table-column label="收款方" min-width="125"><template #default="{row}"><el-input v-model="row.counterparty" maxlength="160"/></template></el-table-column><el-table-column width="52"><template #default="{$index}"><el-button link type="danger" @click="form.expenseLines.splice($index,1)">删</el-button></template></el-table-column></el-table></section>

          <section class="change-section"><h3><span>04</span>预算设置</h3><template v-if="form.budget"><BudgetControlFields v-model="form.budget"/><el-alert title="人员预算按照当前有效成员和投入比例重新计算；成员与投入比例请在“人员工作成本”页调整。" :closable="false"/><el-form-item v-if="(form.budget.mode||'TOTAL')==='TOTAL'" label="业务预算" required><el-input-number v-model="form.budget.businessAmount" :min="0" :precision="2"/></el-form-item><template v-if="openEnded"><el-form-item label="预算周期" required><el-select v-model="form.budget.cycle" @change="normalizeBudgetAnchor"><el-option label="周度" value="WEEK"/><el-option label="月度" value="MONTH"/><el-option label="季度" value="QUARTER"/><el-option label="年度" value="YEAR"/></el-select></el-form-item><el-form-item :label="budgetPeriodFieldLabel" required><BudgetPeriodPicker v-model:anchor-date="form.budget.anchorDate" :cycle="form.budget.cycle" /></el-form-item></template></template><el-form-item v-else :label="tx('预算上限（可不设置）','Giới hạn ngân sách (tùy chọn)')"><el-input-number v-model="form.budgetLimit" :min="0" :precision="2"/></el-form-item></section>

          <section class="change-section forecast-section"><div class="section-head"><div><h3><span>05</span>预计收支与盈利</h3><p>使用与立项表单相同的服务端计算规则，金额包含当前人员计划。</p></div><el-button :loading="previewLoading" @click="runPreview">重新测算</el-button></div><el-alert v-if="previewError" :title="previewError" type="warning" :closable="false" show-icon/><template v-if="previewBudget"><div class="finance-summary"><div><span>预计收入</span><b>{{ money(previewBudget.revenueAmount) }}</b></div><div><span>业务支出</span><b>{{ money(previewBudget.plannedBusinessAmount) }}</b></div><div><span>人员成本</span><b>{{ money(previewBudget.personnelAmount) }}</b></div><div><span>预计总成本</span><b>{{ money(previewBudget.plannedTotalCost) }}</b></div><div><span>预计利润</span><b :class="Number(previewBudget.profit)<0?'danger':'success'">{{ money(previewBudget.profit) }}</b></div></div><el-table :data="previewBudget.monthlyForecasts||[]" size="small" max-height="360"><el-table-column prop="month" label="月份" width="100"/><el-table-column label="预计收入" align="right"><template #default="{row}">{{ money(row.revenueAmount) }}</template></el-table-column><el-table-column label="业务支出" align="right"><template #default="{row}">{{ money(row.plannedBusinessAmount) }}</template></el-table-column><el-table-column label="人员成本" align="right"><template #default="{row}">{{ money(row.personnelAmount) }}</template></el-table-column><el-table-column label="预计总成本" align="right"><template #default="{row}">{{ money(row.plannedTotalCost) }}</template></el-table-column><el-table-column label="预计利润" align="right"><template #default="{row}"><b :class="Number(row.profit)<0?'danger':'success'">{{ money(row.profit) }}</b></template></el-table-column><el-table-column label="状态" min-width="150"><template #default="{row}">{{ row.issues?.join('；')||'已完成' }}</template></el-table-column></el-table></template></section>
        </template>
        <template v-else><el-form-item :label="tx('预测结束日','Ngày kết thúc dự báo')" required><el-date-picker v-model="form.forecastEndDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="tx('预测成本（可不填）','Chi phí dự báo (tùy chọn)')"><el-input-number v-model="form.forecastCost" :min="0" :precision="2"/></el-form-item></template>
        <el-form-item :label="tx('依据与原因','Căn cứ và lý do')" required><el-input v-model="form.reason" type="textarea" maxlength="2000" :rows="3"/></el-form-item><el-alert v-if="!forecast" :title="project.templateVersion==='LIGHT_V1'?tx('轻量模板由负责人授权生效，并保存完整新版本。','Mẫu gọn: người phụ trách phê duyệt phiên bản mới.'):tx('提交后由项目归属责任人复核，批准前继续使用原计划。','Người quản lý duyệt; kế hoạch cũ giữ hiệu lực đến khi được duyệt.')" :closable="false"/>
      </el-form><template #footer><el-button @click="dialog=false">{{ tx('取消','Hủy') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ tx('保存','Lưu') }}</el-button></template>
    </el-dialog>

    <el-drawer v-model="snapshotOpen" :title="tx('计划内容快照','Bản chụp kế hoạch')" size="min(900px,96vw)" append-to-body><el-descriptions :column="1" border><el-descriptions-item v-for="field in fields" :key="field.key" :label="tx(field.zh,field.vi)">{{ snapshot[field.key] ?? (field.key==='planEndDate'?tx('不限期','Không thời hạn'):'—') }}</el-descriptions-item></el-descriptions><h4>收入计划</h4><el-table :data="snapshot.revenueLines||[]" size="small"><el-table-column prop="itemName" label="收入项目"/><el-table-column prop="expectedDate" label="月份"/><el-table-column label="金额"><template #default="{row}">{{ money(row.expectedAmount) }}</template></el-table-column></el-table><h4>支出计划</h4><el-table :data="snapshot.expenseLines||[]" size="small"><el-table-column prop="itemName" label="支出项目"/><el-table-column prop="occurDate" label="月份"/><el-table-column label="金额"><template #default="{row}">{{ money(row.amount) }}</template></el-table-column></el-table><template v-if="snapshot.budget"><h4>按月预计收支与盈利</h4><el-table :data="snapshot.budget.monthlyForecasts||[]" size="small"><el-table-column prop="month" label="月份"/><el-table-column label="收入"><template #default="{row}">{{ money(row.revenueAmount) }}</template></el-table-column><el-table-column label="总成本"><template #default="{row}">{{ money(row.plannedTotalCost) }}</template></el-table-column><el-table-column label="利润"><template #default="{row}">{{ money(row.profit) }}</template></el-table-column></el-table></template></el-drawer>
  </section>
</template>

<script setup>
import { computed, defineComponent, h, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox, ElOption, ElSelect } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { getProjectPlan, previewProjectPlanChange, requestProjectPlanChange, reviewProjectPlanChange, saveProjectForecast } from '@/api/business/projectWork'
import BudgetPeriodPicker from '@/components/BudgetPeriodPicker/index.vue'
import BudgetControlFields from '@/components/BudgetControlFields/index.vue'
import ProposalMonthPicker from '@/views/business/proposal/ProposalMonthPicker.vue'
import '@/assets/styles/business-product.scss'

const OccurrenceSelect=defineComponent({props:{modelValue:String},emits:['update:modelValue'],setup(props,{emit}){const options={ONE_TIME:'一次性',DAILY:'每日',WEEKLY:'每周',MONTHLY:'每月'};return()=>h(ElSelect,{modelValue:props.modelValue,'onUpdate:modelValue':v=>emit('update:modelValue',v)},()=>Object.entries(options).map(([value,label])=>h(ElOption,{value,label})))}})
const props=defineProps({project:{type:Object,required:true}}),emit=defineEmits(['changed'])
const {locale}=useI18n(),tx=(zh,vi)=>locale.value==='vi-VN'?vi:zh
const data=ref({}),loading=ref(false),saving=ref(false),dialog=ref(false),forecast=ref(false),openEnded=ref(false),form=reactive({}),snapshotOpen=ref(false),snapshot=ref({}),previewLoading=ref(false),previewBudget=ref(null),previewError=ref('');let seq=0,previewSeq=0,previewTimer
const revenueTypes={SALES:'商品销售',SERVICE:'服务费',COMMISSION:'佣金',LIVE:'直播收入',OTHER:'其他',ADVERTISING:'广告',SUBSCRIPTION:'订阅',SAVING:'成本节约'}
const expenseTypes={PROCUREMENT:'采购',MARKETING:'推广',PLATFORM:'平台服务',TRAVEL:'差旅',OUTSOURCING:'外包',EQUIPMENT:'设备',LOGISTICS:'物流',OTHER:'其他'}
const budgetPeriodFieldLabel=computed(()=>({WEEK:'预算所属周',MONTH:'预算所属月份',QUARTER:'预算起始月份',YEAR:'预算所属年度'}[form.budget?.cycle]||'预算所属期间'))
const fields=[{key:'projectName',zh:'项目名称',vi:'Tên dự án'},{key:'priority',zh:'优先级',vi:'Ưu tiên'},{key:'objective',zh:'范围与目标',vi:'Phạm vi và mục tiêu'},{key:'applicationReason',zh:'立项说明',vi:'Mô tả'},{key:'acceptanceCriteria',zh:'验收标准',vi:'Tiêu chí nghiệm thu'},{key:'planStartDate',zh:'计划开始',vi:'Bắt đầu'},{key:'planEndDate',zh:'计划结束',vi:'Kết thúc'},{key:'revenueModel',zh:'收入模式',vi:'Mô hình doanh thu'},{key:'budgetLimit',zh:'预算上限',vi:'Giới hạn ngân sách'}]
const status=s=>({SUBMITTED:tx('待复核','Chờ duyệt'),APPROVED:tx('已批准','Đã duyệt'),RETURNED:tx('已退回','Đã trả lại')}[s]||s)
const source=s=>({OWNER_AUTHORIZED_CHANGE:tx('负责人授权变更','Người phụ trách phê duyệt'),SPONSOR_APPROVED_CHANGE:tx('归属责任人批准变更','Người quản lý phê duyệt'),SELF_AUTHORIZED:tx('负责人启动','Người phụ trách khởi tạo'),MANUAL_APPROVAL:tx('归属责任人批准','Người quản lý phê duyệt')}[s]||s)
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value))
async function load(){const n=++seq;loading.value=true;try{const r=await getProjectPlan(props.project.projectId);if(n===seq)data.value=r.data||{}}finally{if(n===seq)loading.value=false}}
function open(isForecast){forecast.value=isForecast;const current=data.value.currentPlan||{};openEnded.value=!(current.planEndDate??props.project.planEndDate);const budget=clone(current.budget||props.project.budget);const cycle=budget?.cycle;Object.assign(form,{version:data.value.version,projectName:current.projectName||props.project.projectName,priority:current.priority||props.project.priority||'MEDIUM',objective:current.objective??props.project.objective,applicationReason:current.applicationReason??props.project.remark??'',acceptanceCriteria:current.acceptanceCriteria??props.project.acceptanceCriteria,planStartDate:String(current.planStartDate||props.project.planStartDate||'').slice(0,10),planEndDate:openEnded.value?null:String(current.planEndDate||props.project.planEndDate||'').slice(0,10),revenueModel:current.revenueModel||'',revenueLines:clone(current.revenueLines||[]),expenseLines:clone(current.expenseLines||[]),budgetLimit:props.project.budgetLimit,budget:budget?{...budget,cycle:['WEEK','MONTH','QUARTER','YEAR'].includes(cycle)?cycle:'MONTH'}:null,forecastEndDate:data.value.forecast?.forecastEndDate||props.project.planEndDate,forecastCost:data.value.forecast?.forecastCost??null,reason:''});previewBudget.value=budget;previewError.value='';dialog.value=true;if(!isForecast)schedulePreview()}
function addRevenue(){form.revenueLines.push({scenario:'BASE',revenueType:'SALES',itemName:'',expectedAmount:0,occurrenceType:'ONE_TIME',expectedDate:null,assumptionText:''})}
function addExpense(){form.expenseLines.push({expenseCategory:'OTHER',itemName:'',purpose:'',counterparty:'',amount:0,occurrenceType:'ONE_TIME',occurDate:null,expenseType:'ONE_TIME',hasQuotation:'0'})}
function normalizeBudgetAnchor(){const value=String(form.budget?.anchorDate||form.planStartDate||'').slice(0,10);if(!value)return;const year=value.slice(0,4),month=Number(value.slice(5,7))||1;if(form.budget.cycle==='WEEK'){const date=new Date(Number(year),month-1,Number(value.slice(8,10))||1),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);form.budget.anchorDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}else form.budget.anchorDate=form.budget.cycle==='YEAR'?`${year}-01-01`:`${year}-${String(month).padStart(2,'0')}-01`}
function handleOpenEndedChange(value){if(value){form.planEndDate=null;if(form.budget){form.budget.cycle=form.budget.cycle==='PROJECT'?'MONTH':form.budget.cycle||'MONTH';normalizeBudgetAnchor()}}schedulePreview()}
function payload(){return{version:form.version,projectName:form.projectName,priority:form.priority,objective:form.objective,applicationReason:form.applicationReason,acceptanceCriteria:form.acceptanceCriteria,planStartDate:form.planStartDate,planEndDate:openEnded.value?null:form.planEndDate,revenueModel:form.revenueModel,revenueLines:clone(form.revenueLines||[]),expenseLines:clone(form.expenseLines||[]),budgetLimit:form.budgetLimit,budget:clone(form.budget),reason:form.reason}}
function complete(){if(!form.projectName?.trim()||!form.objective?.trim()||!form.acceptanceCriteria?.trim()||!form.planStartDate||!openEnded.value&&!form.planEndDate)return false;if(openEnded.value&&form.budget&&!form.budget.anchorDate)return false;return [...(form.revenueLines||[])].every(r=>r.revenueType&&r.itemName?.trim()&&r.expectedAmount!=null&&r.occurrenceType&&r.expectedDate)&&[...(form.expenseLines||[])].every(r=>r.expenseCategory&&r.itemName?.trim()&&r.purpose?.trim()&&r.amount!=null&&r.occurrenceType&&r.occurDate)}
function schedulePreview(){clearTimeout(previewTimer);if(!dialog.value||forecast.value)return;previewTimer=setTimeout(runPreview,450)}
async function runPreview(){if(!complete()){previewBudget.value=null;previewError.value='请先完整填写基本信息及已添加的收支明细';return}const n=++previewSeq;previewLoading.value=true;previewError.value='';try{const r=await previewProjectPlanChange(props.project.projectId,payload());if(n===previewSeq)previewBudget.value=r.data?.budget||null}catch(error){if(n===previewSeq){previewBudget.value=null;previewError.value=error?.msg||error?.message||'测算失败，请核对计划内容'}}finally{if(n===previewSeq)previewLoading.value=false}}
async function save(){if(!form.reason?.trim()||(forecast.value?!form.forecastEndDate:!complete()))return ElMessage.warning(tx('请完整填写必填内容','Điền các trường bắt buộc'));saving.value=true;try{await (forecast.value?saveProjectForecast:requestProjectPlanChange)(props.project.projectId,payload());dialog.value=false;await load();emit('changed')}finally{saving.value=false}}
async function review(row,decision){try{const {value}=await ElMessageBox.prompt(tx('请填写复核依据','Nhập căn cứ duyệt'),tx('复核计划变更','Duyệt thay đổi'),{inputType:'textarea',inputValidator:v=>!!v?.trim()||tx('请填写原因','Nhập lý do')});await reviewProjectPlanChange(row.changeId,{version:row.version,decision,reason:value.trim()});await load();emit('changed')}catch(e){if(!['cancel','close'].includes(e))await load()}}
function view(row){try{snapshot.value=typeof row.snapshotJson==='string'?JSON.parse(row.snapshotJson):row.snapshotJson||{};snapshotOpen.value=true}catch{ElMessage.error(tx('无法读取计划快照','Không thể đọc bản chụp'))}}
function money(value){return value==null?'待完善':`${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${props.project.baseCurrency||'CNY'}`}
watch(()=>[props.project.projectId,props.project.version],load,{immediate:true})
watch(()=>dialog.value&&!forecast.value?JSON.stringify([form.projectName,form.priority,form.objective,form.acceptanceCriteria,form.planStartDate,form.planEndDate,openEnded.value,form.revenueModel,form.revenueLines,form.expenseLines,form.budget]):'',schedulePreview)
</script>

<style scoped>
.plan-panel{padding:0}.plan-panel>h3{margin-top:24px}.product-head{flex-wrap:wrap;gap:12px}.product-head>div:first-child{flex:1 1 300px;min-width:0}.row-actions{flex:0 0 auto;flex-wrap:nowrap;gap:8px}.row-actions :deep(.el-button){height:32px;padding:0 12px;margin:0;font-size:14px;white-space:nowrap}.change-form{max-height:72vh;overflow:auto;padding-right:6px}.change-section{margin:0 0 18px;padding:18px;border:1px solid #dce5ef;border-radius:10px;background:#fff}.change-section>h3,.section-head h3{margin:0 0 16px;color:#25364b}.change-section h3 span{display:inline-flex;align-items:center;justify-content:center;margin-right:8px;padding:3px 7px;border-radius:5px;background:#eaf3ff;color:#2874c6;font-size:12px}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.section-head h3{margin-bottom:4px}.section-head p{margin:0 0 14px;color:#718096;font-size:13px}.open-ended{margin-left:12px}.change-section :deep(.el-input-number),.change-section :deep(.el-date-editor),.change-section :deep(.el-select){width:100%}.finance-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:10px;margin:14px 0}.finance-summary div{padding:14px;border-radius:8px;background:#f3f8f7}.finance-summary span{display:block;margin-bottom:6px;color:#718096}.finance-summary b{font-size:18px;color:#1b4f49}.finance-summary .danger{color:#d7474f}.finance-summary .success{color:#16935f}.forecast-section :deep(.el-alert){margin-bottom:12px}@media(max-width:760px){.product-head>div:first-child{flex-basis:auto}.finance-summary{grid-template-columns:1fr 1fr}}
</style>
