<template>
  <section class="business-product plan-panel" v-loading="loading">
    <header class="product-head"><div><h2>{{ tx('计划基线与变更','Kế hoạch và thay đổi') }}</h2><p>{{ tx('范围、时间与预算按版本保存；预测更新不覆盖承诺的计划。','Phạm vi, lịch và ngân sách được lưu theo phiên bản; dự báo không ghi đè kế hoạch đã cam kết.') }}</p></div><div class="row-actions"><el-button v-if="data.canRequestChange" v-hasPermi="['business:project:edit']" type="primary" @click="open(false)">{{ tx('申请计划变更','Đề nghị thay đổi') }}</el-button><el-button v-if="data.canForecast" v-hasPermi="['business:project:edit']" @click="open(true)">{{ tx('更新预测','Cập nhật dự báo') }}</el-button><el-button @click="load">{{ tx('刷新','Làm mới') }}</el-button></div></header>
    <el-descriptions v-if="data.forecast" :column="2" border><el-descriptions-item :label="tx('预测结束日','Ngày kết thúc dự báo')">{{ data.forecast.forecastEndDate }}</el-descriptions-item><el-descriptions-item :label="tx('预测成本','Chi phí dự báo')">{{ data.forecast.forecastCost ?? '—' }} {{ project.baseCurrency }}</el-descriptions-item><el-descriptions-item :label="tx('预测依据','Căn cứ dự báo')">{{ data.forecast.reason }}</el-descriptions-item></el-descriptions>
    <h3>{{ tx('待办与变更记录','Yêu cầu và lịch sử thay đổi') }}</h3>
    <el-table :data="data.changes || []"><el-table-column prop="changeId" label="ID" width="70"/><el-table-column prop="baseVersion" :label="tx('原基线版本','Phiên bản gốc')" width="110"/><el-table-column :label="tx('状态','Trạng thái')" width="115"><template #default="{row}">{{ status(row.status) }}</template></el-table-column><el-table-column prop="requestUserName" :label="tx('申请人','Người đề nghị')"/><el-table-column prop="reason" :label="tx('变更原因','Lý do')" min-width="180"/><el-table-column prop="reviewReason" :label="tx('复核意见','Ý kiến duyệt')"/><el-table-column :label="tx('操作','Thao tác')" min-width="185"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看内容','Xem nội dung') }}</el-button><template v-if="row.canReview"><el-button v-hasPermi="['business:project:manage']" link type="success" @click="review(row,'APPROVED')">{{ tx('批准','Duyệt') }}</el-button><el-button v-hasPermi="['business:project:manage']" link type="warning" @click="review(row,'RETURNED')">{{ tx('退回','Trả lại') }}</el-button></template></template></el-table-column></el-table>
    <h3>{{ tx('已生效基线','Kế hoạch có hiệu lực') }}</h3>
    <el-table :data="data.baselines || []"><el-table-column prop="baselineVersion" :label="tx('版本','Phiên bản')" width="90"/><el-table-column :label="tx('授权方式','Cách phê duyệt')"><template #default="{row}">{{ source(row.authorizationSource) }}</template></el-table-column><el-table-column prop="authorizedUserName" :label="tx('确认人','Người xác nhận')"/><el-table-column prop="createTime" :label="tx('时间','Thời gian')"/><el-table-column :label="tx('操作','Thao tác')"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看快照','Xem bản chụp') }}</el-button></template></el-table-column></el-table>
    <el-dialog v-model="dialog" :title="forecast?tx('更新预测','Cập nhật dự báo'):tx('申请计划变更','Đề nghị thay đổi')" width="min(720px,96vw)" append-to-body><el-form label-position="top">
      <template v-if="!forecast"><el-form-item :label="tx('范围与目标','Phạm vi và mục tiêu')" required><el-input v-model="form.objective" type="textarea" maxlength="1000"/></el-form-item><el-form-item :label="tx('验收标准','Tiêu chí nghiệm thu')" required><el-input v-model="form.acceptanceCriteria" type="textarea" maxlength="2000"/></el-form-item><el-form-item :label="tx('计划开始日期','Ngày bắt đầu kế hoạch')" required><el-date-picker v-model="form.planStartDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="tx('计划结束日期','Ngày kết thúc kế hoạch')" :required="!openEnded"><el-date-picker v-model="form.planEndDate" type="date" value-format="YYYY-MM-DD" :disabled="openEnded"/><el-checkbox v-model="openEnded" style="margin-left:12px" @change="handleOpenEndedChange">{{ tx('不限期','Không thời hạn') }}</el-checkbox></el-form-item><template v-if="project.budget"><BudgetControlFields v-model="form.budget"/><el-alert title="总预算将按当前有效人员计划重新计算，保存后生效。请先完成本期人员安排，再续编预算。" :closable="false"/><el-form-item label="总预算 / 人员预算"><el-input :model-value="`当前 ${project.budget.totalAmount} / ${project.budget.personnelAmount} ${project.baseCurrency}（保存时重新计算）`" readonly/></el-form-item><el-form-item v-if="(form.budget.mode||'TOTAL')==='TOTAL'" label="业务预算" required><el-input-number v-model="form.budget.businessAmount" :min="0" :precision="2"/></el-form-item><template v-if="openEnded"><el-form-item label="预算周期" required><el-select v-model="form.budget.cycle" @change="normalizeBudgetAnchor"><el-option label="周度" value="WEEK"/><el-option label="月度" value="MONTH"/><el-option label="季度" value="QUARTER"/></el-select></el-form-item><el-form-item :label="budgetPeriodFieldLabel" required><BudgetPeriodPicker v-model:anchor-date="form.budget.anchorDate" :cycle="form.budget.cycle" /></el-form-item></template></template><el-form-item v-else :label="tx('预算上限（可不设置）','Giới hạn ngân sách (tùy chọn)')"><el-input-number v-model="form.budgetLimit" :min="0" :precision="2"/></el-form-item></template>
      <template v-else><el-form-item :label="tx('预测结束日','Ngày kết thúc dự báo')" required><el-date-picker v-model="form.forecastEndDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="tx('预测成本（可不填）','Chi phí dự báo (tùy chọn)')"><el-input-number v-model="form.forecastCost" :min="0" :precision="2"/></el-form-item></template>
      <el-form-item :label="tx('依据与原因','Căn cứ và lý do')" required><el-input v-model="form.reason" type="textarea" maxlength="2000"/></el-form-item><el-alert v-if="!forecast" :title="project.templateVersion==='LIGHT_V1'?tx('轻量模板由负责人授权生效，并保存新版本。','Mẫu gọn: người phụ trách phê duyệt phiên bản mới.'):tx('提交后由项目归属责任人复核，批准前保留原基线。','Người chịu trách nhiệm quản lý duyệt; kế hoạch cũ giữ hiệu lực đến khi được duyệt.')" :closable="false"/>
    </el-form><template #footer><el-button @click="dialog=false">{{ tx('取消','Hủy') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ tx('保存','Lưu') }}</el-button></template></el-dialog>
    <el-drawer v-model="snapshotOpen" :title="tx('计划内容快照','Bản chụp kế hoạch')" size="min(780px,96vw)" append-to-body><el-descriptions :column="1" border><el-descriptions-item v-for="field in fields" :key="field.key" :label="tx(field.zh,field.vi)">{{ snapshot[field.key] ?? (field.key==='planEndDate'?tx('不限期','Không thời hạn'):'—') }}</el-descriptions-item></el-descriptions><el-descriptions v-if="snapshot.budget" :column="1" border><el-descriptions-item label="预算期间">{{ snapshot.budget.startDate }} 至 {{ snapshot.budget.endDate }}</el-descriptions-item><el-descriptions-item label="人员预算">{{ snapshot.budget.personnelAmount }}</el-descriptions-item><el-descriptions-item label="业务预算">{{ snapshot.budget.businessAmount }}</el-descriptions-item></el-descriptions><h4 v-if="snapshot.tasks?.length">{{ tx('任务清单','Nhiệm vụ') }}</h4><el-table v-if="snapshot.tasks?.length" :data="snapshot.tasks"><el-table-column prop="taskName" :label="tx('任务','Nhiệm vụ')"/><el-table-column prop="assigneeUserName" :label="tx('负责人','Người phụ trách')"/><el-table-column prop="dueDate" :label="tx('截止日期','Hạn')"/></el-table></el-drawer>
  </section>
</template>
<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getProjectPlan, requestProjectPlanChange, reviewProjectPlanChange, saveProjectForecast } from '@/api/business/projectWork'
import BudgetPeriodPicker from '@/components/BudgetPeriodPicker/index.vue'
import BudgetControlFields from '@/components/BudgetControlFields/index.vue'
import '@/assets/styles/business-product.scss'
const props=defineProps({project:{type:Object,required:true}}),emit=defineEmits(['changed'])
const {locale}=useI18n(),tx=(zh,vi)=>locale.value==='vi-VN'?vi:zh
const data=ref({}),loading=ref(false),saving=ref(false),dialog=ref(false),forecast=ref(false),openEnded=ref(false),form=reactive({}),snapshotOpen=ref(false),snapshot=ref({});let seq=0
const budgetPeriodFieldLabel=computed(()=>({WEEK:'预算所属周',MONTH:'预算所属月份',QUARTER:'预算起始月份'}[form.budget?.cycle]||'预算所属期间'))
const fields=[{key:'objective',zh:'范围与目标',vi:'Phạm vi và mục tiêu'},{key:'acceptanceCriteria',zh:'验收标准',vi:'Tiêu chí nghiệm thu'},{key:'planStartDate',zh:'计划开始',vi:'Bắt đầu'},{key:'planEndDate',zh:'计划结束',vi:'Kết thúc'},{key:'budgetLimit',zh:'预算上限',vi:'Giới hạn ngân sách'}]
const status=s=>({SUBMITTED:tx('待复核','Chờ duyệt'),APPROVED:tx('已批准','Đã duyệt'),RETURNED:tx('已退回','Đã trả lại')}[s]||s)
const source=s=>({OWNER_AUTHORIZED_CHANGE:tx('负责人授权变更','Người phụ trách phê duyệt'),SPONSOR_APPROVED_CHANGE:tx('归属责任人批准变更','Người quản lý phê duyệt'),OWNER_LAUNCH:tx('负责人启动','Người phụ trách khởi tạo'),SPONSOR_APPROVAL:tx('归属责任人批准','Người quản lý phê duyệt')}[s]||s)
async function load(){const n=++seq;loading.value=true;try{const r=await getProjectPlan(props.project.projectId);if(n===seq)data.value=r.data||{}}finally{if(n===seq)loading.value=false}}
function open(isForecast){forecast.value=isForecast;openEnded.value=!props.project.planEndDate;const currentCycle=props.project.budget?.cycle;Object.assign(form,{version:data.value.version,objective:props.project.objective,acceptanceCriteria:props.project.acceptanceCriteria,planStartDate:props.project.planStartDate,planEndDate:props.project.planEndDate,budgetLimit:props.project.budgetLimit,budget:props.project.budget?{...props.project.budget,cycle:['WEEK','MONTH','QUARTER'].includes(currentCycle)?currentCycle:'MONTH'}:null,forecastEndDate:data.value.forecast?.forecastEndDate||props.project.planEndDate,forecastCost:data.value.forecast?.forecastCost??null,reason:''});dialog.value=true}
function normalizeBudgetAnchor(){const source=String(form.budget?.anchorDate||form.planStartDate||'').slice(0,10);if(!source)return;const year=source.slice(0,4),month=Number(source.slice(5,7))||1;if(form.budget.cycle==='WEEK'){const date=new Date(Number(year),month-1,Number(source.slice(8,10))||1),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);form.budget.anchorDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}else{const normalizedMonth=month;form.budget.anchorDate=`${year}-${String(normalizedMonth).padStart(2,'0')}-01`}}
function handleOpenEndedChange(value){if(value){form.planEndDate=null;if(form.budget){form.budget.cycle=form.budget.cycle==='PROJECT'?'MONTH':form.budget.cycle||'MONTH';normalizeBudgetAnchor()}}}
async function save(){if(!form.reason?.trim()||(forecast.value?!form.forecastEndDate:!form.objective?.trim()||!form.acceptanceCriteria?.trim()||!form.planStartDate||!openEnded.value&&!form.planEndDate||openEnded.value&&form.budget&&!form.budget.anchorDate))return ElMessage.warning(tx('请完整填写必填内容','Điền các trường bắt buộc'));saving.value=true;try{await (forecast.value?saveProjectForecast:requestProjectPlanChange)(props.project.projectId,{...form,planEndDate:openEnded.value?null:form.planEndDate});dialog.value=false;await load();emit('changed')}finally{saving.value=false}}
async function review(row,decision){try{const {value}=await ElMessageBox.prompt(tx('请填写复核依据','Nhập căn cứ duyệt'),tx('复核计划变更','Duyệt thay đổi'),{inputType:'textarea',inputValidator:v=>!!v?.trim()||tx('请填写原因','Nhập lý do')});await reviewProjectPlanChange(row.changeId,{version:row.version,decision,reason:value.trim()});await load();emit('changed')}catch(e){if(!['cancel','close'].includes(e))await load()}}
function view(row){try{snapshot.value=typeof row.snapshotJson==='string'?JSON.parse(row.snapshotJson):row.snapshotJson||{};snapshotOpen.value=true}catch{ElMessage.error(tx('无法读取计划快照','Không thể đọc bản chụp'))}}
watch(()=>[props.project.projectId,props.project.version],load,{immediate:true})
</script>
<style scoped>.plan-panel{padding:0}.plan-panel h3{margin-top:24px}</style>
