<template>
  <section class="business-product plan-panel" v-loading="loading">
    <header class="product-head">
      <div><h2>{{ tx('项目计划与变更','Kế hoạch và thay đổi') }}</h2><p>{{ tx('沿用立项申请的计划明细；变更生效后更新当前项目数据，原版本留存备查。','Duy trì phạm vi, thu chi theo tháng và ngân sách theo phiên bản.') }}</p></div>
      <div class="row-actions"><el-button v-if="data.canRequestChange" v-hasPermi="['business:project:edit']" type="primary" @click="open(false)">{{ tx('申请计划变更','Đề nghị thay đổi') }}</el-button><el-button v-if="data.canForecast" v-hasPermi="['business:project:edit']" @click="open(true)">{{ tx('更新预测','Cập nhật dự báo') }}</el-button><el-button @click="load">{{ tx('刷新','Làm mới') }}</el-button></div>
    </header>
    <el-descriptions v-if="data.forecast" :column="2" border><el-descriptions-item :label="tx('预测结束日','Ngày kết thúc dự báo')">{{ data.forecast.forecastEndDate }}</el-descriptions-item><el-descriptions-item :label="tx('预测成本','Chi phí dự báo')">{{ data.forecast.forecastCost ?? '—' }} {{ project.baseCurrency }}</el-descriptions-item><el-descriptions-item :label="tx('预测依据','Căn cứ dự báo')">{{ data.forecast.reason }}</el-descriptions-item></el-descriptions>
    <h3>{{ tx('待办与变更记录','Yêu cầu và lịch sử thay đổi') }}</h3>
    <el-table :data="data.changes || []"><el-table-column prop="changeId" label="ID" width="70"/><el-table-column prop="baseVersion" :label="tx('原计划版本','Phiên bản gốc')" width="110"/><el-table-column :label="tx('状态','Trạng thái')" width="115"><template #default="{row}">{{ status(row.status) }}</template></el-table-column><el-table-column prop="requestUserName" :label="tx('申请人','Người đề nghị')"/><el-table-column prop="reason" :label="tx('变更原因','Lý do')" min-width="180"/><el-table-column prop="reviewReason" :label="tx('复核意见','Ý kiến duyệt')"/><el-table-column :label="tx('操作','Thao tác')" min-width="185"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看内容','Xem nội dung') }}</el-button><template v-if="row.canReview"><el-button v-hasPermi="['business:project:manage']" link type="success" @click="review(row,'APPROVED')">{{ tx('批准','Duyệt') }}</el-button><el-button v-hasPermi="['business:project:manage']" link type="warning" @click="review(row,'RETURNED')">{{ tx('退回','Trả lại') }}</el-button></template></template></el-table-column></el-table>
    <h3>{{ tx('已生效计划版本','Kế hoạch có hiệu lực') }}</h3>
    <el-table :data="data.baselines || []"><el-table-column prop="baselineVersion" :label="tx('版本','Phiên bản')" width="90"/><el-table-column :label="tx('授权方式','Cách phê duyệt')"><template #default="{row}">{{ source(row.authorizationSource) }}</template></el-table-column><el-table-column prop="authorizedUserName" :label="tx('确认人','Người xác nhận')"/><el-table-column prop="createTime" :label="tx('时间','Thời gian')"/><el-table-column :label="tx('操作','Thao tác')"><template #default="{row}"><el-button link @click="view(row)">{{ tx('查看快照','Xem bản chụp') }}</el-button></template></el-table-column></el-table>

    <el-dialog v-model="dialog" :title="forecast?tx('更新预测','Cập nhật dự báo'):tx('申请计划变更','Đề nghị thay đổi')" :width="forecast?'min(720px,96vw)':'min(1220px,96vw)'" append-to-body destroy-on-close>
      <el-form label-position="top" class="change-form">
        <template v-if="!forecast">
          <section class="change-section"><h3><span>01</span>{{ $tr("基本信息") }}</h3><el-row :gutter="16"><el-col :span="18"><el-form-item :label="$tr(&quot;项目名称&quot;)" required><el-input v-model="form.projectName" maxlength="160"/></el-form-item></el-col><el-col :span="6"><el-form-item :label="$tr(&quot;优先级&quot;)" required><el-select v-model="form.priority"><el-option :label="$tr(&quot;低&quot;)" value="LOW"/><el-option :label="$tr(&quot;中&quot;)" value="MEDIUM"/><el-option :label="$tr(&quot;高&quot;)" value="HIGH"/><el-option :label="$tr(&quot;紧急&quot;)" value="URGENT"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item :label="tx('范围与目标','Phạm vi và mục tiêu')" required><el-input v-model="form.objective" type="textarea" maxlength="1000" :rows="3"/></el-form-item></el-col><el-col :span="12"><el-form-item :label="tx('验收标准','Tiêu chí nghiệm thu')"><el-input v-model="form.acceptanceCriteria" type="textarea" maxlength="2000" :rows="3"/></el-form-item></el-col><el-col :span="24"><el-form-item :label="$tr(&quot;立项理由&quot;)" required><el-input v-model="form.applicationReason" type="textarea" maxlength="2000" :rows="2"/></el-form-item></el-col><el-col :span="8"><el-form-item :label="tx('计划开始日期','Ngày bắt đầu kế hoạch')" required><el-date-picker v-model="form.planStartDate" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-col><el-col :span="16"><el-form-item :label="tx('计划结束日期','Ngày kết thúc kế hoạch')" :required="!openEnded"><el-date-picker v-model="form.planEndDate" type="date" value-format="YYYY-MM-DD" :disabled="openEnded"/><el-checkbox v-model="openEnded" class="open-ended" @change="handleOpenEndedChange">{{ tx('不限期','Không thời hạn') }}</el-checkbox></el-form-item></el-col></el-row></section>

          <ProposalPlanDetails section-number="02" kind="targets" :form="form" :required-plan-sections="optionalPlanSections" :target-type-label="targetTypes" :target-unit-options="targetUnits" :revenue-type-label="revenueTypes" :plan-end-date="openEnded?null:form.planEndDate" :line-date-issue="lineDateIssue" :date-type="planDateType" @add-target="addTarget" @add-revenue="addRevenue" @change-target-type="changeTargetType"/>
          <el-form-item :label="$tr(&quot;收入模式&quot;)"><el-input v-model="form.revenueModel" type="textarea" maxlength="1000" :rows="2" :placeholder="$tr(&quot;说明项目如何获得收入&quot;)"/></el-form-item>
          <ProposalPlanDetails section-number="03" kind="revenue" :form="form" :required-plan-sections="optionalPlanSections" :target-type-label="targetTypes" :target-unit-options="targetUnits" :revenue-type-label="revenueTypes" :plan-end-date="openEnded?null:form.planEndDate" :line-date-issue="lineDateIssue" :date-type="planDateType" @add-target="addTarget" @add-revenue="addRevenue" @change-target-type="changeTargetType"/>

          <ProposalExpenseLines section-number="04" :form="form" :description="$tr(&quot;可选择项目开始月前 6 个月；有限期项目最晚可选结束月后 6 个月&quot;)" :expense-category-label="expenseTypes" :date-type="planDateType" :plan-end-date="openEnded?null:form.planEndDate" :line-date-issue="lineDateIssue" @add-expense="addExpense"/>

          <section class="change-section"><h3><span>05</span>{{ $tr("预算设置") }}</h3><template v-if="form.budget"><BudgetControlFields v-model="form.budget"/><el-alert :title="$tr(&quot;人员预算按照当前有效成员和投入比例重新计算；成员与投入比例请在“人员工作成本”页调整。&quot;)" :closable="false"/><el-form-item v-if="(form.budget.mode||'TOTAL')==='TOTAL'" :label="$tr(&quot;业务预算&quot;)" required><el-input-number v-model="form.budget.businessAmount" :min="0" :precision="2"/></el-form-item><template v-if="openEnded"><el-form-item :label="$tr(&quot;预算周期&quot;)" required><el-select v-model="form.budget.cycle" @change="normalizeBudgetAnchor"><el-option :label="$tr(&quot;周度&quot;)" value="WEEK"/><el-option :label="$tr(&quot;月度&quot;)" value="MONTH"/><el-option :label="$tr(&quot;季度&quot;)" value="QUARTER"/><el-option :label="$tr(&quot;年度&quot;)" value="YEAR"/></el-select></el-form-item><el-form-item :label="budgetPeriodFieldLabel" required><BudgetPeriodPicker v-model:anchor-date="form.budget.anchorDate" :cycle="form.budget.cycle" /></el-form-item></template></template><el-form-item v-else :label="tx('预算上限（可不设置）','Giới hạn ngân sách (tùy chọn)')"><el-input-number v-model="form.budgetLimit" :min="0" :precision="2"/></el-form-item></section>

          <section class="change-section forecast-section"><div class="section-head"><div><h3><span>06</span>{{ $tr("预计收支与盈利") }}</h3><p>{{ $tr("使用与立项表单相同的服务端计算规则，金额包含当前人员计划。") }}</p></div><el-button :loading="previewLoading" @click="runPreview">{{ $tr("重新测算") }}</el-button></div><el-alert v-if="previewError" :title="previewError" type="warning" :closable="false" show-icon/><template v-if="previewBudget"><div class="finance-summary"><div><span>{{ $tr("预计收入") }}</span><b>{{ money(previewBudget.revenueAmount) }}</b></div><div><span>{{ $tr("业务支出") }}</span><b>{{ money(previewBudget.plannedBusinessAmount) }}</b></div><div><span>{{ $tr("人员成本") }}</span><b>{{ money(previewBudget.personnelAmount) }}</b></div><div><span>{{ $tr("预计总成本") }}</span><b>{{ money(previewBudget.plannedTotalCost) }}</b></div><div><span>{{ $tr("预计利润") }}</span><b :class="Number(previewBudget.profit)<0?'danger':'success'">{{ money(previewBudget.profit) }}</b></div></div><el-table :data="previewBudget.monthlyForecasts||[]" size="small" max-height="360"><el-table-column prop="month" :label="$tr(&quot;月份&quot;)" width="100"/><el-table-column :label="$tr(&quot;预计收入&quot;)" align="right"><template #default="{row}">{{ money(row.revenueAmount) }}</template></el-table-column><el-table-column :label="$tr(&quot;业务支出&quot;)" align="right"><template #default="{row}">{{ money(row.plannedBusinessAmount) }}</template></el-table-column><el-table-column :label="$tr(&quot;人员成本&quot;)" align="right"><template #default="{row}">{{ money(row.personnelAmount) }}</template></el-table-column><el-table-column :label="$tr(&quot;预计总成本&quot;)" align="right"><template #default="{row}">{{ money(row.plannedTotalCost) }}</template></el-table-column><el-table-column :label="$tr(&quot;预计利润&quot;)" align="right"><template #default="{row}"><b :class="Number(row.profit)<0?'danger':'success'">{{ money(row.profit) }}</b></template></el-table-column><el-table-column :label="$tr(&quot;状态&quot;)" min-width="150"><template #default="{row}">{{ row.issues?.map(issue => $tr(issue)).join('；')||$tr("已完成") }}</template></el-table-column></el-table></template></section>
        </template>
        <template v-else><el-form-item :label="tx('预测结束日','Ngày kết thúc dự báo')" required><el-date-picker v-model="form.forecastEndDate" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="tx('预测成本（可不填）','Chi phí dự báo (tùy chọn)')"><el-input-number v-model="form.forecastCost" :min="0" :precision="2"/></el-form-item></template>
        <el-form-item :label="tx('依据与原因','Căn cứ và lý do')" required><el-input v-model="form.reason" type="textarea" maxlength="2000" :rows="3"/></el-form-item><el-alert v-if="!forecast" :title="project.templateVersion==='LIGHT_V1'?tx('轻量模板由负责人授权生效，并保存完整新版本。','Mẫu gọn: người phụ trách phê duyệt phiên bản mới.'):tx('提交后由项目归属责任人复核，批准前继续使用原计划。','Người quản lý duyệt; kế hoạch cũ giữ hiệu lực đến khi được duyệt.')" :closable="false"/>
      </el-form><template #footer><el-button @click="dialog=false">{{ tx('取消','Hủy') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ tx('保存','Lưu') }}</el-button></template>
    </el-dialog>

    <el-drawer v-model="snapshotOpen" :title="tx('计划内容快照','Bản chụp kế hoạch')" size="min(900px,96vw)" append-to-body><el-descriptions :column="1" border><el-descriptions-item v-for="field in fields" :key="field.key" :label="tx(field.zh,field.vi)">{{ snapshot[field.key] ?? (field.key==='planEndDate'?tx('不限期','Không thời hạn'):'—') }}</el-descriptions-item></el-descriptions><h4>{{ $tr("项目验收目标") }}</h4><el-table :data="snapshot.targetLines||[]" size="small"><el-table-column prop="targetName" :label="$tr(&quot;目标名称&quot;)"/><el-table-column prop="targetValue" :label="$tr(&quot;目标值&quot;)"/><el-table-column prop="unit" :label="$tr(&quot;单位&quot;)" :formatter="(row, column, value) => $tr(value)"/><el-table-column prop="acceptanceEvidence" :label="$tr(&quot;验收依据&quot;)"/></el-table><h4>{{ $tr("收入计划") }}</h4><el-table :data="snapshot.revenueLines||[]" size="small"><el-table-column prop="itemName" :label="$tr(&quot;收入项目&quot;)"/><el-table-column prop="expectedDate" :label="$tr(&quot;月份&quot;)"/><el-table-column :label="$tr(&quot;金额&quot;)"><template #default="{row}">{{ money(row.expectedAmount) }}</template></el-table-column></el-table><h4>{{ $tr("支出计划") }}</h4><el-table :data="snapshot.expenseLines||[]" size="small"><el-table-column prop="itemName" :label="$tr(&quot;支出项目&quot;)"/><el-table-column prop="occurDate" :label="$tr(&quot;月份&quot;)"/><el-table-column :label="$tr(&quot;金额&quot;)"><template #default="{row}">{{ money(row.amount) }}</template></el-table-column></el-table><template v-if="snapshot.budget"><h4>{{ $tr("按月预计收支与盈利") }}</h4><el-table :data="snapshot.budget.monthlyForecasts||[]" size="small">
      <el-table-column prop="month" :label="$tr(&quot;月份&quot;)" width="95"/>
      <el-table-column :label="$tr(&quot;收入&quot;)" min-width="125"><template #default="{row}">{{ money(row.revenueAmount) }}</template></el-table-column>
      <el-table-column :label="$tr(&quot;业务支出&quot;)" min-width="125"><template #default="{row}">{{ money(row.plannedBusinessAmount) }}</template></el-table-column>
      <el-table-column :label="$tr(&quot;人员成本&quot;)" min-width="125"><template #default="{row}">{{ money(row.personnelAmount) }}</template></el-table-column>
      <el-table-column :label="$tr(&quot;总成本&quot;)" min-width="125"><template #default="{row}">{{ money(row.plannedTotalCost) }}</template></el-table-column>
      <el-table-column :label="$tr(&quot;利润&quot;)" min-width="125"><template #default="{row}">{{ money(row.profit) }}</template></el-table-column>
      <el-table-column :label="$tr(&quot;状态&quot;)" min-width="180"><template #default="{row}">{{ row.issues?.map(issue => $tr(issue)).join('；') || $tr("已完成") }}</template></el-table-column>
    </el-table></template></el-drawer>
  </section>
</template>

<script setup>
import { translateText } from '@/locales/translate'

import { computed, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { getProjectPlan, previewProjectPlanChange, requestProjectPlanChange, reviewProjectPlanChange, saveProjectForecast } from '@/api/business/projectWork'
import BudgetPeriodPicker from '@/components/BudgetPeriodPicker/index.vue'
import BudgetControlFields from '@/components/BudgetControlFields/index.vue'
import ProposalPlanDetails from '@/views/business/proposal/ProposalPlanDetails.vue'
import ProposalExpenseLines from '@/views/business/proposal/ProposalExpenseLines.vue'
import '@/assets/styles/business-product.scss'

const props=defineProps({project:{type:Object,required:true}}),emit=defineEmits(['changed'])
const {locale}=useI18n(),tx=(zh,vi)=>locale.value==='vi-VN'?vi:zh
const data=ref({}),loading=ref(false),saving=ref(false),dialog=ref(false),forecast=ref(false),openEnded=ref(false),form=reactive({}),snapshotOpen=ref(false),snapshot=ref({}),previewLoading=ref(false),previewBudget=ref(null),previewError=ref('');let seq=0,previewSeq=0,previewTimer
const revenueTypes={SALES:translateText("商品销售"),SERVICE:translateText("服务费"),COMMISSION:translateText("佣金"),LIVE:translateText("直播收入"),OTHER:translateText("其他"),ADVERTISING:translateText("广告"),SUBSCRIPTION:translateText("订阅"),SAVING:translateText("成本节约")}
const expenseTypes={PROCUREMENT:translateText("采购"),MARKETING:translateText("推广"),PLATFORM:translateText("平台服务"),TRAVEL:translateText("差旅"),OUTSOURCING:translateText("外包"),EQUIPMENT:translateText("设备"),LOGISTICS:translateText("物流"),OTHER:translateText("其他")}
const targetTypes={FINANCIAL:translateText("财务"),QUANTITY:translateText("数量"),SCHEDULE:translateText("进度"),QUALITY:translateText("质量"),EFFICIENCY:translateText("效率"),GROWTH:translateText("增长"),CUSTOMER:translateText("客户"),COMPLIANCE:translateText("合规"),OTHER:translateText("价值 / 其他"),DELIVERY:translateText("成果验收")}
const targetUnits=computed(()=>['个','件','条','次','人','单','份','套','台','场','天','小时','分钟',...(props.project.baseCurrency==='CNY'?['元','万元']:[props.project.baseCurrency||'CNY']),'%','分'])
const optionalPlanSections={targets:false,revenue:false}
const planDateType=computed(()=>openEnded.value&&form.budget?.cycle==='WEEK'?'date':'month')
const budgetPeriodFieldLabel=computed(()=>({WEEK:translateText("预算所属周"),MONTH:translateText("预算所属月份"),QUARTER:translateText("预算起始月份"),YEAR:translateText("预算所属年度")}[form.budget?.cycle]||translateText("预算所属期间")))
const fields=[{key:'projectName',zh:translateText("项目名称"),vi:'Tên dự án'},{key:'priority',zh:translateText("优先级"),vi:'Ưu tiên'},{key:'objective',zh:translateText("范围与目标"),vi:'Phạm vi và mục tiêu'},{key:'applicationReason',zh:translateText("立项说明"),vi:'Mô tả'},{key:'acceptanceCriteria',zh:translateText("验收标准"),vi:'Tiêu chí nghiệm thu'},{key:'planStartDate',zh:translateText("计划开始"),vi:'Bắt đầu'},{key:'planEndDate',zh:translateText("计划结束"),vi:'Kết thúc'},{key:'revenueModel',zh:translateText("收入模式"),vi:'Mô hình doanh thu'},{key:'budgetLimit',zh:translateText("预算上限"),vi:'Giới hạn ngân sách'}]
const status=s=>({SUBMITTED:tx('待复核','Chờ duyệt'),APPROVED:tx('已批准','Đã duyệt'),RETURNED:tx('已退回','Đã trả lại')}[s]||s)
const source=s=>({OWNER_AUTHORIZED_CHANGE:tx('负责人授权变更','Người phụ trách phê duyệt'),SPONSOR_APPROVED_CHANGE:tx('归属责任人批准变更','Người quản lý phê duyệt'),SELF_AUTHORIZED:tx('负责人启动','Người phụ trách khởi tạo'),MANUAL_APPROVAL:tx('归属责任人批准','Người quản lý phê duyệt')}[s]||s)
const clone=value=>value==null?value:JSON.parse(JSON.stringify(value))
async function load(){const n=++seq;loading.value=true;try{const r=await getProjectPlan(props.project.projectId);if(n===seq)data.value=r.data||{}}finally{if(n===seq)loading.value=false}}
function open(isForecast){forecast.value=isForecast;const current=data.value.currentPlan||{};openEnded.value=!(current.planEndDate??props.project.planEndDate);const budget=clone(current.budget||props.project.budget);const cycle=budget?.cycle;Object.assign(form,{version:data.value.version,projectName:current.projectName||props.project.projectName,priority:current.priority||props.project.priority||'MEDIUM',objective:current.objective??props.project.objective,applicationReason:current.applicationReason??props.project.remark??'',acceptanceCriteria:current.acceptanceCriteria??props.project.acceptanceCriteria,planStartDate:String(current.planStartDate||props.project.planStartDate||'').slice(0,10),planEndDate:openEnded.value?null:String(current.planEndDate||props.project.planEndDate||'').slice(0,10),revenueModel:current.revenueModel||'',revenueLines:clone(current.revenueLines||[]),expenseLines:clone(current.expenseLines||[]),targetLines:clone(current.targetLines||[]),budgetLimit:props.project.budgetLimit,budget:budget?{...budget,cycle:['WEEK','MONTH','QUARTER','YEAR'].includes(cycle)?cycle:'MONTH'}:null,forecastEndDate:data.value.forecast?.forecastEndDate||props.project.planEndDate,forecastCost:data.value.forecast?.forecastCost??null,reason:''});previewBudget.value=budget;previewError.value='';dialog.value=true;if(!isForecast)schedulePreview()}
function addRevenue(){form.revenueLines.push({scenario:'BASE',revenueType:'SALES',itemName:'',expectedAmount:0,occurrenceType:'ONE_TIME',expectedDate:null,assumptionText:''})}
function addExpense(){form.expenseLines.push({expenseCategory:'OTHER',itemName:'',purpose:'',counterparty:'',amount:0,occurrenceType:'ONE_TIME',occurDate:null,expenseType:'ONE_TIME',hasQuotation:'0'})}
function addTarget(){const delivery=['VALUE','HYBRID'].includes(props.project.accountingMode);form.targetLines.push({targetType:delivery?'DELIVERY':'QUANTITY',targetName:'',targetValue:delivery?1:0,unit:delivery?'项':'',dueDate:null,acceptanceEvidence:''})}
function changeTargetType(row){if(row.targetType==='DELIVERY'){row.targetValue=1;row.unit='项'}else if(row.targetType!=='FINANCIAL'&&['元','万元','CNY','USD','VND'].includes(row.unit)){row.targetValue=null;row.unit='';ElMessage.info(translateText("目标类型已变化，请重新选择单位并填写目标值"))}}
function lineDateIssue(value,rule='project'){
  if(!value)return ''
  const date=String(value).slice(0,10),month=date.slice(0,7),start=String(form.planStartDate||'').slice(0,10),end=openEnded.value?'':String(form.planEndDate||'').slice(0,10)
  const shifted=(base,offset)=>{const [year,number]=base.split('-').map(Number),date=new Date(year,number-1+offset,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`}
  if(rule==='revenue'||rule==='expense')return start&&month<shifted(start,-6)||end&&month>shifted(end,6)?translateText("月份须在项目开始月前 6 个月至结束月后 6 个月内"):''
  return start&&date<start||end&&date>end?translateText("日期须在项目起止范围内"):''
}
function normalizeBudgetAnchor(){const value=String(form.budget?.anchorDate||form.planStartDate||'').slice(0,10);if(!value)return;const year=value.slice(0,4),month=Number(value.slice(5,7))||1;if(form.budget.cycle==='WEEK'){const date=new Date(Number(year),month-1,Number(value.slice(8,10))||1),offset=(date.getDay()+6)%7;date.setDate(date.getDate()-offset);form.budget.anchorDate=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}else form.budget.anchorDate=form.budget.cycle==='YEAR'?`${year}-01-01`:`${year}-${String(month).padStart(2,'0')}-01`}
function handleOpenEndedChange(value){if(value){form.planEndDate=null;if(form.budget){form.budget.cycle=form.budget.cycle==='PROJECT'?'MONTH':form.budget.cycle||'MONTH';normalizeBudgetAnchor()}}schedulePreview()}
function payload(){return{version:form.version,projectName:form.projectName,priority:form.priority,objective:form.objective,applicationReason:form.applicationReason,acceptanceCriteria:form.acceptanceCriteria,planStartDate:form.planStartDate,planEndDate:openEnded.value?null:form.planEndDate,revenueModel:form.revenueModel,revenueLines:clone(form.revenueLines||[]),expenseLines:clone(form.expenseLines||[]),targetLines:clone(form.targetLines||[]),budgetLimit:form.budgetLimit,budget:clone(form.budget),reason:form.reason}}
function forecastPayload(){return{version:form.version,forecastEndDate:form.forecastEndDate,forecastCost:form.forecastCost,reason:form.reason}}
function complete(){if(!form.projectName?.trim()||!form.objective?.trim()||!form.applicationReason?.trim()||!form.planStartDate||!openEnded.value&&!form.planEndDate)return false;if(openEnded.value&&form.budget&&!form.budget.anchorDate)return false;return [...(form.targetLines||[])].every(r=>r.targetType&&r.targetName?.trim()&&(r.targetType==='DELIVERY'||r.targetValue!=null&&r.unit?.trim())&&r.acceptanceEvidence?.trim())&&[...(form.revenueLines||[])].every(r=>r.revenueType&&r.itemName?.trim()&&r.expectedAmount!=null&&r.occurrenceType&&r.expectedDate)&&[...(form.expenseLines||[])].every(r=>r.expenseCategory&&r.itemName?.trim()&&r.purpose?.trim()&&r.amount!=null&&r.occurrenceType&&r.occurDate)}
function schedulePreview(){clearTimeout(previewTimer);if(!dialog.value||forecast.value)return;previewTimer=setTimeout(runPreview,450)}
async function runPreview(){if(!complete()){previewBudget.value=null;previewError.value=translateText("请先完整填写基本信息及已添加的收支明细");return}const n=++previewSeq;previewLoading.value=true;previewError.value='';try{const r=await previewProjectPlanChange(props.project.projectId,payload());if(n===previewSeq)previewBudget.value=r.data?.budget||null}catch(error){if(n===previewSeq){previewBudget.value=null;previewError.value=error?.msg||error?.message||translateText("测算失败，请核对计划内容")}}finally{if(n===previewSeq)previewLoading.value=false}}
async function save(){if(!form.reason?.trim()||(forecast.value?!form.forecastEndDate:!complete()))return ElMessage.warning(tx('请完整填写必填内容','Điền các trường bắt buộc'));if(forecast.value&&form.planStartDate&&form.forecastEndDate<form.planStartDate)return ElMessage.warning(tx('预测结束日不能早于项目计划开始日','Ngày kết thúc dự báo không được trước ngày bắt đầu kế hoạch'));saving.value=true;try{await (forecast.value?saveProjectForecast:requestProjectPlanChange)(props.project.projectId,forecast.value?forecastPayload():payload());dialog.value=false;await load();emit('changed')}finally{saving.value=false}}
async function review(row,decision){try{const {value}=await ElMessageBox.prompt(tx('请填写复核依据','Nhập căn cứ duyệt'),tx('复核计划变更','Duyệt thay đổi'),{inputType:'textarea',inputValidator:v=>!!v?.trim()||tx('请填写原因','Nhập lý do')});await reviewProjectPlanChange(row.changeId,{version:row.version,decision,reason:value.trim()});await load();emit('changed')}catch(e){if(!['cancel','close'].includes(e))await load()}}
function view(row){try{const value=row.displaySnapshot??row.snapshotJson;snapshot.value=typeof value==='string'?JSON.parse(value):value||{};snapshotOpen.value=true}catch{ElMessage.error(tx('无法读取计划快照','Không thể đọc bản chụp'))}}
function money(value){return value==null?translateText("待完善"):`${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${props.project.baseCurrency||'CNY'}`}
watch(()=>[props.project.projectId,props.project.version],load,{immediate:true})
watch(()=>dialog.value&&!forecast.value?JSON.stringify([form.projectName,form.priority,form.objective,form.acceptanceCriteria,form.planStartDate,form.planEndDate,openEnded.value,form.revenueModel,form.revenueLines,form.expenseLines,form.targetLines,form.budget]):'',schedulePreview)
</script>

<style scoped>
.plan-panel{padding:0}.plan-panel>h3{margin-top:24px}.product-head{flex-wrap:wrap;gap:12px}.product-head>div:first-child{flex:1 1 300px;min-width:0}.row-actions{flex:0 0 auto;flex-wrap:nowrap;gap:8px}.row-actions :deep(.el-button){height:32px;padding:0 12px;margin:0;font-size:14px;white-space:nowrap}.change-form{max-height:72vh;overflow:auto;padding-right:6px}.change-section{margin:0 0 18px;padding:18px;border:1px solid #dce5ef;border-radius:10px;background:#fff}.change-section>h3,.section-head h3{margin:0 0 16px;color:#25364b}.change-section h3 span{display:inline-flex;align-items:center;justify-content:center;margin-right:8px;padding:3px 7px;border-radius:5px;background:#eaf3ff;color:#2874c6;font-size:12px}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.section-head h3{margin-bottom:4px}.section-head p{margin:0 0 14px;color:#718096;font-size:13px}.open-ended{margin-left:12px}.change-section :deep(.el-input-number),.change-section :deep(.el-date-editor),.change-section :deep(.el-select){width:100%}.finance-summary{display:grid;grid-template-columns:repeat(5,minmax(130px,1fr));gap:10px;margin:14px 0}.finance-summary div{padding:14px;border-radius:8px;background:#f3f8f7}.finance-summary span{display:block;margin-bottom:6px;color:#718096}.finance-summary b{font-size:18px;color:#1b4f49}.finance-summary .danger{color:#d7474f}.finance-summary .success{color:#16935f}.forecast-section :deep(.el-alert){margin-bottom:12px}@media(max-width:760px){.product-head>div:first-child{flex-basis:auto}.finance-summary{grid-template-columns:1fr 1fr}}
</style>
