<template>
 <div class="business-product feishu-integration" v-loading="loading">
  <header class="product-head"><div><h1>{{ canManage ? tr('飞书集成管理','Tích hợp Feishu') : tr('假勤接入验收','Nghiệm thu nguồn chấm công') }}</h1><p>{{ canManage ? tr('管理连接、人员映射与只读同步。应用密钥只在服务端配置。','Quản lý kết nối, ánh xạ và đồng bộ chỉ đọc. Bí mật ứng dụng chỉ được cấu hình phía máy chủ.') : tr('核对真实假勤样本、处理遗留事项，并确认公司的来源切换日期。','Đối chiếu mẫu chấm công thực tế, xử lý tồn đọng và xác nhận ngày chuyển nguồn của công ty.') }}</p></div><el-button icon="Refresh" @click="load">{{ tr('刷新','Làm mới') }}</el-button></header>
  <el-alert v-if="canManage && data.configuration && (!data.configuration.enabled || !data.configuration.appIdPresent || !data.configuration.appSecretPresent || !data.configuration.tenantKeyPresent)" :title="tr('服务端授权尚未完整配置。可先建立连接与映射，真实同步和切换需授权就绪。','Cấu hình ủy quyền chưa đầy đủ. Có thể chuẩn bị ánh xạ; đồng bộ thật và chuyển đổi cần ủy quyền.')" type="warning" :closable="false" show-icon/>
  <div class="product-toolbar"><el-select v-model="connectionId" @change="loadConnection"><el-option v-for="c in data.connections || []" :key="c.connectionId" :label="`${c.companyName || c.companyDeptId} · ${status(c.state)}`" :value="c.connectionId"/></el-select><el-button v-if="canManage" @click="openConnection">{{ tr('新增连接','Thêm kết nối') }}</el-button></div>
  <template v-if="connection">
   <div class="product-summary integration-summary">
    <div><span>{{ tr('最近同步结果','Kết quả đồng bộ gần nhất') }}</span><b><el-tag :type="statusType(runs[0]?.status)" effect="light">{{ runs[0] ? status(runs[0].status) : tr('尚无记录','Chưa có') }}</el-tag></b><small>{{ tr('最近完整同步','Đồng bộ đầy đủ gần nhất') }} · {{ formatTime(connection.lastCompleteAt) }}</small></div>
    <div class="attention-card"><span>{{ tr('待处理问题','Vấn đề cần xử lý') }}</span><b>{{ issuesLoaded ? openIssues.length : '—' }}</b><el-button link type="primary" @click="tab='issues';issueFilter='OPEN'">{{ tr('查看待办','Xem việc cần xử lý') }}</el-button><small>{{ tr('按最近 200 条问题统计','Thống kê tối đa 200 vấn đề gần nhất') }}</small></div>
    <div><span>{{ tr('考勤来源状态','Trạng thái nguồn chấm công') }}</span><b>{{ status(connection.state) }}</b><small>{{ connection.state === 'PARALLEL' ? tr('正在核对飞书数据，尚未切换业务来源','Đang đối chiếu Feishu, chưa chuyển nguồn nghiệp vụ') : tr('切换生效日','Ngày chuyển đổi') + ' · ' + (connection.effectiveDate || '—') }}</small></div>
   </div>
   <el-alert v-if="loadFailed" :title="tr('部分列表读取失败，请刷新重试。空列表不代表没有问题。','Không tải được một số danh sách. Hãy làm mới; danh sách trống không có nghĩa là không có vấn đề.')" type="error" :closable="false" show-icon/>
   <el-alert v-if="running" :title="tr('后台同步中，每五秒刷新批次进度；未完成前不会推进完整同步水位。','Đang đồng bộ nền, cập nhật mỗi 5 giây; mốc đầy đủ chỉ thay đổi khi hoàn tất.')" type="info" :closable="false"/><el-tabs v-model="tab" @tab-change="name => name === 'cutover' && loadCutover()">
    <el-tab-pane v-if="canManage" :label="tr('人员映射','Ánh xạ nhân sự')" name="mappings"><div class="product-toolbar"><el-button type="primary" :disabled="running" @click="openMapping">{{ tr('手动填写标识','Nhập mã thủ công') }}</el-button><el-button type="primary" :disabled="running || !connection.configured" @click="batchMapping.open(connectionId, syncDates?.[0] || today())">{{ tr('从飞书批量关联','Liên kết hàng loạt từ Feishu') }}</el-button></div><el-alert :title="tr('按飞书考勤员工标识绑定本地人员，不按姓名自动合并。停用或改绑不修改历史记录。','Liên kết bằng mã nhân sự chấm công Feishu, không tự ghép theo tên. Dừng ánh xạ không sửa lịch sử.')" type="info" :closable="false"/><el-table :data="mappings"><el-table-column :label="tr('人员','Nhân sự')"><template #default="{row}">{{ row.userName || personName(row.userId) }}</template></el-table-column><el-table-column prop="externalUserId" :label="tr('飞书员工标识','Mã nhân sự Feishu')" min-width="150"/><el-table-column prop="effectiveFrom" :label="tr('生效日期','Ngày hiệu lực')"/><el-table-column prop="effectiveTo" :label="tr('截止日期','Ngày kết thúc')"/><el-table-column :label="tr('状态','Trạng thái')"><template #default="{row}">{{ status(row.status) }}</template></el-table-column><el-table-column :label="tr('操作','Thao tác')"><template #default="{row}"><el-button v-if="row.status === 'CONFIRMED'" link type="danger" :disabled="running" @click="retire(row)">{{ tr('停用','Dừng') }}</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane :label="tr('同步记录','Lịch sử đồng bộ')" name="runs">
     <div v-if="canManage && overview.configuration" class="sync-policy"><b>{{ tr('自动同步','Đồng bộ tự động') }} · {{ overview.configuration.pollEnabled ? tr('已开启','Đã bật') : tr('未开启','Chưa bật') }}</b><span v-if="overview.configuration.pollEnabled">{{ tr('间隔','Khoảng cách') }} {{ overview.configuration.pollDelayMs / 60000 }} {{ tr('分钟，回看','phút, xem lại') }} {{ overview.configuration.pollLookbackDays }} {{ tr('天（含当天）','ngày (gồm hôm nay)') }}</span><span>{{ tr('已绑定人员','Nhân sự đã liên kết') }} {{ activeCoverage.length }} · {{ tr('时区','Múi giờ') }} {{ overview.timezone }}</span><el-button link type="primary" @click="coverageOpen=true">{{ tr('查看人员覆盖','Xem phạm vi nhân sự') }}</el-button></div>
     <p v-if="canManage" class="muted">{{ tr('手动补拉每次最多 7 天。重试会按原日期范围重新读取当前有效关联人员，并保留旧批次。','Mỗi lần bổ sung tối đa 7 ngày. Thử lại đọc nhân sự đang liên kết trong cùng khoảng ngày, giữ nguyên lần chạy cũ.') }}</p><div v-if="canManage" class="product-toolbar"><el-date-picker v-model="syncDates" type="daterange" value-format="YYYY-MM-DD"/><el-button type="primary" :loading="syncing" :disabled="running || !connection.configured" @click="runSync">{{ tr('同步所选范围','Đồng bộ khoảng đã chọn') }}</el-button></div><el-table :data="runs"><el-table-column prop="runId" :label="tr('批次','Lần chạy')" width="85"/><el-table-column :label="tr('范围','Phạm vi')" min-width="185"><template #default="{row}">{{ row.windowStart }} — {{ row.windowEnd }}</template></el-table-column><el-table-column :label="tr('状态','Trạng thái')"><template #default="{row}">{{ status(row.status) }}</template></el-table-column><el-table-column :label="tr('分片进度','Tiến độ phần')" width="110"><template #default="{row}">{{ row.completedChunks || 0 }}/{{ row.expectedChunks || 0 }}</template></el-table-column><el-table-column prop="receivedCount" :label="tr('读取数','Số bản ghi')"/><el-table-column prop="rejectedCount" :label="tr('待核实','Cần kiểm tra')"/><el-table-column :label="tr('完成时间','Thời gian kết thúc')" min-width="170"><template #default="{row}">{{ formatTime(row.finishedAt) }}</template></el-table-column><el-table-column :label="tr('异常说明','Mô tả lỗi')" min-width="220"><template #default="{row}">{{ issueText(row.errorCode) }}<small v-if="row.errorCode" class="technical-code">{{ row.errorCode }}</small></template></el-table-column><el-table-column v-if="canManage" :label="tr('操作','Thao tác')" width="130"><template #default="{row}"><el-button v-if="['FAILED','PARTIAL'].includes(row.status)" link type="primary" :disabled="running || syncing || !connection.configured" @click="retryRun(row)">{{ tr('按原范围重试','Thử lại phạm vi cũ') }}</el-button></template></el-table-column></el-table></el-tab-pane>
    <el-tab-pane v-if="canAudit" :label="tr('验收与切换','Nghiệm thu và chuyển đổi')" name="cutover">
     <el-alert :title="tr('先核对真实出勤、请假、更正、跨日、未映射和故障恢复样本，处理完本地遗留申请，再切换。同步故障不会自动恢复本地请假。','Kiểm tra mẫu thật, điều chỉnh, qua ngày, chưa ánh xạ và phục hồi; xử lý hồ sơ cũ trước khi chuyển. Lỗi đồng bộ không tự mở lại nghỉ phép nội bộ.')" type="warning" :closable="false"/>
     <div class="product-toolbar"><el-date-picker v-model="effectiveDate" type="date" value-format="YYYY-MM-DD" @change="loadCutover"/><el-button @click="loadCutover">{{ tr('检查切换条件','Kiểm tra điều kiện') }}</el-button><el-button v-hasPermi="['business:attendance:cutover']" @click="openValidation">{{ tr('登记真实样本验收','Ghi nhận kiểm tra mẫu thật') }}</el-button><el-button v-if="cutover?.canActivate" v-hasPermi="['business:attendance:cutover']" type="warning" :loading="saving" @click="activate">{{ tr('确认切换','Xác nhận chuyển đổi') }}</el-button></div>
     <ul v-if="cutover?.blockers?.length"><li v-for="(b,i) in cutover.blockers" :key="i">{{ blockerText(typeof b==='string'?b:b.label || b.message || b.code) }}</li></ul><el-result v-else-if="cutover?.canActivate" icon="success" :title="tr('检查通过，等待业务负责人确认','Đã đạt kiểm tra, chờ người phụ trách xác nhận')"/>
     <el-table :data="cutover?.validations || []"><el-table-column :label="tr('验收情景','Tình huống kiểm tra')"><template #default="{row}">{{ cases[row.caseType] || row.caseType }}</template></el-table-column><el-table-column prop="runId" :label="tr('批次','Lần chạy')"/><el-table-column :label="tr('结论','Kết luận')"><template #default="{row}">{{ row.passed ? tr('通过','Đạt') : tr('未通过','Chưa đạt') }}</template></el-table-column><el-table-column prop="connectionVersion" :label="tr('映射版本','Phiên bản ánh xạ')"/><el-table-column prop="reason" :label="tr('验收说明','Ghi chú')" min-width="200" show-overflow-tooltip/><el-table-column prop="validatedAt" :label="tr('登记时间','Thời gian ghi')"/></el-table><p v-if="cutover?.pendingLocalCount != null">{{ tr('本地遗留待办','Hồ sơ nội bộ đang chờ') }}: {{ cutover.pendingLocalCount }}</p>
    </el-tab-pane>
   <el-tab-pane :label="tr('同步问题','Vấn đề đồng bộ')" name="issues">
    <div class="issue-heading"><div><h2>{{ tr('同步问题处理','Xử lý vấn đề đồng bộ') }}</h2><p>{{ tr('查看原因与处理建议，核实后登记处理结果。','Xem nguyên nhân và hướng xử lý, sau đó ghi nhận kết quả đã xác minh.') }}</p></div><span class="muted">{{ tr('展示最近 200 条问题','Hiển thị tối đa 200 vấn đề gần nhất') }}</span></div>
    <div class="product-toolbar issue-toolbar">
     <el-radio-group v-model="issueFilter" :aria-label="tr('问题状态','Trạng thái vấn đề')"><el-radio-button value="OPEN">{{ tr('待处理','Cần xử lý') }} ({{ issuesLoaded ? openIssues.length : '—' }})</el-radio-button><el-radio-button value="RESOLVED">{{ tr('已处理','Đã xử lý') }}</el-radio-button><el-radio-button value="ALL">{{ tr('全部','Tất cả') }}</el-radio-button></el-radio-group>
     <el-input v-model="issueSearch" clearable :placeholder="tr('搜索问题、编号或处理记录','Tìm vấn đề, mã hoặc ghi nhận xử lý')" :aria-label="tr('搜索同步问题','Tìm vấn đề đồng bộ')" class="issue-search" prefix-icon="Search"/>
    </div>
    <el-table :data="filteredIssues" :empty-text="!issuesLoaded ? tr('问题列表未加载，请刷新','Chưa tải danh sách; hãy làm mới') : issueSearch ? tr('没有匹配的问题','Không có vấn đề phù hợp') : tr('当前筛选下没有问题','Không có vấn đề theo bộ lọc')">
     <el-table-column :label="tr('问题与处理建议','Vấn đề và hướng xử lý')" min-width="360"><template #default="{row}"><div class="issue-title"><el-tag size="small" :type="row.issueCode === 'SOURCE_REVISION_REQUIRES_REVIEW' ? 'warning' : 'info'">{{ issueCategory(row.issueCode) }}</el-tag><strong>{{ issueText(row.issueCode) }}</strong></div><p class="issue-hint">{{ issueAdvice(row.issueCode) }}</p></template></el-table-column>
     <el-table-column :label="tr('发现时间','Thời gian phát hiện')" width="185"><template #default="{row}">{{ formatTime(row.createdAt) }}</template></el-table-column>
     <el-table-column :label="tr('状态','Trạng thái')" width="115"><template #default="{row}"><el-tag :type="statusType(row.status)">{{ status(row.status) }}</el-tag></template></el-table-column>
     <el-table-column :label="tr('操作','Thao tác')" :width="canManage ? 180 : 100"><template #default="{row}"><el-button link type="primary" @click="selectedIssue=row;issueDetailOpen=true">{{ tr('查看详情','Xem chi tiết') }}</el-button><el-button v-if="canManage && row.status === 'OPEN'" link type="primary" @click="resolve(row)">{{ tr('登记处理','Ghi xử lý') }}</el-button></template></el-table-column>
    </el-table>
   </el-tab-pane>
    <el-tab-pane v-if="canAudit" :label="tr('组织查询授权','Quyền tra cứu công ty')" name="readers"><el-alert :title="tr('范围授权和账号角色权限共同生效。被授权人员还须具有假勤组织查询权限，技术管理权限不会自动获得业务数据。','Phạm vi và quyền vai trò phải cùng có hiệu lực. Nhân sự cần quyền tra cứu nghỉ phép công ty; quyền kỹ thuật không tự cấp dữ liệu nghiệp vụ.')" type="info" :closable="false"/><div class="product-toolbar"><el-select v-model="readerUserId" filterable :placeholder="tr('选择本公司查询人员','Chọn nhân sự công ty')"><el-option v-for="p in readerCandidates" :key="p.userId" :label="p.userName" :value="p.userId"/></el-select><el-button type="primary" :disabled="!readerUserId" @click="authorizeReader">{{ tr('授权查询','Cấp quyền tra cứu') }}</el-button></div><el-table :data="readers"><el-table-column :label="tr('人员','Nhân sự')"><template #default="{row}">{{ readerCandidates.find(p=>p.userId===row.userId)?.userName || row.userId }}</template></el-table-column><el-table-column :label="tr('状态','Trạng thái')"><template #default="{row}">{{ row.enabled ? tr('已授权','Đã cấp quyền') : tr('已撤销','Đã thu hồi') }}</template></el-table-column><el-table-column prop="updatedAt" :label="tr('更新时间','Cập nhật lúc')"/><el-table-column :label="tr('操作','Thao tác')"><template #default="{row}"><el-button v-if="row.enabled" link type="danger" @click="revokeReader(row)">{{ tr('撤销授权','Thu hồi quyền') }}</el-button></template></el-table-column></el-table></el-tab-pane>
   </el-tabs>
  </template>
  <el-empty v-else :description="tr('请先建立飞书连接','Tạo kết nối Feishu trước')"/>
  <BatchMapping v-if="canManage" ref="batchMapping" @saved="load"/>
  <el-dialog v-model="coverageOpen" :title="tr('人员同步覆盖','Phạm vi đồng bộ nhân sự')" width="min(1000px,94vw)" append-to-body><el-alert :title="tr('日期范围表示已读取的考勤记录，不保证区间每天都有数据。无记录不代表缺勤。','Phạm vi ngày là bản ghi đã đọc, không đảm bảo mỗi ngày đều có dữ liệu. Thiếu bản ghi không có nghĩa là vắng mặt.')" type="info" :closable="false"/><el-table :data="overview.people || []"><el-table-column prop="userName" :label="tr('人员','Nhân sự')"/><el-table-column :label="tr('当前同步范围','Phạm vi hiện tại')"><template #default="{row}">{{ activeCoverage.includes(row)?tr('已纳入','Đã đưa vào'):tr('不在生效期','Ngoài thời gian hiệu lực') }}</template></el-table-column><el-table-column :label="tr('已读取日期范围','Khoảng ngày đã đọc')" min-width="220"><template #default="{row}">{{ row.firstDate ? row.firstDate + ' — ' + row.lastDate : tr('尚未读取','Chưa đọc') }}</template></el-table-column><el-table-column :label="tr('已读取天数','Số ngày đã đọc')" width="125"><template #default="{row}">{{ row.dateCount || 0 }}</template></el-table-column><el-table-column :label="tr('最近读取时间','Lần đọc gần nhất')" min-width="180"><template #default="{row}">{{ formatTime(row.lastReadAt) }}</template></el-table-column></el-table></el-dialog>
  <el-dialog v-model="issueDetailOpen" :title="tr('同步问题详情','Chi tiết vấn đề đồng bộ')" width="min(700px,94vw)" append-to-body>
   <template v-if="selectedIssue">
    <h3>{{ issueText(selectedIssue.issueCode) }}</h3><el-alert :title="issueAdvice(selectedIssue.issueCode)" type="info" :closable="false" show-icon/>
    <dl class="issue-details"><dt>{{ tr('状态','Trạng thái') }}</dt><dd><el-tag :type="statusType(selectedIssue.status)">{{ status(selectedIssue.status) }}</el-tag></dd><dt>{{ tr('发现时间','Thời gian phát hiện') }}</dt><dd>{{ formatTime(selectedIssue.createdAt) }}</dd><dt>{{ tr('问题编号 / 同步批次','Mã vấn đề / Lần đồng bộ') }}</dt><dd>#{{ selectedIssue.issueId }} / #{{ selectedIssue.runId }}</dd><dt>{{ tr('来源记录编号','Mã bản ghi nguồn') }}</dt><dd>{{ selectedIssue.observationId || '—' }}</dd><dt>{{ tr('技术代码','Mã kỹ thuật') }}</dt><dd>{{ selectedIssue.issueCode }}</dd><dt>{{ tr('处理记录','Ghi nhận xử lý') }}</dt><dd>{{ selectedIssue.resolution || tr('尚未登记','Chưa ghi nhận') }}</dd><dt v-if="selectedIssue.resolvedAt">{{ tr('处理时间','Thời gian xử lý') }}</dt><dd v-if="selectedIssue.resolvedAt">{{ formatTime(selectedIssue.resolvedAt) }}</dd></dl>
   </template>
   <template #footer><el-button @click="issueDetailOpen=false">{{ tr('关闭','Đóng') }}</el-button><el-button v-if="canManage && selectedIssue?.status === 'OPEN'" type="primary" @click="resolve(selectedIssue)">{{ tr('登记处理','Ghi xử lý') }}</el-button></template>
  </el-dialog>
  <el-dialog v-model="connectionOpen" :title="tr('新增飞书连接','Thêm kết nối Feishu')" width="min(600px,94vw)" append-to-body><el-form label-position="top"><el-form-item :label="tr('公司','Công ty')" required><el-select v-model="connectionForm.companyDeptId" style="width:100%"><el-option v-for="c in data.companies || []" :key="c.companyDeptId" :label="c.companyName" :value="c.companyDeptId"/></el-select></el-form-item><el-form-item :label="tr('飞书企业标识','Mã doanh nghiệp Feishu')" required><el-input v-model="connectionForm.tenantKey"/></el-form-item><el-form-item :label="tr('业务时区','Múi giờ nghiệp vụ')" required><el-select v-model="connectionForm.timezone"><el-option label="Asia/Shanghai" value="Asia/Shanghai"/><el-option label="Asia/Ho_Chi_Minh" value="Asia/Ho_Chi_Minh"/></el-select></el-form-item></el-form><template #footer><el-button @click="connectionOpen=false">{{ tr('取消','Hủy') }}</el-button><el-button type="primary" :loading="saving" @click="saveConnection">{{ tr('保存连接','Lưu kết nối') }}</el-button></template></el-dialog>
  <el-dialog v-model="mappingOpen" :title="tr('建立人员映射','Tạo ánh xạ nhân sự')" width="min(600px,94vw)" append-to-body><el-form label-position="top"><el-form-item :label="tr('本地人员','Nhân sự nội bộ')" required><el-select v-model="mappingForm.userId" filterable style="width:100%"><el-option v-for="p in people" :key="p.userId" :label="p.userName || p.nickName" :value="p.userId"/></el-select></el-form-item><el-form-item :label="tr('飞书考勤员工标识','Mã nhân sự chấm công Feishu')" required><el-input v-model="mappingForm.externalUserId"/></el-form-item><el-form-item :label="tr('生效日期','Ngày hiệu lực')" required><el-date-picker v-model="mappingForm.effectiveFrom" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="tr('截止日期（可选）','Ngày kết thúc (tùy chọn)')"><el-date-picker v-model="mappingForm.effectiveTo" type="date" value-format="YYYY-MM-DD"/></el-form-item></el-form><template #footer><el-button @click="mappingOpen=false">{{ tr('取消','Hủy') }}</el-button><el-button type="primary" :loading="saving" @click="saveMapping">{{ tr('保存映射','Lưu ánh xạ') }}</el-button></template></el-dialog>
  <el-dialog v-model="validationOpen" :title="tr('真实样本验收','Kiểm tra mẫu thực tế')" width="min(700px,95vw)" append-to-body><el-form label-position="top"><el-form-item :label="tr('样本类型','Loại mẫu')"><el-select v-model="validationForm.caseType"><el-option v-for="(label,key) in cases" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item :label="tr('真实同步批次','Lần đồng bộ thật')" required><el-select v-model="validationForm.runId"><el-option v-for="r in runs.filter(item => item.status === 'COMPLETE')" :key="r.runId" :label="`${r.runId} · ${r.windowStart} · ${status(r.status)}`" :value="r.runId"/></el-select></el-form-item><el-form-item v-if="!['UNMAPPED','RECOVERY'].includes(validationForm.caseType)" :label="tr('来源记录编号（从假勤查询获取）','Mã bản ghi nguồn (lấy từ tra cứu)')" required><el-input-number v-model="validationForm.observationId" :min="1" :precision="0"/></el-form-item><el-form-item v-else :label="tr('已核实处理的实际问题','Vấn đề thực tế đã xử lý')" required><el-select v-model="validationForm.issueId" style="width:100%"><el-option v-for="i in issues.filter(item => item.status === 'RESOLVED')" :key="i.issueId" :label="i.issueId + ' · ' + issueText(i.issueCode)" :value="i.issueId"/></el-select></el-form-item><el-form-item v-for="field in ['expectedResult','sourceEvidence','localResult','reason']" :key="field" :label="validationLabels[field]" required><el-input v-model="validationForm[field]" type="textarea" :rows="2" maxlength="1000"/></el-form-item><el-radio-group v-model="validationForm.passed"><el-radio :value="true">{{ tr('核对通过','Đạt kiểm tra') }}</el-radio><el-radio :value="false">{{ tr('有差异，未通过','Có khác biệt, chưa đạt') }}</el-radio></el-radio-group><br/><el-checkbox v-model="validationChecked">{{ tr('已逐项核对真实来源及本地结果','Đã kiểm tra nguồn thật và kết quả nội bộ') }}</el-checkbox></el-form><template #footer><el-button @click="validationOpen=false">{{ tr('取消','Hủy') }}</el-button><el-button :disabled="!validationChecked" type="primary" :loading="saving" @click="saveValidation">{{ tr('登记验收','Lưu nghiệm thu') }}</el-button></template></el-dialog>
 </div>
</template>
<script setup name="BusinessFeishuIntegration">
import { computed, onMounted, onBeforeUnmount, onActivated, onDeactivated, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import {getFeishuConnections,createFeishuConnection,getFeishuPeople,getFeishuMappings,createFeishuMapping,retireFeishuMapping,getFeishuRuns,syncFeishu,getFeishuCutoverStatus,validateFeishu,activateFeishu} from '@/api/business/feishu'
import { checkPermi } from '@/utils/permission'
import {getFeishuIssues,resolveFeishuIssue,getFeishuReaders,getFeishuReaderCandidates,saveFeishuReader} from '@/api/business/feishu'
import '@/assets/styles/business-product.scss'
import BatchMapping from './BatchMapping.vue'
import { getFeishuSyncOverview } from '@/api/business/feishu'
const {locale}=useI18n(),tr=(zh,vi)=>locale.value==='vi-VN'?vi:zh
const data=reactive({}),connectionId=ref(null),loading=ref(false),saving=ref(false),syncing=ref(false),mappings=ref([]),people=ref([]),runs=ref([]),tab=ref(checkPermi(['business:integration:feishu'])?'runs':'cutover'),cutover=ref(null),connectionOpen=ref(false),mappingOpen=ref(false),validationOpen=ref(false),validationChecked=ref(false),connectionForm=reactive({}),mappingForm=reactive({}),validationForm=reactive({})
const date=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),today=()=>date(new Date()),start=new Date();start.setDate(start.getDate()-6);const syncDates=ref([date(start),today()]),effectiveDate=ref(date(new Date(Date.now()+86400000)));let sequence=0
const connection=computed(()=>data.connections?.find(c=>c.connectionId===connectionId.value))
const canManage=computed(()=>checkPermi(['business:integration:feishu'])),canAudit=computed(()=>checkPermi(['business:attendance:cutover']) && connection.value?.canCutoverOwner === true)
const issues=ref([]),readers=ref([]),readerCandidates=ref([]),readerUserId=ref(null),running=computed(()=>!!connection.value?.runningRunId || runs.value[0]?.status === 'RUNNING')
const batchMapping=ref(null),overview=ref({}),coverageOpen=ref(false)
const activeCoverage=computed(()=>(overview.value.people||[]).filter(m=>String(m.effectiveFrom).slice(0,10)<=overview.value.sourceToday&&(!m.effectiveTo||String(m.effectiveTo).slice(0,10)>=overview.value.sourceToday)))
const issueFilter=ref('OPEN'),issueSearch=ref(''),selectedIssue=ref(null),issueDetailOpen=ref(false),issuesLoaded=ref(false),loadFailed=ref(false)
const openIssues=computed(()=>issues.value.filter(i=>i.status==='OPEN'))
const filteredIssues=computed(()=>issues.value.filter(i=>(issueFilter.value==='ALL'||i.status===issueFilter.value)&&(!issueSearch.value.trim()||[issueText(i.issueCode),i.issueCode,i.issueId,i.runId,i.resolution].some(v=>String(v??'').toLowerCase().includes(issueSearch.value.trim().toLowerCase())))))
const formatTime=value=>value?String(value).replace('T',' ').replace(/\.\d+$/,''):'—'
const statusType=value=>({COMPLETE:'success',SUCCESS:'success',RESOLVED:'success',FAILED:'danger',PARTIAL:'warning',OPEN:'warning',RUNNING:'primary'}[value]||'info')
function issueCategory(code){return code==='SOURCE_REVISION_REQUIRES_REVIEW'?tr('来源更正','Nguồn điều chỉnh'):code==='UNKNOWN_SOURCE_STATUS'?tr('规则待核实','Cần kiểm tra quy tắc'):tr('同步异常','Lỗi đồng bộ')}
function issueAdvice(code){
 if(code==='SOURCE_REVISION_REQUIRES_REVIEW')return tr('同步记录与上一版本存在差异，请由有权限的人员核对考勤明细及相关业务，再登记处理结果。','Bản ghi đồng bộ khác phiên bản trước. Người có quyền cần kiểm tra chấm công và nghiệp vụ liên quan rồi ghi kết quả.')
 if(['FEISHU_SCOPE_REJECTED','FEISHU_SCOPE_MISMATCH'].includes(code))return tr('核对员工绑定及飞书应用的数据授权范围，配置生效后重新同步。','Kiểm tra liên kết nhân sự và phạm vi dữ liệu Feishu; đồng bộ lại sau khi cấu hình có hiệu lực.')
 if(code==='FEISHU_TENANT_MISMATCH')return tr('请管理员核对服务端应用凭据与连接所属企业。','Nhờ quản trị viên kiểm tra thông tin xác thực máy chủ và doanh nghiệp của kết nối.')
 if(code==='FEISHU_HTTP_400')return tr('飞书未接受本次请求，请检查接口权限与请求参数；不能仅凭此错误判断具体原因。','Feishu không chấp nhận yêu cầu. Kiểm tra quyền API và tham số; mã này chưa xác định nguyên nhân cụ thể.')
 if(code==='FEISHU_HTTP_429')return tr('调用频率受限，请稍后重试；持续发生时请管理员调整同步频率。','Đã vượt giới hạn gọi. Thử lại sau; nhờ quản trị viên điều chỉnh tần suất nếu tiếp diễn.')
 if(['FEISHU_HTTP_401','FEISHU_HTTP_403'].includes(code))return tr('请管理员检查应用授权、凭据和可访问的数据范围。','Nhờ quản trị viên kiểm tra ủy quyền, xác thực và phạm vi dữ liệu.')
 if(code==='UNKNOWN_SOURCE_STATUS')return tr('请核对飞书班次和考勤状态，交由管理员确认当前规则是否受支持。','Kiểm tra ca và trạng thái Feishu; nhờ quản trị viên xác nhận quy tắc được hỗ trợ.')
 if(code==='FEISHU_SOURCE_CHANGED_DURING_READ')return tr('读取期间飞书数据发生变化，请重新同步相同日期范围。','Dữ liệu Feishu thay đổi trong khi đọc; đồng bộ lại cùng khoảng ngày.')
 if(code==='FEISHU_NETWORK_ERROR'||/^FEISHU_HTTP_5/.test(code||''))return tr('请检查连接或稍后重试；若仍失败，将详情中的技术代码提供给管理员。','Kiểm tra kết nối hoặc thử lại sau; nếu vẫn lỗi, gửi mã kỹ thuật cho quản trị viên.')
 return tr('查看技术代码及对应同步批次，核实原因后重新同步或登记处理。','Xem mã kỹ thuật và lần đồng bộ, xác minh nguyên nhân rồi đồng bộ lại hoặc ghi kết quả.')
}
let timer=null,polling=false,nextRefreshAt=0
const cases=computed(()=>({NORMAL:tr('正常出勤','Đi làm bình thường'),LEAVE:tr('已生效请假','Nghỉ phép có hiệu lực'),CORRECTION:tr('更正或撤销','Điều chỉnh hoặc thu hồi'),CROSS_DAY:tr('跨日记录','Qua ngày'),UNMAPPED:tr('未映射异常','Chưa ánh xạ'),RECOVERY:tr('故障后恢复','Phục hồi sau lỗi')}))
const validationLabels=computed(()=>({expectedResult:tr('预期结果','Kết quả mong đợi'),sourceEvidence:tr('飞书来源证据','Bằng chứng Feishu'),localResult:tr('本地实际结果','Kết quả nội bộ'),reason:tr('验收说明','Ghi chú nghiệm thu')}))
const status=s=>({PARALLEL:tr('并行核对','Đối chiếu'),ACTIVE:tr('飞书已生效','Feishu có hiệu lực'),COMPLETE:tr('完整成功','Thành công đầy đủ'),SUCCESS:tr('成功','Thành công'),PARTIAL:tr('部分成功','Một phần'),FAILED:tr('失败','Thất bại'),RUNNING:tr('同步中','Đang đồng bộ'),UNKNOWN:tr('未知','Chưa rõ'),CONFIRMED:tr('已确认映射','Ánh xạ đã xác nhận'),RETIRED:tr('已设截止日','Đã đặt ngày kết thúc'),OPEN:tr('待处理','Cần xử lý'),RESOLVED:tr('已处理','Đã xử lý')}[s]||s||'—')
const personName=id=>people.value.find(p=>p.userId===id)?.userName||String(id)
async function load(){loading.value=true;try{Object.assign(data,(await getFeishuConnections()).data||{});if(!data.connections?.some(c=>c.connectionId===connectionId.value))connectionId.value=data.connections?.[0]?.connectionId;await loadConnection();startPolling()}finally{loading.value=false}}
async function loadConnection(){const n=++sequence;cutover.value=null;overview.value={};coverageOpen.value=false;issuesLoaded.value=false;loadFailed.value=false;issueDetailOpen.value=false;selectedIssue.value=null;mappings.value=[];people.value=[];runs.value=[];issues.value=[];readers.value=[];readerCandidates.value=[];readerUserId.value=null;if(!connectionId.value)return;const id=connectionId.value,jobs={runs:getFeishuRuns(id),issues:getFeishuIssues(id)};if(canManage.value){jobs.mappings=getFeishuMappings(id);jobs.people=getFeishuPeople(id);jobs.overview=getFeishuSyncOverview(id)}if(canAudit.value){jobs.readers=getFeishuReaders(id);jobs.candidates=getFeishuReaderCandidates(id)}const keys=Object.keys(jobs),values=await Promise.allSettled(Object.values(jobs));if(n!==sequence)return;loadFailed.value=values.some(r=>r.status==='rejected');issuesLoaded.value=values[keys.indexOf('issues')]?.status==='fulfilled';const refs={runs,issues,mappings,people,readers,candidates:readerCandidates};values.forEach((r,i)=>{if(r.status==='fulfilled'){if(keys[i]==='overview')overview.value=r.value.data||{};else refs[keys[i]].value=Array.isArray(r.value.data)?r.value.data:[]}});if(!canManage.value&&tab.value==='mappings')tab.value='runs';if(!canAudit.value&&['cutover','readers'].includes(tab.value))tab.value='runs';if(canAudit.value&&tab.value==='cutover')await loadCutover()}
function openConnection(){Object.assign(connectionForm,{companyDeptId:null,tenantKey:'',timezone:'Asia/Shanghai'});connectionOpen.value=true}
function openMapping(){Object.assign(mappingForm,{userId:null,externalUserId:'',effectiveFrom:today(),effectiveTo:null});mappingOpen.value=true}
async function saveConnection(){if(!connectionForm.companyDeptId||!connectionForm.tenantKey?.trim())return;saving.value=true;try{await createFeishuConnection(connectionForm);connectionOpen.value=false;await load()}finally{saving.value=false}}
async function saveMapping(){if(!mappingForm.userId||!mappingForm.externalUserId?.trim()||!mappingForm.effectiveFrom)return;saving.value=true;try{await createFeishuMapping(connectionId.value,mappingForm);mappingOpen.value=false;await loadConnection()}finally{saving.value=false}}
async function reason(){return(await ElMessageBox.prompt(tr('请填写操作依据','Nhập căn cứ thao tác'),tr('确认','Xác nhận'),{inputValidator:v=>!!v?.trim()||tr('必须填写原因','Cần nhập lý do')})).value.trim()}
async function retire(row){try{const answer=await ElMessageBox.prompt(tr('截止日仍属于旧映射；必须不早于已有历史记录。填写 yyyy-MM-dd。','Ngày kết thúc vẫn thuộc ánh xạ cũ và không được trước dữ liệu lịch sử. Nhập yyyy-MM-dd.'),tr('映射截止日期','Ngày kết thúc ánh xạ'),{inputValue:row.effectiveTo||today(),inputValidator:v=>/^\d{4}-\d{2}-\d{2}$/.test(v)||tr('日期格式不正确','Sai định dạng ngày')});await retireFeishuMapping(row.mappingId,{effectiveTo:answer.value,reason:await reason()});await load()}catch(e){if(!['cancel','close'].includes(e))throw e}}
async function retryRun(row){syncDates.value=[row.windowStart,row.windowEnd];await runSync()}
async function runSync(){if(!syncDates.value?.[0]||!syncDates.value?.[1])return;const days=(new Date(syncDates.value[1]+'T00:00:00Z')-new Date(syncDates.value[0]+'T00:00:00Z'))/86400000;if(days<0||days>6)return ElMessage.warning(tr('每次补拉最多7天','Tối đa 7 ngày mỗi lần'));syncing.value=true;try{const result=await syncFeishu(connectionId.value,{windowStart:syncDates.value[0],windowEnd:syncDates.value[1]});connection.value.runningRunId=result.data.runId;await load();ElMessage.success(tr('已启动后台补拉，请查看批次进度','Đã bắt đầu đồng bộ nền; xem tiến độ lần chạy'))}finally{syncing.value=false}}
async function loadCutover(){if(canAudit.value&&connectionId.value&&effectiveDate.value)cutover.value=(await getFeishuCutoverStatus(connectionId.value,{effectiveDate:effectiveDate.value})).data}
function openValidation(){Object.assign(validationForm,{caseType:'NORMAL',runId:null,observationId:null,issueId:null,expectedResult:'',sourceEvidence:'',localResult:'',reason:'',passed:true});validationChecked.value=false;validationOpen.value=true}
async function saveValidation(){if(!validationChecked.value||!validationForm.runId||!(['UNMAPPED','RECOVERY'].includes(validationForm.caseType)?validationForm.issueId:validationForm.observationId)||['expectedResult','sourceEvidence','localResult','reason'].some(k=>!validationForm[k]?.trim()))return ElMessage.warning(tr('请完整填写验收资料','Điền đủ thông tin nghiệm thu'));saving.value=true;try{await validateFeishu(connectionId.value,{...validationForm,observationId:['UNMAPPED','RECOVERY'].includes(validationForm.caseType)?null:validationForm.observationId,issueId:['UNMAPPED','RECOVERY'].includes(validationForm.caseType)?validationForm.issueId:null});validationOpen.value=false;await loadCutover()}finally{saving.value=false}}
async function activate(){if(!cutover.value?.canActivate)return;try{const note=await reason();saving.value=true;await activateFeishu(connectionId.value,{effectiveDate:effectiveDate.value,version:cutover.value.version??connection.value.version,reason:note});await load();await loadCutover()}catch(e){if(!['cancel','close'].includes(e))await loadCutover()}finally{saving.value=false}}
function issueText(code){const labels={FEISHU_SCOPE_REJECTED:tr('员工授权范围不完整','Phạm vi ủy quyền nhân sự chưa đủ'),FEISHU_SCOPE_MISMATCH:tr('人员或日期超出请求范围','Nhân sự hoặc ngày ngoài phạm vi'),FEISHU_TENANT_MISMATCH:tr('凭据对应企业不匹配','Doanh nghiệp xác thực không khớp'),FEISHU_SOURCE_CHANGED_DURING_READ:tr('复查时来源变化，请补拉','Nguồn thay đổi khi kiểm tra; cần đồng bộ lại'),SOURCE_REVISION_REQUIRES_REVIEW:tr('来源记录有更新，需核对','Bản ghi nguồn cập nhật, cần đối chiếu'),UNKNOWN_SOURCE_STATUS:tr('未知状态或未支持的班次规则','Trạng thái hoặc quy tắc ca chưa hỗ trợ'),FEISHU_NETWORK_ERROR:tr('网络连接失败','Kết nối mạng thất bại')};const http={400:tr('飞书请求未通过','Yêu cầu Feishu không được chấp nhận'),401:tr('飞书身份验证失败','Xác thực Feishu thất bại'),403:tr('飞书访问被拒绝','Feishu từ chối truy cập'),429:tr('飞书调用频率受限','Vượt giới hạn gọi Feishu')};return code?labels[code]||http[code.replace('FEISHU_HTTP_','')]||(/^FEISHU_HTTP_5/.test(code)?tr('飞书服务暂时异常','Dịch vụ Feishu tạm lỗi'):tr('同步异常，需查看详情','Lỗi đồng bộ, cần xem chi tiết')):'—'}
function blockerText(text){if(locale.value!=='vi-VN')return text;const items={'服务端凭据未配置或企业标识不匹配':'Chưa cấu hình xác thực hoặc mã doanh nghiệp không khớp','来源已切换，不能重复启用或自动恢复本地申请':'Nguồn đã chuyển; không thể bật lại hoặc tự mở hồ sơ nội bộ','同步仍在运行':'Đồng bộ đang chạy','生效日至少为来源时区的明天':'Ngày hiệu lực phải từ ngày mai theo múi giờ nguồn','缺少最近 48 小时完整同步':'Chưa đồng bộ đầy đủ trong 48 giờ','当前人员映射版本尚无完整同步':'Chưa đồng bộ đầy đủ phiên bản ánh xạ hiện tại','完整同步窗口尚未覆盖最近业务日期':'Đồng bộ chưa bao phủ ngày nghiệp vụ gần nhất'};if(items[text])return items[text];const n=text.match(/\d+/)?.[0];if(text.includes('在职人员缺少映射'))return n+' nhân sự chưa ánh xạ vào ngày hiệu lực';if(text.includes('待审批/待撤销'))return n+' đơn nội bộ chờ duyệt hoặc thu hồi';if(text.includes('跨越生效日'))return n+' đơn đã duyệt kéo qua ngày hiệu lực, cần xử lý trước';if(text.includes('同步或来源差异'))return n+' vấn đề đồng bộ hoặc nguồn cần xử lý';if(text.includes('真实企业验收'))return 'Mới đạt '+n+'/6 tình huống nghiệm thu thực tế';return text}
async function resolve(row){try{await resolveFeishuIssue(connectionId.value,row.issueId,{resolution:(await ElMessageBox.prompt(tr('请填写核对结果及处理依据。登记后关闭此待办，不会修改飞书考勤、项目投入或成本。','Nhập kết quả xác minh và căn cứ xử lý. Việc ghi nhận đóng vấn đề, không sửa chấm công Feishu, công việc hoặc chi phí.'),tr('登记处理结果','Ghi nhận kết quả xử lý'),{inputType:'textarea',inputValidator:v=>!!v?.trim()||tr('请填写处理依据','Nhập căn cứ xử lý'),confirmButtonText:tr('保存处理结果','Lưu kết quả'),cancelButtonText:tr('取消','Hủy')})).value.trim()});await loadConnection()}catch(e){if(!['cancel','close'].includes(e))throw e}}
async function authorizeReader(){if(!readerUserId.value)return;try{await saveFeishuReader(connectionId.value,{userId:readerUserId.value,enabled:true,reason:await reason()});await loadConnection()}catch(e){if(!['cancel','close'].includes(e))throw e}}
async function revokeReader(row){try{await saveFeishuReader(connectionId.value,{userId:row.userId,enabled:false,reason:await reason()});await loadConnection()}catch(e){if(!['cancel','close'].includes(e))throw e}}
function startPolling(){if(timer)return;timer=setInterval(async()=>{if((!running.value&&Date.now()<nextRefreshAt)||polling||loading.value||!connectionId.value)return;nextRefreshAt=Date.now()+60000;polling=true;try{const id=connectionId.value,values=await Promise.all([getFeishuRuns(id),getFeishuConnections(),getFeishuIssues(id)]);if(id!==connectionId.value)return;runs.value=values[0].data||[];Object.assign(data,values[1].data||{});issues.value=values[2].data||[];if(canManage.value&&!running.value){const coverage=await getFeishuSyncOverview(id);if(id===connectionId.value)overview.value=coverage.data||{}}if(!running.value&&tab.value==='cutover')await loadCutover()}catch{stopPolling()}finally{polling=false}},5000)}
function stopPolling(){if(timer)clearInterval(timer);timer=null}
onMounted(load);onActivated(startPolling);onDeactivated(stopPolling);onBeforeUnmount(stopPolling)
</script>

<style scoped lang="scss">
.feishu-integration { max-width: none; }
.sync-policy { display:flex; align-items:center; flex-wrap:wrap; gap:16px; padding:16px; background:#f7fafb; border-radius:8px; margin:12px 0; }
.technical-code {display:block; color:#728494; overflow-wrap:anywhere;}
.integration-summary small { display: block; color: #637788; line-height: 1.7; margin-top: 8px; }
.integration-summary .attention-card { background: #fffaf0; border-color: #f1dfba; }
.issue-heading { display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-top: 12px; }
.issue-search { width: 320px; max-width: 100%; }
.issue-toolbar { justify-content: space-between; }
.issue-title { display: flex; align-items: center; gap: 10px; padding-top: 8px; }
.issue-hint { font-size: 13px; margin: 8px 0 !important; }
.issue-details { display: grid; grid-template-columns: 150px 1fr; gap: 16px; margin-top: 24px; }
.issue-details dt { color: #728494; }
.issue-details dd { margin: 0; white-space: pre-wrap; overflow-wrap: anywhere; }
@media(max-width:760px) { .issue-heading { align-items: flex-start; flex-direction: column; } .issue-details { grid-template-columns: 1fr; gap: 10px; } .issue-title { align-items: flex-start; } }
</style>
