<template>
  <div class="business-product" v-loading="loading">
    <header class="product-head"><div><h1>{{ t('title') }}</h1><p>{{ t('intro') }}</p></div><el-button icon="Refresh" @click="load">{{ t('refresh') }}</el-button></header>
    <div class="product-toolbar"><el-select v-model="projectId" filterable :placeholder="t('project')" @change="switchProject"><el-option v-for="p in data.projects || []" :key="p.projectId" :label="p.projectName" :value="p.projectId" /></el-select><el-button v-if="data.canManageRules" v-hasPermi="['business:incentive:rule']" @click="openRule">{{ t('newRule') }}</el-button><el-button v-if="data.canApply" v-hasPermi="['business:incentive:apply']" type="primary" :disabled="!activeRules.length" @click="openAward">{{ t('newAward') }}</el-button></div>
    <el-empty v-if="!data.project && !loading" :description="t('chooseProject')" />
    <template v-if="data.project">
      <BusinessSettlementPanel :project="data.project" :refresh-key="refreshKey" @closed="load" />
      <el-alert :title="t('boundary')" type="info" :closable="false" show-icon /><el-alert v-if="sameApprover" :title="t('selfApproval')" type="warning" :closable="false" show-icon />
      <section class="product-card"><h2>{{ t('awards') }}</h2><p>{{ t('awardHint') }}</p>
        <el-table :data="data.awards || []" :empty-text="t('empty')">
          <el-table-column :label="t('rule')" min-width="165"><template #default="{row}">{{ row.ruleName || `#${row.ruleId}` }}<div class="muted">{{ row.awardNo || `#${row.awardId}` }}</div></template></el-table-column>
          <el-table-column :label="t('amount')" min-width="135"><template #default="{row}">{{ amount(row.amount ?? row.approvedAmount) }} {{ row.currency }}</template></el-table-column>
          <el-table-column prop="bizDate" :label="t('date')" width="115" />
          <el-table-column :label="t('approval')" min-width="115"><template #default="{row}"><el-tag :type="tone(row.status)">{{ state(row.status) }}</el-tag></template></el-table-column>
          <el-table-column :label="t('cost')" min-width="120"><template #default="{row}">{{ costState(row.costStatus) }}</template></el-table-column>
          <el-table-column :label="t('payment')" min-width="125"><template #default="{row}">{{ state(row.paymentStatus || 'NOT_RECORDED') }}</template></el-table-column>
          <el-table-column :label="t('actions')" min-width="275" fixed="right"><template #default="{row}"><div class="row-actions">
            <el-button link @click="history=row">{{ t('details') }}</el-button>
            <el-button v-if="row.canSubmit" v-hasPermi="['business:incentive:apply']" link type="primary" :disabled="acting" @click="act(row,'submit')">{{ t('submit') }}</el-button>
            <el-button v-if="row.canReview" v-hasPermi="['business:incentive:approve']" link type="success" :disabled="acting" @click="act(row,'review','APPROVED')">{{ t('approve') }}</el-button>
            <el-button v-if="row.canReview" v-hasPermi="['business:incentive:approve']" link type="warning" :disabled="acting" @click="act(row,'review','RETURNED')">{{ t('return') }}</el-button>
            <el-button v-if="row.canCancel" v-hasPermi="['business:incentive:apply','business:incentive:approve']" link type="danger" :disabled="acting" @click="act(row,'cancel')">{{ t('cancelAward') }}</el-button>
            <el-button v-if="row.canResubmitCost" v-hasPermi="['business:incentive:approve']" link type="primary" :disabled="acting" @click="act(row,'resubmit-cost')">{{ t('resubmitCost') }}</el-button>
            <el-button v-if="row.accountingFactId" v-hasPermi="['business:accounting:list']" link @click="openAccounting(row)">{{ t('openCost') }}</el-button>
          </div></template></el-table-column>
        </el-table>
      </section>
      <section class="product-card"><h2>{{ t('rules') }}</h2><p>{{ t('ruleHint') }}</p><el-table :data="data.rules || []" :empty-text="t('empty')"><el-table-column prop="ruleName" :label="t('rule')" min-width="180"/><el-table-column :label="t('amount')"><template #default="{row}">{{ amount(row.amount) }} {{ row.currency }}</template></el-table-column><el-table-column :label="t('score')"><template #default="{row}">{{ row.minScore ?? t('noScore') }}</template></el-table-column><el-table-column prop="reason" :label="t('reason')" min-width="180"/><el-table-column prop="ruleVersion" :label="t('version')"/><el-table-column :label="t('approval')"><template #default="{row}">{{ state(row.status) }}</template></el-table-column><el-table-column :label="t('actions')"><template #default="{row}"><el-button v-if="data.canRetireRules && row.status==='ACTIVE'" v-hasPermi="['business:incentive:rule']" link type="danger" @click="retireRule(row)">{{ t('retire') }}</el-button></template></el-table-column></el-table></section>
      <section v-if="data.legacyBonuses?.length" class="product-card"><h2>{{ t('legacy') }}</h2><p>{{ t('legacyHint') }}</p><el-table :data="data.legacyBonuses"><el-table-column prop="periodEnd" :label="t('date')"/><el-table-column :label="t('amount')"><template #default="{row}">{{ amount(row.bonusAmount) }} {{ row.currency || 'CNY' }}</template></el-table-column><el-table-column :label="t('approval')"><template #default="{row}">{{ row.status==='CONFIRMED'?t('indicatorConfirmed'):state(row.status) }}</template></el-table-column><el-table-column :label="t('cost')"><template #default="{row}">{{ costState(row.costStatus) }}</template></el-table-column><el-table-column :label="t('payment')"><template #default>{{ t('notRecorded') }}</template></el-table-column></el-table></section>
    </template>
    <el-dialog v-model="ruleOpen" :title="t('newRule')" width="min(640px,95vw)" append-to-body>
      <el-form label-position="top" :model="ruleForm"><el-form-item :label="t('rule')" required><el-input v-model="ruleForm.ruleName" maxlength="100"/></el-form-item><el-form-item :label="t('amount')" required><el-input-number v-model="ruleForm.amount" :min="0.01" :precision="2"/><span> {{ ruleForm.currency }}</span></el-form-item><el-form-item :label="t('score')"><el-input-number v-model="ruleForm.minScore" :min="0" :max="120" :precision="2"/><p>{{ t('scoreHint') }}</p></el-form-item><el-form-item :label="t('reason')" required><el-input v-model="ruleForm.reason" type="textarea" maxlength="500"/></el-form-item></el-form>
      <template #footer><el-button @click="ruleOpen=false">{{ t('cancel') }}</el-button><el-button type="primary" :loading="saving" @click="saveRule">{{ t('publish') }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="awardOpen" :title="t('newAward')" width="min(640px,95vw)" append-to-body>
      <el-form label-position="top" :model="awardForm"><el-form-item :label="t('rule')" required><el-select v-model="awardForm.ruleId" style="width:100%" @change="invalidateEstimate"><el-option v-for="r in activeRules" :key="r.ruleId" :label="`${r.ruleName} · ${amount(r.amount)} ${r.currency}`" :value="r.ruleId"/></el-select></el-form-item><el-form-item :label="t('kpiEvidence')"><el-select v-model="awardForm.settlementId" clearable style="width:100%" @change="invalidateEstimate"><el-option v-for="k in data.confirmedKpis || []" :key="k.settlementId" :label="`${k.periodEnd || k.cycleEnd} · ${k.totalScore ?? '—'}`" :value="k.settlementId"/></el-select></el-form-item><el-form-item :label="t('date')" required><el-date-picker v-model="awardForm.bizDate" type="date" value-format="YYYY-MM-DD" :disabled-date="futureDate"/></el-form-item><el-form-item :label="t('reason')" required><el-input v-model="awardForm.reason" type="textarea" maxlength="500"/></el-form-item></el-form>
      <el-button :disabled="!awardForm.ruleId" :loading="estimating" @click="calculate">{{ t('estimate') }}</el-button><p v-if="estimate">{{ t('estimated') }} {{ amount(estimate.amount ?? estimate.estimatedAmount) }} {{ estimate.currency || data.project?.baseCurrency }} · {{ estimate.message || t('estimateHint') }}</p>
      <template #footer><el-button @click="awardOpen=false">{{ t('cancel') }}</el-button><el-button type="primary" :loading="saving" @click="saveAward">{{ t('saveDraft') }}</el-button></template>
    </el-dialog>
    <el-drawer :model-value="!!history" :title="t('details')" size="min(640px,95vw)" @close="history=null"><template v-if="history"><el-descriptions :column="1" border><el-descriptions-item :label="t('rule')">{{ history.ruleName }} · v{{ history.ruleVersion }}</el-descriptions-item><el-descriptions-item :label="t('amount')">{{ amount(history.amount) }} {{ history.currency }}</el-descriptions-item><el-descriptions-item :label="t('applicant')">{{ history.applicantUserName }}</el-descriptions-item><el-descriptions-item :label="t('approver')">{{ history.approvedUserName || '—' }}</el-descriptions-item><el-descriptions-item :label="t('approvedTime')">{{ history.approvedTime || '—' }}</el-descriptions-item><el-descriptions-item :label="t('scoreSnapshot')">{{ history.scoreSnapshot ?? '—' }}</el-descriptions-item><el-descriptions-item :label="t('reason')">{{ history.reason }}</el-descriptions-item><el-descriptions-item :label="t('allocation')">{{ t('notRecorded') }}</el-descriptions-item><el-descriptions-item :label="t('approval')">{{ state(history.status) }}</el-descriptions-item><el-descriptions-item :label="t('cost')">{{ costState(history.costStatus) }}</el-descriptions-item><el-descriptions-item :label="t('payment')">{{ t('notRecorded') }}</el-descriptions-item></el-descriptions><el-timeline style="margin-top:24px"><el-timeline-item v-for="(event,index) in history.events || []" :key="event.eventId || index" :timestamp="event.createTime || event.eventTime"><b>{{ event.operatorName || event.operatorUserName }}</b> · {{ state(event.toStatus || event.action) }}<p>{{ event.reason || event.comment }}</p></el-timeline-item></el-timeline></template></el-drawer>
  </div>
</template>

<script setup name="BusinessIncentive">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { getIncentiveWorkspace, createIncentiveRule, estimateIncentive, createIncentiveAward, actIncentiveAward, retireIncentiveRule } from '@/api/business/incentive'
import BusinessSettlementPanel from '@/components/BusinessSettlementPanel/index.vue'
import '@/assets/styles/business-product.scss'
import { useBusinessRefreshOnReactivated } from '@/utils/businessRefresh'

const route=useRoute(), router=useRouter(), projectId=ref(route.query.projectId ? Number(route.query.projectId) : null)
const data=reactive({}), loading=ref(false), saving=ref(false), estimating=ref(false), ruleOpen=ref(false), awardOpen=ref(false), history=ref(null), estimate=ref(null), refreshKey=ref(0)
const ruleForm=reactive({}), awardForm=reactive({}), acting=ref(false); let sequence=0, estimateSequence=0
const {t,te}=useI18n({useScope:'local',messages:{
  'zh-CN':{title:'奖金激励',version:'版本',retire:'停用规则',indicatorConfirmed:'指标已确认',pendingCost:'待确认',allocation:'个人分配',applicant:'申请人',approver:'核准人',approvedTime:'核准时间',scoreSnapshot:'指标得分快照',maxReason:'说明不得超过500字',selfApproval:'主负责人与归属老板相同时，不能自批奖励；须先明确不同的业务核准责任人。',intro:'管理奖励方案、申请与核准，按单据追踪成本确认。',refresh:'刷新',project:'选择项目',chooseProject:'请选择有权查看的项目',newRule:'发布奖金规则',newAward:'新建奖励申请',boundary:'奖励核准、成本入账、个人分配与支付分别记录。这里不会把奖金池标记为已发薪。',awards:'奖励申请与核准',awardHint:'申请人提交，由项目归属责任人核准；核准后生成待确认成本。',empty:'暂无记录',rule:'奖金规则',amount:'奖励金额',date:'业务日期',approval:'核准状态',cost:'成本状态',payment:'支付状态',actions:'操作',details:'详情与记录',submit:'提交核准',approve:'核准',return:'退回',cancelAward:'撤销',resubmitCost:'重新提交成本',openCost:'查看成本',rules:'奖金规则版本',ruleHint:'已发布规则保留原值。调整时发布新规则，既有申请继续引用原版本。',score:'最低综合得分',noScore:'不要求指标分数',reason:'依据与说明',legacy:'历史项目奖金池',legacyHint:'原方案按历史规则结清；没有个人分配和支付记录，不生成新的重复奖励。',notRecorded:'未记录',cancel:'取消',publish:'发布规则',scoreHint:'选填；填写后，奖励申请须引用已确认且达到门槛的独立项目指标。',kpiEvidence:'已确认项目指标（可选）',estimate:'测算奖励',estimated:'测算金额：',estimateHint:'测算不代表核准或入账',saveDraft:'保存草稿',required:'请完整填写必填资料',success:'操作成功',actionTitle:'确认奖励操作',actionReason:'请填写本次操作的依据或原因',states:{ACTIVE:'有效',RETIRED:'已停用',DRAFT:'草稿',SUBMITTED:'待核准',RETURNED:'已退回',APPROVED:'已核准',CONFIRMED:'已入账',CANCELED:'已撤销',CANCELLED:'已撤销',VOIDED:'已作废',REVERSED:'已冲正',NOT_CREATED:'未生成',PENDING:'待确认',NOT_RECORDED:'未记录',NONE:'未生成'}},
  'vi-VN':{title:'Khuyến khích và thưởng',version:'Phiên bản',retire:'Dừng quy tắc',indicatorConfirmed:'Chỉ tiêu đã xác nhận',pendingCost:'Chờ xác nhận',allocation:'Phân bổ cá nhân',applicant:'Người đề nghị',approver:'Người phê duyệt',approvedTime:'Thời gian phê duyệt',scoreSnapshot:'Điểm chỉ tiêu đã chốt',maxReason:'Lý do không vượt quá 500 ký tự',selfApproval:'Khi người phụ trách cũng là người phê duyệt, không được tự phê duyệt thưởng; cần xác định người chịu trách nhiệm khác.',intro:'Quản lý quy tắc, đề nghị và phê duyệt thưởng; theo dõi ghi nhận chi phí.',refresh:'Làm mới',project:'Chọn dự án',chooseProject:'Chọn dự án được phép xem',newRule:'Công bố quy tắc thưởng',newAward:'Tạo đề nghị thưởng',boundary:'Phê duyệt, ghi nhận chi phí, phân bổ cá nhân và thanh toán là các bước riêng biệt.',awards:'Đề nghị và phê duyệt',awardHint:'Người đề nghị gửi, người chịu trách nhiệm dự án phê duyệt rồi tạo chi phí chờ xác nhận.',empty:'Chưa có dữ liệu',rule:'Quy tắc thưởng',amount:'Số tiền thưởng',date:'Ngày nghiệp vụ',approval:'Phê duyệt',cost:'Chi phí',payment:'Thanh toán',actions:'Thao tác',details:'Chi tiết và lịch sử',submit:'Gửi phê duyệt',approve:'Phê duyệt',return:'Trả lại',cancelAward:'Hủy đề nghị',resubmitCost:'Gửi lại chi phí',openCost:'Xem chi phí',rules:'Phiên bản quy tắc',ruleHint:'Quy tắc đã công bố được giữ nguyên. Thay đổi bằng phiên bản mới.',score:'Điểm tổng hợp tối thiểu',noScore:'Không yêu cầu điểm',reason:'Căn cứ và lý do',legacy:'Quỹ thưởng dự án cũ',legacyHint:'Giữ cách quyết toán cũ; chưa ghi nhận phân bổ cá nhân hoặc thanh toán, không tạo thưởng trùng.',notRecorded:'Chưa ghi nhận',cancel:'Hủy',publish:'Công bố',scoreHint:'Tùy chọn; khi có ngưỡng, cần dẫn kết quả chỉ tiêu đã xác nhận đạt ngưỡng.',kpiEvidence:'Chỉ tiêu đã xác nhận (tùy chọn)',estimate:'Ước tính',estimated:'Số tiền ước tính: ',estimateHint:'Ước tính chưa phải phê duyệt hoặc hạch toán',saveDraft:'Lưu bản nháp',required:'Vui lòng điền thông tin bắt buộc',success:'Thành công',actionTitle:'Xác nhận thao tác thưởng',actionReason:'Nhập căn cứ hoặc lý do',states:{ACTIVE:'Có hiệu lực',RETIRED:'Đã dừng',DRAFT:'Bản nháp',SUBMITTED:'Chờ phê duyệt',RETURNED:'Đã trả lại',APPROVED:'Đã phê duyệt',CONFIRMED:'Đã ghi chi phí',CANCELED:'Đã hủy',CANCELLED:'Đã hủy',VOIDED:'Đã vô hiệu',REVERSED:'Đã đảo',NOT_CREATED:'Chưa tạo',PENDING:'Chờ xác nhận',NOT_RECORDED:'Chưa ghi nhận',NONE:'Chưa tạo'}}
}})
const amount=value=>value==null?'—':Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})
const state=value=>value&&te(`states.${value}`)?t(`states.${value}`):(value||'—')
const costState=value=>value==='DRAFT'?t('pendingCost'):state(value)
const sameApprover=computed(()=>data.project?.mainOwnerUserId && String(data.project.mainOwnerUserId)===String(data.project.sponsorOwnerUserId??data.project.initiatorUserId))
const tone=value=>({APPROVED:'success',CONFIRMED:'success',RETURNED:'warning',SUBMITTED:'warning',CANCELED:'info'}[value]||'info')
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'})
const futureDate=date=>{const v=new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,10),start=data.project?.actualStartDate||data.project?.planStartDate,end=data.project?.actualEndDate||today();return v>today()||v>end||(start&&v<start)}
const activeRules=computed(()=>(data.rules||[]).filter(r=>r.status==='ACTIVE'))
async function load(){const n=++sequence;loading.value=true;try{const res=await getIncentiveWorkspace({projectId:projectId.value||undefined});if(n!==sequence)return;Object.keys(data).forEach(k=>delete data[k]);Object.assign(data,res.data||{});projectId.value=data.project?.projectId||projectId.value;if(history.value)history.value=(data.awards||[]).find(a=>a.awardId===history.value.awardId)||null;refreshKey.value++}catch(error){if(n===sequence){Object.keys(data).forEach(k=>delete data[k]);history.value=null}throw error}finally{if(n===sequence)loading.value=false}}
async function switchProject(){history.value=null;invalidateEstimate();await router.replace({query:{...route.query,projectId:projectId.value}});await load()}
function openRule(){Object.assign(ruleForm,{projectId:projectId.value,ruleName:'',amount:null,currency:data.project?.baseCurrency||'CNY',minScore:null,reason:''});ruleOpen.value=true}
function openAward(){Object.assign(awardForm,{projectId:projectId.value,ruleId:null,settlementId:null,bizDate:data.project?.actualEndDate||today(),reason:'',requestKey:globalThis.crypto?.randomUUID?.()||`award-${Date.now()}-${Math.random().toString(36).slice(2)}`});estimate.value=null;awardOpen.value=true}
async function saveRule(){if(!ruleForm.ruleName?.trim()||!ruleForm.reason?.trim()||!(ruleForm.amount>0))return ElMessage.warning(t('required'));saving.value=true;try{await createIncentiveRule(ruleForm);ruleOpen.value=false;await load();ElMessage.success(t('success'))}finally{saving.value=false}}
function invalidateEstimate(){estimateSequence++;estimate.value=null;estimating.value=false}
async function calculate(){const n=++estimateSequence;estimating.value=true;try{const res=await estimateIncentive({projectId:projectId.value,ruleId:awardForm.ruleId,settlementId:awardForm.settlementId||null});if(n===estimateSequence)estimate.value=res.data}finally{if(n===estimateSequence)estimating.value=false}}
async function saveAward(){if(!awardForm.ruleId||!awardForm.bizDate||!awardForm.reason?.trim())return ElMessage.warning(t('required'));saving.value=true;try{await createIncentiveAward({...awardForm,settlementId:awardForm.settlementId||null});awardOpen.value=false;await load();ElMessage.success(t('success'))}finally{saving.value=false}}
const validReason=value=>!value?.trim()?t('required'):value.trim().length>500?t('maxReason'):true
async function act(row,action,decision){if(acting.value)return;acting.value=true;try{const label=decision==='APPROVED'?t('approve'):decision==='RETURNED'?t('return'):action==='cancel'?t('cancelAward'):action==='resubmit-cost'?t('resubmitCost'):t('submit');const{value}=await ElMessageBox.prompt(`${label} #${row.awardId} · ${amount(row.amount)} ${row.currency}。${decision==='APPROVED'?t('awardHint'):''} ${t('actionReason')}`,t('actionTitle'),{inputType:'textarea',inputValidator:validReason,type:'warning'});await actIncentiveAward(row.awardId,action,{version:row.version,reason:value.trim(),decision});await load();ElMessage.success(t('success'))}catch(error){if(!['cancel','close'].includes(error))await load()}finally{acting.value=false}}
async function retireRule(row){try{const {value}=await ElMessageBox.prompt(t('actionReason'),t('retire'),{inputValidator:validReason});await retireIncentiveRule(row.ruleId,{reason:value.trim()});await load()}catch(e){if(!['cancel','close'].includes(e))await load()}}
function openAccounting(row){router.push({path:'/finance/accounting',query:{projectId:projectId.value,factId:row.accountingFactId}})}
watch(()=>route.query.projectId,value=>{const id=Number(value)||null;if(id!==projectId.value){projectId.value=id;history.value=null;load()}})
useBusinessRefreshOnReactivated(load)
onMounted(load)
</script>
