<template>
  <div class="app-container">
    <el-form inline><el-form-item><el-input v-model="query.keyword" :placeholder="$tr(&quot;供应商编码或名称&quot;)" clearable/></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="load">{{ $tr("查询") }}</el-button></el-form-item></el-form>
    <el-button type="primary" plain icon="Plus" class="mb8" v-hasPermi="['jewelry:supplier:add']" @click="open()">{{ $tr("新增供应商") }}</el-button>
    <el-table :data="rows" v-loading="loading" border><el-table-column prop="supplierCode" :label="$tr(&quot;编码&quot;)" width="130"/><el-table-column prop="supplierName" :label="$tr(&quot;供应商名称&quot;)" min-width="180"/><el-table-column prop="contactName" :label="$tr(&quot;联系人&quot;)" width="110"/><el-table-column prop="contactPhone" :label="$tr(&quot;电话&quot;)" width="140"/><el-table-column prop="settlementType" :label="$tr(&quot;结算方式&quot;)" width="130"/><el-table-column prop="address" :label="$tr(&quot;地址&quot;)" min-width="180"/><el-table-column :label="$tr(&quot;状态&quot;)" width="80"><template #default="{row}">{{row.status==='0'?$tr("启用"):$tr("停用")}}</template></el-table-column><el-table-column :label="$tr(&quot;操作&quot;)" width="90"><template #default="{row}"><el-button link type="primary" icon="Edit" v-hasPermi="['jewelry:supplier:edit']" @click="open(row)">{{ $tr("编辑") }}</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="dialog" :title="form.supplierId?$tr(&quot;编辑供应商&quot;):$tr(&quot;新增供应商&quot;)" width="580px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item :label="$tr(&quot;供应商编码&quot;)" prop="supplierCode"><el-input v-model="form.supplierCode" :disabled="!!form.supplierId"/></el-form-item><el-form-item :label="$tr(&quot;供应商名称&quot;)" prop="supplierName"><el-input v-model="form.supplierName"/></el-form-item><el-form-item :label="$tr(&quot;联系人&quot;)"><el-input v-model="form.contactName"/></el-form-item><el-form-item :label="$tr(&quot;联系电话&quot;)"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item :label="$tr(&quot;结算方式&quot;)"><el-input v-model="form.settlementType"/></el-form-item><el-form-item :label="$tr(&quot;地址&quot;)"><el-input v-model="form.address"/></el-form-item><el-form-item :label="$tr(&quot;状态&quot;)"><el-radio-group v-model="form.status"><el-radio value="0">{{ $tr("启用") }}</el-radio><el-radio value="1">{{ $tr("停用") }}</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog=false">{{ $tr("取消") }}</el-button><el-button type="primary" @click="save">{{ $tr("确定") }}</el-button></template></el-dialog>
  </div>
</template>
<script setup name="JewelrySupplier">
import { translateText } from '@/locales/translate'

import {listJewelrySuppliers,saveJewelrySupplier} from '@/api/jewelry/erp'
const {proxy}=getCurrentInstance(),rows=ref([]),total=ref(0),loading=ref(false),dialog=ref(false),formRef=ref();const query=reactive({pageNum:1,pageSize:10,keyword:''});const blank=()=>({supplierId:null,supplierCode:'',supplierName:'',contactName:'',contactPhone:'',settlementType:'',address:'',status:'0'});const form=reactive(blank());const rules={supplierCode:[{required:true,message:translateText("请输入编码")}],supplierName:[{required:true,message:translateText("请输入名称")}]}
async function load(){loading.value=true;try{const r=await listJewelrySuppliers(query);rows.value=r.rows||[];total.value=r.total||0}finally{loading.value=false}}function open(row){Object.assign(form,blank(),row||{});dialog.value=true}async function save(){await formRef.value.validate();await saveJewelrySupplier(form);proxy.$modal.msgSuccess(translateText("保存成功"));dialog.value=false;load()}load()
</script>
