<template>
  <div class="app-container">
    <el-form inline><el-form-item><el-input v-model="query.keyword" placeholder="供应商编码或名称" clearable/></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="load">查询</el-button></el-form-item></el-form>
    <el-button type="primary" plain icon="Plus" class="mb8" v-hasPermi="['jewelry:supplier:add']" @click="open()">新增供应商</el-button>
    <el-table :data="rows" v-loading="loading" border><el-table-column prop="supplierCode" label="编码" width="130"/><el-table-column prop="supplierName" label="供应商名称" min-width="180"/><el-table-column prop="contactName" label="联系人" width="110"/><el-table-column prop="contactPhone" label="电话" width="140"/><el-table-column prop="settlementType" label="结算方式" width="130"/><el-table-column prop="address" label="地址" min-width="180"/><el-table-column label="状态" width="80"><template #default="{row}">{{row.status==='0'?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" icon="Edit" v-hasPermi="['jewelry:supplier:edit']" @click="open(row)">编辑</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="dialog" :title="form.supplierId?'编辑供应商':'新增供应商'" width="580px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-form-item label="供应商编码" prop="supplierCode"><el-input v-model="form.supplierCode" :disabled="!!form.supplierId"/></el-form-item><el-form-item label="供应商名称" prop="supplierName"><el-input v-model="form.supplierName"/></el-form-item><el-form-item label="联系人"><el-input v-model="form.contactName"/></el-form-item><el-form-item label="联系电话"><el-input v-model="form.contactPhone"/></el-form-item><el-form-item label="结算方式"><el-input v-model="form.settlementType"/></el-form-item><el-form-item label="地址"><el-input v-model="form.address"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="0">启用</el-radio><el-radio value="1">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup name="JewelrySupplier">
import {listJewelrySuppliers,saveJewelrySupplier} from '@/api/jewelry/erp'
const {proxy}=getCurrentInstance(),rows=ref([]),total=ref(0),loading=ref(false),dialog=ref(false),formRef=ref();const query=reactive({pageNum:1,pageSize:10,keyword:''});const blank=()=>({supplierId:null,supplierCode:'',supplierName:'',contactName:'',contactPhone:'',settlementType:'',address:'',status:'0'});const form=reactive(blank());const rules={supplierCode:[{required:true,message:'请输入编码'}],supplierName:[{required:true,message:'请输入名称'}]}
async function load(){loading.value=true;try{const r=await listJewelrySuppliers(query);rows.value=r.rows||[];total.value=r.total||0}finally{loading.value=false}}function open(row){Object.assign(form,blank(),row||{});dialog.value=true}async function save(){await formRef.value.validate();await saveJewelrySupplier(form);proxy.$modal.msgSuccess('保存成功');dialog.value=false;load()}load()
</script>
