<template>
  <div class="app-container">
    <el-form inline><el-form-item><el-input v-model="query.keyword" placeholder="SKU或商品名称" clearable @keyup.enter="load"/></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="load">查询</el-button></el-form-item></el-form>
    <el-button type="primary" plain icon="Plus" class="mb8" v-hasPermi="['jewelry:product:add']" @click="open()">新增商品</el-button>
    <el-table v-loading="loading" :data="rows" border><el-table-column prop="sku" label="SKU" width="150"/><el-table-column prop="productName" label="商品名称" min-width="180"/><el-table-column prop="category" label="分类" width="110"/><el-table-column prop="specification" label="规格" min-width="140"/><el-table-column prop="unit" label="单位" width="70"/><el-table-column prop="onHandQty" label="库存" width="90" align="right"/><el-table-column v-if="canViewFinance" prop="avgCost" label="平均成本" width="110" align="right"/><el-table-column prop="warningQty" label="预警值" width="90" align="right"/><el-table-column label="状态" width="80"><template #default="{row}">{{row.status==='0'?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" icon="Edit" v-hasPermi="['jewelry:product:edit']" @click="open(row)">编辑</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="dialog" :title="form.productId?'编辑商品':'新增商品'" width="650px"><el-form ref="formRef" :model="form" :rules="rules" label-width="100px"><el-row :gutter="14"><el-col :span="12"><el-form-item label="SKU" prop="sku"><el-input v-model="form.sku" :disabled="!!form.productId"/></el-form-item></el-col><el-col :span="12"><el-form-item label="商品名称" prop="productName"><el-input v-model="form.productName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="分类"><el-input v-model="form.category"/></el-form-item></el-col><el-col :span="12"><el-form-item label="规格"><el-input v-model="form.specification"/></el-form-item></el-col><el-col :span="8"><el-form-item label="单位"><el-input v-model="form.unit"/></el-form-item></el-col><el-col :span="8"><el-form-item label="预警值"><el-input-number v-model="form.warningQty" :min="0" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="0"/><el-option label="停用" value="1"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="包装费"><el-input-number v-model="form.defaultPackFee" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="物流费"><el-input-number v-model="form.defaultShipFee" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="鉴定费"><el-input-number v-model="form.defaultCertFee" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">确定</el-button></template></el-dialog>
  </div>
</template>
<script setup name="JewelryProduct">
import { listJewelryProducts, saveJewelryProduct } from '@/api/jewelry/erp'
import useUserStore from '@/store/modules/user'
const userStore=useUserStore()
const canViewFinance=computed(()=>userStore.roles.some(role=>['admin','jewelry_admin','jewelry_reviewer'].includes(role)))
const {proxy}=getCurrentInstance(),loading=ref(false),rows=ref([]),total=ref(0),dialog=ref(false),formRef=ref();const query=reactive({pageNum:1,pageSize:10,keyword:''})
const blank=()=>({productId:null,sku:'',productName:'',category:'',specification:'',unit:'件',warningQty:5,status:'0',defaultPackFee:0,defaultShipFee:0,defaultCertFee:0});const form=reactive(blank());const rules={sku:[{required:true,message:'请输入SKU'}],productName:[{required:true,message:'请输入商品名称'}]}
async function load(){loading.value=true;try{const r=await listJewelryProducts(query);rows.value=r.rows||[];total.value=r.total||0}finally{loading.value=false}}function open(row){Object.assign(form,blank(),row||{});dialog.value=true}async function save(){await formRef.value.validate();await saveJewelryProduct(form);proxy.$modal.msgSuccess('保存成功');dialog.value=false;load()}load()
</script>
