<template>
  <section class="business-product work-panel" v-loading="loading">
    <div class="product-head"><div><h2>{{ t('title') }}</h2><p>{{ t('intro') }}</p></div><el-button icon="Refresh" @click="load">{{ t('refresh') }}</el-button></div>
    <el-alert v-if="legacy" :title="t('legacy')" type="info" :closable="false" show-icon />
    <template v-else-if="workspace.project">
      <div class="product-toolbar"><el-date-picker v-model="dates" type="daterange" value-format="YYYY-MM-DD" @change="load"/><el-button v-if="workspace.canReport" v-hasPermi="['business:work:report']" type="primary" @click="openEntry()">{{ t('record') }}</el-button><el-button v-if="workspace.canManage" v-hasPermi="['business:resource:edit']" @click="openAssignment">{{ t('arrange') }}</el-button><el-button v-if="Number(user.id)===1" v-hasPermi="['business:resource:config']" @click="openConfig('calendar')">{{ t('calendar') }}</el-button><el-button v-if="Number(user.id)===1" v-hasPermi="['business:resource:config']" @click="openConfig('unit')">{{ t('unitPolicy') }}</el-button></div>
      <div class="product-summary"><div><span>{{ t('recorded') }}</span><b>{{ confirmedDays }} {{ t('day') }}</b></div><div><span>{{ t('pending') }}</span><b>{{ pendingEntries }}</b></div><div><span>{{ t('notRecorded') }}</span><b>—</b></div></div>
      <el-alert v-if="workspace.pendingCostCount>0" :title="`${t('pendingCost')} · ${workspace.pendingCostCount}`" type="warning" :closable="false"/><el-alert :title="t('basis')" type="info" :closable="false" />
      <el-tabs v-model="tab">
        <el-tab-pane :label="t('actual')" name="actual">
          <el-table :data="workspace.entries || []" :empty-text="t('emptyActual')">
            <el-table-column :label="t('person')" min-width="110"><template #default="{row}">{{ row.userName || row.userNameSnapshot || row.userId }}</template></el-table-column>
            <el-table-column prop="bizDate" :label="t('date')" width="115"/>
            <el-table-column :label="t('quantity')" min-width="125"><template #default="{row}">{{ row.inputQuantity }} {{ unit(row.inputUnit) }}<div class="muted">{{ row.minutes ?? row.actualMinutes ?? row.workMinutes }} {{ t('minutes') }}</div></template></el-table-column>
            <el-table-column prop="activity" :label="t('activity')" min-width="180"/>
            <el-table-column :label="t('state')" width="120"><template #default="{row}"><el-tag :type="row.status==='CONFIRMED'?'success':'info'">{{ state(row.status) }}</el-tag><div v-if="row.parentEntryId" class="muted">{{ t('correction') }}</div></template></el-table-column>
            <el-table-column prop="reason" :label="t('reason')" min-width="150"/>
            <el-table-column :label="t('actions')" min-width="240" fixed="right"><template #default="{row}"><div class="row-actions"><el-button v-if="row.canEdit" v-hasPermi="['business:work:report']" link @click="openEntry(row)">{{ t('edit') }}</el-button><el-button v-if="row.canSubmit" v-hasPermi="['business:work:report']" link type="primary" @click="act(row,'submit')">{{ t('submit') }}</el-button><el-button v-if="row.canWithdraw" v-hasPermi="['business:work:report']" link @click="act(row,'withdraw')">{{ t('withdraw') }}</el-button><el-button v-if="row.canConfirm" v-hasPermi="['business:work:confirm']" link type="success" @click="act(row,'confirm')">{{ t('confirm') }}</el-button><el-button v-if="row.canReturn" v-hasPermi="['business:work:confirm']" link type="warning" @click="act(row,'return')">{{ t('return') }}</el-button><el-button v-if="row.canCorrect" v-hasPermi="['business:work:report']" link @click="openEntry(row,true)">{{ t('correct') }}</el-button><el-button v-if="row.canDiscard" v-hasPermi="['business:work:report']" link type="danger" @click="act(row,'discard')">{{ t('discard') }}</el-button><el-button link @click="history(row)">{{ t('history') }}</el-button><span v-if="row.confirmingSelfBlocked" class="muted">{{ t('selfBlocked') }}</span></div></template></el-table-column>
          </el-table>
        </el-tab-pane>
        <el-tab-pane :label="t('planned')" name="planned"><el-table :data="workspace.assignments || []" :empty-text="t('emptyPlan')"><el-table-column :label="t('person')"><template #default="{row}">{{ row.userName || row.userNameSnapshot || row.userId }}</template></el-table-column><el-table-column prop="effectiveFrom" :label="t('from')"/><el-table-column prop="effectiveTo" :label="t('to')"/><el-table-column :label="t('quantity')"><template #default="{row}">{{ row.inputQuantity }} {{ unit(row.inputUnit) }}</template></el-table-column><el-table-column prop="reason" :label="t('reason')" min-width="150"/><el-table-column :label="t('state')"><template #default="{row}">{{ state(row.status) }}</template></el-table-column><el-table-column :label="t('actions')"><template #default="{row}"><el-button v-if="row.canRetire" v-hasPermi="['business:resource:edit']" link type="danger" @click="retire(row)">{{ t('retire') }}</el-button></template></el-table-column></el-table></el-tab-pane>
        <el-tab-pane :label="t('policy')" name="policy"><h3>{{ t('calendar') }}</h3><el-table :data="workspace.calendars || []"><el-table-column prop="calendarName" :label="t('name')"/><el-table-column prop="timeZone" :label="t('timezone')"/><el-table-column prop="dailyMinutes" :label="t('dailyMinutes')"/><el-table-column prop="workingWeekdays" :label="t('weekdays')"/><el-table-column prop="effectiveFrom" :label="t('from')"/></el-table><h3>{{ t('unitPolicy') }}</h3><el-table :data="workspace.unitPolicies || []"><el-table-column prop="policyName" :label="t('name')"/><el-table-column prop="minutesPerDay" :label="t('minutesPerDay')"/><el-table-column prop="effectiveFrom" :label="t('from')"/></el-table></el-tab-pane>
      </el-tabs>
    </template>
    <el-dialog v-model="editOpen" :title="editingAssignment?t('arrange'):correcting?t('correct'):t('record')" width="min(700px,96vw)" append-to-body>
      <el-form :model="form" label-position="top" class="business-product"><div class="form-grid">
        <el-form-item :label="t('person')" required><el-select v-model="form.userId" :disabled="!editingAssignment && (!!form.entryId || Number(user.id)!==Number(workspace.project?.mainOwnerUserId))"><el-option v-for="m in selectableMembers" :key="m.userId" :label="m.userName || m.userNameSnapshot || String(m.userId)" :value="m.userId"/></el-select></el-form-item>
        <el-form-item v-if="!editingAssignment" :label="t('date')" required><el-date-picker v-model="form.bizDate" :disabled="correcting || !!form.entryId" type="date" value-format="YYYY-MM-DD" :disabled-date="disabledWorkDate"/></el-form-item>
        <template v-if="editingAssignment"><el-form-item :label="t('from')" required><el-date-picker v-model="form.effectiveFrom" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="t('to')" required><el-date-picker v-model="form.effectiveTo" type="date" value-format="YYYY-MM-DD"/></el-form-item></template>
        <el-form-item :label="t('quantity')" required><el-input-number v-model="form.inputQuantity" :min="correcting?0:0.01" :precision="4"/></el-form-item><el-form-item :label="t('unit')"><el-select v-model="form.inputUnit"><el-option :label="t('day')" value="DAY"/><el-option :label="t('hour')" value="HOUR"/><el-option v-if="editingAssignment" :label="t('percentage')" value="PERCENTAGE"/></el-select></el-form-item>
        <el-form-item :label="t('calendar')" required><el-select v-model="form.calendarId" :disabled="correcting"><el-option v-for="c in workspace.calendars || []" :key="c.calendarId" :label="`${c.calendarName} · ${c.dailyMinutes} ${t('minutes')}`" :value="c.calendarId"/></el-select></el-form-item><el-form-item :label="t('unitPolicy')" required><el-select v-model="form.unitPolicyId"><el-option v-for="u in workspace.unitPolicies || []" :key="u.unitPolicyId" :label="`${u.policyName} · ${u.minutesPerDay} ${t('minutes')}`" :value="u.unitPolicyId"/></el-select></el-form-item>
        <el-form-item v-if="!editingAssignment" :label="t('activity')" class="wide" required><el-input v-model="form.activity" :disabled="correcting" maxlength="300"/></el-form-item><el-form-item :label="t('reason')" class="wide" required><el-input v-model="form.reason" type="textarea" :rows="3" maxlength="1000"/></el-form-item>
      </div><el-alert :title="editingAssignment?t('planningHint'):t('entryHint')" type="info" :closable="false"/></el-form>
      <template #footer><el-button @click="editOpen=false">{{ t('cancel') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ t('saveDraft') }}</el-button></template>
    </el-dialog>
    <el-dialog v-model="configOpen" :title="configType==='calendar'?t('calendar'):t('unitPolicy')" width="min(680px,96vw)" append-to-body>
      <el-form label-position="top"><el-form-item :label="t('name')" required><el-input v-model="configForm.name" maxlength="100"/></el-form-item><el-form-item :label="t('from')" required><el-date-picker v-model="configForm.effectiveFrom" type="date" value-format="YYYY-MM-DD"/></el-form-item><el-form-item :label="t('to')"><el-date-picker v-model="configForm.effectiveTo" type="date" value-format="YYYY-MM-DD"/></el-form-item><template v-if="configType==='calendar'"><el-form-item :label="t('timezone')"><el-input v-model="configForm.timeZone"/></el-form-item><el-form-item :label="t('weekdays')"><el-checkbox-group v-model="configForm.weekdays"><el-checkbox v-for="d in 7" :key="d" :value="String(d)">{{ t(`week.${d}`) }}</el-checkbox></el-checkbox-group></el-form-item></template><el-form-item :label="configType==='calendar'?t('dailyMinutes'):t('minutesPerDay')" required><el-input-number v-model="configForm.minutes" :min="1" :max="1440" :precision="0"/></el-form-item>
      <template v-if="configType==='calendar'"><h4>{{ t('exceptions') }}</h4><div v-for="(e,i) in configForm.exceptions" :key="i" class="row-actions"><el-date-picker v-model="e.bizDate" type="date" value-format="YYYY-MM-DD"/><el-input-number v-model="e.minutes" :min="0" :max="1440" :precision="0"/><el-button link type="danger" @click="configForm.exceptions.splice(i,1)">{{ t('remove') }}</el-button></div><el-button @click="configForm.exceptions.push({bizDate:null,minutes:0})">{{ t('addException') }}</el-button></template><el-alert :title="t('versionHint')" type="info" :closable="false"/></el-form>
      <template #footer><el-button @click="configOpen=false">{{ t('cancel') }}</el-button><el-button type="primary" :loading="saving" @click="saveConfig">{{ t('publish') }}</el-button></template>
    </el-dialog>
    <el-drawer v-model="historyOpen" :title="t('history')" size="min(760px,96vw)" append-to-body><el-timeline><el-timeline-item v-for="row in historyRows" :key="row.auditId" :timestamp="row.createTime"><b>{{ row.action }} · {{ row.actorName }}</b><p>{{ row.reason }}</p></el-timeline-item></el-timeline></el-drawer>
  </section>
</template>

<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import useUserStore from '@/store/modules/user'
import { getProjectWork, saveProjectAssignment, retireProjectAssignment, saveProjectWorkEntry, actProjectWorkEntry, createProjectCalendar, createProjectUnitPolicy, getProjectWorkHistory } from '@/api/business/projectWork'
import '@/assets/styles/business-product.scss'
const props=defineProps({projectId:{type:[Number,String],required:true}}), emit=defineEmits(['changed']), user=useUserStore()
const workspace=reactive({}), loading=ref(false),saving=ref(false),tab=ref('actual'),editOpen=ref(false),editingAssignment=ref(false),correcting=ref(false),form=reactive({}),configOpen=ref(false),configType=ref('calendar'),configForm=reactive({})
const dateString=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10),today=()=>dateString(new Date())
const anchor=new Date();anchor.setDate(anchor.getDate()-6);const dates=ref([dateString(anchor),today()]);let sequence=0
const legacy=computed(()=>workspace.project && workspace.project.costPolicyVersion!=='ACTUAL_WORK_V1')
const confirmedDays=computed(()=>{const rows=(workspace.entries||[]).filter(e=>e.status==='CONFIRMED'&&String(e.isCurrent)==='1');return rows.some(e=>!(Number(e.minutesPerDay)>0)||e.workMinutes==null)?'—':rows.reduce((sum,e)=>sum+Number(e.workMinutes)/Number(e.minutesPerDay),0).toFixed(2)})
const historyOpen=ref(false),historyRows=ref([])
async function history(row){historyRows.value=(await getProjectWorkHistory(row.entryId)).data||[];historyOpen.value=true}
const selectableMembers=computed(()=>{const rows=workspace.members||[];if(form.entryId)return rows.filter(m=>Number(m.userId)===Number(form.userId));return rows.filter(m=>m.memberRole!=='OBSERVER'&&(m.status==='0'||m.leftDate))})
const pendingEntries=computed(()=>(workspace.entries||[]).filter(e=>['DRAFT','RETURNED','SUBMITTED'].includes(e.status)).length)
const {t,te}=useI18n({useScope:'local',messages:{
 'zh-CN':{pendingCost:'已确认工作待计价，尚不能视为完整成本',history:'操作历史',discard:'作废草稿',title:'人员安排与实际投入',intro:'计划安排与实际工作分别记录，按人、日期和确认版本追溯。',refresh:'刷新',legacy:'该项目沿用历史比例成本规则。新项目使用独立工作量记录，历史数据不自动换算。',record:'记录实际投入',arrange:'安排人员',calendar:'工作日历',unitPolicy:'人天换算政策',recorded:'本期已确认人天',pending:'待处理记录',notRecorded:'未填报仍为未记录',day:'人天',hour:'小时',minutes:'分钟',percentage:'容量比例（%）',basis:'日历决定可用容量，单位政策决定每人天分钟数。日历变更不改写已确认人天。',actual:'实际工作',planned:'人员计划',policy:'日历与单位',emptyActual:'尚未记录实际工作，计划不会自动计入实际',emptyPlan:'尚未安排人员；有效成员仍可说明活动后申报',person:'人员',date:'工作日期',quantity:'工作量',activity:'活动／工作说明',state:'状态',reason:'依据／原因',actions:'操作',correction:'更正版本',edit:'编辑',submit:'提交确认',withdraw:'撤回',confirm:'确认',return:'退回',correct:'申请更正',selfBlocked:'本人记录需由另一责任人确认',from:'开始日期',to:'结束日期',retire:'停用计划',name:'名称',timezone:'时区',dailyMinutes:'每天可用分钟',weekdays:'工作日',minutesPerDay:'每人天分钟数',unit:'计量单位',planningHint:'比例只用于安排容量；小时或人天是这段参与期间的计划总工作量。',entryHint:'按工作日记录数量；不自动从考勤推算。更正批准前，原确认版本仍然有效。',cancel:'取消',saveDraft:'保存',exceptions:'节假日与半天例外',remove:'删除',addException:'添加日期例外',versionHint:'发布新版本，不覆盖已有记录的日历和换算快照。',publish:'发布新版本',required:'请完整填写日期、数量、人员及原因',reasonPrompt:'请填写处理依据或原因',success:'操作成功',week:{1:'一',2:'二',3:'三',4:'四',5:'五',6:'六',7:'日'},states:{DRAFT:'草稿',SUBMITTED:'待确认',RETURNED:'已退回',WITHDRAWN:'已撤回',CONFIRMED:'已确认',SUPERSEDED:'已被更正',ACTIVE:'有效',VOID:'已停用',VOIDED:'已作废',DISCARDED:'已作废',RETIRED:'已停用'}},
 'vi-VN':{pendingCost:'Công việc đã xác nhận chờ định giá; chi phí chưa đầy đủ',history:'Lịch sử thao tác',discard:'Hủy bản nháp',title:'Phân bổ nhân sự và công việc thực tế',intro:'Kế hoạch và thực tế được ghi riêng, theo người, ngày và phiên bản xác nhận.',refresh:'Làm mới',legacy:'Dự án giữ phương pháp tỷ lệ cũ. Không tự chuyển dữ liệu lịch sử thành công việc thực tế.',record:'Ghi công việc thực tế',arrange:'Phân bổ nhân sự',calendar:'Lịch làm việc',unitPolicy:'Quy đổi ngày công',recorded:'Ngày công đã xác nhận',pending:'Bản ghi chờ xử lý',notRecorded:'Chưa khai báo là chưa ghi nhận',day:'Ngày công',hour:'Giờ',minutes:'Phút',percentage:'Tỷ lệ công suất (%)',basis:'Lịch xác định khả năng làm việc; chính sách đơn vị xác định phút/ngày công. Thay lịch không sửa lịch sử.',actual:'Công việc thực tế',planned:'Kế hoạch nhân sự',policy:'Lịch và đơn vị',emptyActual:'Chưa có thực tế; kế hoạch không tự chuyển thành thực tế',emptyPlan:'Chưa có kế hoạch; thành viên hợp lệ vẫn được khai báo hoạt động',person:'Nhân sự',date:'Ngày làm việc',quantity:'Khối lượng',activity:'Hoạt động / mô tả',state:'Trạng thái',reason:'Căn cứ / lý do',actions:'Thao tác',correction:'Phiên bản sửa',edit:'Sửa',submit:'Gửi xác nhận',withdraw:'Rút lại',confirm:'Xác nhận',return:'Trả lại',correct:'Đề nghị sửa',selfBlocked:'Cần người có trách nhiệm khác xác nhận bản ghi của mình',from:'Ngày bắt đầu',to:'Ngày kết thúc',retire:'Dừng kế hoạch',name:'Tên',timezone:'Múi giờ',dailyMinutes:'Phút làm việc mỗi ngày',weekdays:'Ngày làm việc',minutesPerDay:'Phút mỗi ngày công',unit:'Đơn vị',planningHint:'Tỷ lệ dùng để phân bổ khả năng làm việc; giờ/ngày công là tổng kế hoạch trong khoảng tham gia.',entryHint:'Ghi số lượng theo ngày, không suy từ chấm công. Bản gốc có hiệu lực đến khi bản sửa được duyệt.',cancel:'Hủy',saveDraft:'Lưu',exceptions:'Ngoại lệ ngày lễ và nửa ngày',remove:'Xóa',addException:'Thêm ngoại lệ',versionHint:'Công bố phiên bản mới; giữ nguyên lịch và quy đổi của bản ghi cũ.',publish:'Công bố phiên bản',required:'Điền ngày, số lượng, nhân sự và lý do',reasonPrompt:'Nhập căn cứ hoặc lý do',success:'Thành công',week:{1:'T2',2:'T3',3:'T4',4:'T5',5:'T6',6:'T7',7:'CN'},states:{DRAFT:'Nháp',SUBMITTED:'Chờ xác nhận',RETURNED:'Đã trả lại',WITHDRAWN:'Đã rút',CONFIRMED:'Đã xác nhận',SUPERSEDED:'Đã thay thế',ACTIVE:'Có hiệu lực',VOID:'Đã dừng',VOIDED:'Đã hủy',DISCARDED:'Đã hủy',RETIRED:'Đã dừng'}}
}})
const state=v=>te(`states.${v}`)?t(`states.${v}`):v,unit=v=>v==='DAY'?t('day'):v==='HOUR'?t('hour'):v==='PERCENTAGE'?'%':v
async function load(){const n=++sequence;if(!props.projectId)return;loading.value=true;try{const r=await getProjectWork(props.projectId,{dateFrom:dates.value?.[0],dateTo:dates.value?.[1]});if(n===sequence){Object.keys(workspace).forEach(k=>delete workspace[k]);Object.assign(workspace,r.data||{})}}finally{if(n===sequence)loading.value=false}}
function resetForm(){Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,{userId:Number(user.id),bizDate:today(),inputUnit:'DAY',inputQuantity:null,calendarId:workspace.calendars?.[0]?.calendarId,unitPolicyId:workspace.unitPolicies?.[0]?.unitPolicyId,activity:'',reason:'',sourceKey:crypto.randomUUID()})}
function openEntry(row,correction=false){resetForm();if(row)Object.assign(form,row);editingAssignment.value=false;correcting.value=correction;if(correction)form.reason='';editOpen.value=true}
function openAssignment(){resetForm();Object.assign(form,{userId:null,effectiveFrom:workspace.project?.planStartDate&&workspace.project.planStartDate>today()?workspace.project.planStartDate:today(),effectiveTo:workspace.project?.planEndDate||today()});editingAssignment.value=true;correcting.value=false;editOpen.value=true}
function disabledWorkDate(d){const day=dateString(d),end=workspace.project?.actualEndDate,start=workspace.project?.actualStartDate;return day>today()||(end&&day>end)||(start&&day<start)}
async function save(){if(!form.userId||form.inputQuantity==null||!form.reason?.trim()||!form.calendarId||!form.unitPolicyId||(!editingAssignment.value&&!form.activity?.trim()))return ElMessage.warning(t('required'));saving.value=true;try{if(editingAssignment.value)await saveProjectAssignment(props.projectId,{...form});else if(correcting.value)await actProjectWorkEntry(form.entryId,'corrections',{version:form.version,inputQuantity:form.inputQuantity,inputUnit:form.inputUnit,unitPolicyId:form.unitPolicyId,reason:form.reason});else await saveProjectWorkEntry(props.projectId,{...form});editOpen.value=false;await load();emit('changed');ElMessage.success(t('success'))}finally{saving.value=false}}
async function reason(){return (await ElMessageBox.prompt(t('reasonPrompt'),t('confirm'),{inputType:'textarea',inputValidator:v=>!!v?.trim()||t('required')})).value.trim()}
async function act(row,action){try{await actProjectWorkEntry(row.entryId,action,{version:row.version,reason:await reason()});await load();emit('changed')}catch(e){if(!['cancel','close'].includes(e))await load()}}
async function retire(row){try{await retireProjectAssignment(row.assignmentId,{version:row.version,reason:await reason()});await load()}catch(e){if(!['cancel','close'].includes(e))await load()}}
function openConfig(kind){configType.value=kind;Object.assign(configForm,{name:'',effectiveFrom:today(),effectiveTo:null,timeZone:'Asia/Shanghai',weekdays:['1','2','3','4','5'],minutes:480,exceptions:[]});configOpen.value=true}
async function saveConfig(){if(!configForm.name?.trim()||!configForm.effectiveFrom||!(configForm.minutes>0))return ElMessage.warning(t('required'));saving.value=true;try{const common={effectiveFrom:configForm.effectiveFrom,effectiveTo:configForm.effectiveTo};if(configType.value==='calendar')await createProjectCalendar({...common,calendarName:configForm.name,timeZone:configForm.timeZone,workingWeekdays:configForm.weekdays.join(','),dailyMinutes:configForm.minutes,exceptions:configForm.exceptions});else await createProjectUnitPolicy({...common,policyName:configForm.name,minutesPerDay:configForm.minutes});configOpen.value=false;await load()}finally{saving.value=false}}
watch(()=>props.projectId,load,{immediate:true})
</script>

<style scoped>.work-panel{padding:0}.work-panel :deep(.el-dialog .business-product){padding:0}.work-panel :deep(.el-tabs__content){overflow:visible}</style>
