-- Project owners submit employee leave requests; company owners approve before leave affects project effort and cost.
create table if not exists biz_staff_leave_request (
  request_id bigint not null auto_increment comment 'leave request id',
  request_no varchar(40) not null comment 'stable request number',
  user_id bigint not null comment 'employee user id',
  user_name varchar(100) not null comment 'employee display name snapshot',
  leave_start_date date not null comment 'first leave date',
  leave_end_date date not null comment 'last leave date',
  leave_type varchar(24) not null comment 'SICK/PERSONAL/ANNUAL/COMPENSATORY/OTHER',
  reason varchar(500) not null comment 'leave reason',
  attachment_urls varchar(4000) default null comment 'supporting files',
  status varchar(16) not null default 'PENDING' comment 'PENDING/APPROVED/RETURNED/CANCEL_PENDING/CANCELED',
  submitted_project_id bigint not null comment 'project where the request was submitted',
  submitted_project_name varchar(200) not null comment 'project name snapshot',
  submitted_user_id bigint not null comment 'requester user id',
  submitted_user_name varchar(100) not null comment 'requester display name snapshot',
  submitted_time datetime not null default current_timestamp,
  reviewed_user_id bigint default null,
  reviewed_user_name varchar(100) default null,
  reviewed_time datetime default null,
  review_comment varchar(1000) default null,
  canceled_user_id bigint default null,
  canceled_user_name varchar(100) default null,
  canceled_time datetime default null,
  cancel_reason varchar(500) default null,
  version int not null default 0,
  create_by varchar(64) default '',
  create_time datetime not null default current_timestamp,
  update_by varchar(64) default '',
  update_time datetime default null,
  primary key (request_id),
  unique key uk_staff_leave_request_no (request_no),
  key idx_staff_leave_request_reviewer (status, submitted_project_id, submitted_time),
  key idx_staff_leave_request_user_date (user_id, leave_start_date, leave_end_date)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_0900_ai_ci comment='employee leave approval request';
