<template>
  <div class="app-container">
    <el-form inline><el-form-item><el-input v-model="query.keyword" :placeholder="$tr(&quot;编码、达人ID、名称或平台账号&quot;)" clearable @keyup.enter="load"/></el-form-item><el-form-item><el-select v-model="query.priceStatus" :placeholder="$tr(&quot;全部定价状态&quot;)" clearable style="width:170px"><el-option :label="$tr(&quot;已有商品定价&quot;)" value="PRICED"/><el-option :label="$tr(&quot;有待生效价格&quot;)" value="PENDING"/><el-option :label="$tr(&quot;尚无商品价格&quot;)" value="UNPRICED"/></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="load">{{ $tr("查询") }}</el-button></el-form-item></el-form>
    <el-button type="primary" plain icon="Plus" class="mb8" v-hasPermi="['jewelry:influencer:add']" @click="openProfile()">{{ $tr("新增达人/主播") }}</el-button>
    <el-table :data="rows" v-loading="loading" border><el-table-column prop="influencerCode" :label="$tr(&quot;达人编码&quot;)" width="125"/><el-table-column prop="externalInfluencerId" :label="$tr(&quot;达人ID&quot;)" min-width="130" show-overflow-tooltip/><el-table-column prop="influencerName" :label="$tr(&quot;达人/主播&quot;)" min-width="150"/><el-table-column prop="platform" :label="$tr(&quot;平台&quot;)" width="100"/><el-table-column prop="platformAccount" :label="$tr(&quot;平台账号&quot;)" min-width="140"/><el-table-column prop="salesChannel" :label="$tr(&quot;默认销售渠道&quot;)" width="140"/><el-table-column :label="$tr(&quot;商品关联&quot;)" width="225"><template #default="{row}"><el-tag type="success">{{ $tr('已定价 {0} 种', [row.pricedProductCount||0]) }}</el-tag><el-tag v-if="Number(row.pendingProductCount||0)>0" type="warning" class="ml5">{{ $tr('待生效 {0} 种', [row.pendingProductCount]) }}</el-tag></template></el-table-column><el-table-column :label="$tr(&quot;状态&quot;)" width="80"><template #default="{row}"><el-tag :type="row.status==='0'?'success':'info'">{{row.status==='0'?$tr('启用'):$tr('停用')}}</el-tag></template></el-table-column><el-table-column :label="$tr(&quot;操作&quot;)" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" v-hasPermi="['jewelry:influencer:edit','jewelry:influencer:price']" @click="openProfile(row)">{{ canEditProfile?$tr("编辑"):$tr("商品绑定") }}</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.pageNum" v-model:limit="query.pageSize" :total="total" @pagination="load"/>
    <el-dialog v-model="profileDialog" :title="profile.influencerId?$tr('编辑达人/主播'):$tr('新增达人/主播')" :width="profile.influencerId?'1180px':'650px'" destroy-on-close>
      <el-tabs v-model="activeTab"><el-tab-pane :label="$tr(&quot;基本信息&quot;)" name="basic"><el-form ref="profileRef" :model="profile" :rules="profileRules" label-width="125px" class="profile-form"><el-form-item :label="$tr(&quot;达人编码&quot;)"><el-input :model-value="profile.influencerId ? profile.influencerCode : $tr('{0}+流水号，保存后生成', [profile.platformCode||$tr('平台简写')])" disabled/></el-form-item><el-form-item :label="$tr(&quot;平台&quot;)" prop="platformCode"><el-select v-model="profile.platformCode" :disabled="!!profile.influencerId" :placeholder="$tr(&quot;请选择平台&quot;)" style="width:100%" @change="onPlatformChange"><el-option v-for="p in platforms" :key="p.platformCode" :label="`${p.platformName}（${p.platformCode}）`" :value="p.platformCode"/></el-select></el-form-item><el-form-item :label="$tr(&quot;达人ID&quot;)"><el-input v-model="profile.externalInfluencerId" :disabled="!!profile.influencerId&&!canEditProfile" :placeholder="$tr(&quot;平台侧达人ID&quot;)"/></el-form-item><el-form-item :label="$tr(&quot;达人/主播名称&quot;)" prop="influencerName"><el-input v-model="profile.influencerName" :disabled="!!profile.influencerId&&!canEditProfile"/></el-form-item><el-form-item :label="$tr(&quot;平台账号&quot;)"><el-input v-model="profile.platformAccount" :disabled="!!profile.influencerId&&!canEditProfile"/></el-form-item><el-form-item :label="$tr(&quot;默认销售渠道&quot;)"><el-input v-model="profile.salesChannel" :disabled="!!profile.influencerId&&!canEditProfile"/></el-form-item><el-form-item :label="$tr(&quot;联系电话&quot;)"><el-input v-model="profile.contactPhone" :disabled="!!profile.influencerId&&!canEditProfile"/></el-form-item><el-form-item :label="$tr(&quot;状态&quot;)"><el-radio-group v-model="profile.status" :disabled="!!profile.influencerId&&!canEditProfile"><el-radio value="0">{{ $tr("启用") }}</el-radio><el-radio value="1">{{ $tr("停用") }}</el-radio></el-radio-group></el-form-item><el-form-item :label="$tr(&quot;备注&quot;)"><el-input v-model="profile.remark" :disabled="!!profile.influencerId&&!canEditProfile" type="textarea"/></el-form-item></el-form><div v-if="!profile.influencerId||canEditProfile" class="tab-actions"><el-button type="primary" @click="saveProfile">{{ $tr("保存基本信息") }}</el-button></div></el-tab-pane>
      <template v-if="profile.influencerId"><el-tab-pane :label="$tr(&quot;商品绑定&quot;)" name="bindings"><el-alert :title="$tr(&quot;按成品商品维护直播成交价、佣金及费用。保存后成为正式价格；历史销售单仍使用原价格快照。配件商品请在搭售配置中选择。&quot;)" type="info" :closable="false" class="mb12"/><div class="toolbar" v-if="canPrice"><el-button type="primary" plain @click="openBinding()">{{ $tr("新增商品绑定") }}</el-button><el-button @click="downloadTemplate">{{ $tr("下载Excel模板") }}</el-button><el-upload :show-file-list="false" :auto-upload="false" accept=".xlsx,.xls" :on-change="previewExcel"><el-button>{{ $tr("批量Excel导入") }}</el-button></el-upload></div><el-table :data="bindings" border max-height="440"><el-table-column prop="sku" label="SKU" width="130"/><el-table-column prop="productName" :label="$tr(&quot;商品&quot;)" min-width="155" show-overflow-tooltip/><el-table-column :label="$tr(&quot;类型&quot;)" width="100"><template #default="{row}">{{typeName(row.productType)}}</template></el-table-column><el-table-column :label="$tr(&quot;直播价&quot;)" width="100" align="right"><template #default="{row}">{{money(row.fixedUnitPrice)}}</template></el-table-column><el-table-column :label="$tr(&quot;佣金/平台/税率 %&quot;)" width="195"><template #default="{row}">{{percent(row.commissionRate)}} / {{percent(row.platformRate)}} / {{percent(row.taxRate)}}</template></el-table-column><el-table-column :label="$tr(&quot;包装/物流/鉴定&quot;)" width="180"><template #default="{row}">{{money(row.packFee)}} / {{money(row.shipFee)}} / {{money(row.certFee)}}</template></el-table-column><el-table-column :label="$tr(&quot;状态&quot;)" width="90"><template #default="{row}"><el-tag :type="row.priceStatus==='PENDING'?'warning':row.bindingStatus==='1'?'info':'success'">{{row.priceStatus==='PENDING'?$tr('待生效'):row.bindingStatus==='1'?$tr('停用'):$tr('启用')}}</el-tag></template></el-table-column><el-table-column :label="$tr(&quot;操作&quot;)" width="75" v-if="canPrice"><template #default="{row}"><el-button v-if="row.productType==='FINISHED'" link type="primary" :disabled="row.priceStatus==='PENDING'" @click="openBinding(row)">{{ $tr("编辑") }}</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane :label="$tr(&quot;搭售配置&quot;)" name="bundles"><el-alert :title="$tr(&quot;预设搭售关系供后续制单选择；配置本身不会变动库存。&quot;)" type="info" :closable="false" class="mb12"/><div class="toolbar" v-if="canPrice"><el-button type="primary" plain @click="openBundle">{{ $tr("新增搭售配置") }}</el-button></div><el-table :data="bundles" border max-height="400"><el-table-column prop="mainSku" :label="$tr(&quot;主商品SKU&quot;)" width="150"/><el-table-column prop="mainProductName" :label="$tr(&quot;主商品&quot;)" min-width="160"/><el-table-column prop="addonSku" :label="$tr(&quot;搭售SKU&quot;)" width="150"/><el-table-column prop="addonProductName" :label="$tr(&quot;搭售商品&quot;)" min-width="160"/><el-table-column :label="$tr(&quot;数量比&quot;)" width="100"><template #default="{row}">{{row.mainQty}} : {{row.addonQty}}</template></el-table-column><el-table-column :label="$tr(&quot;计价&quot;)" width="120"><template #default="{row}">{{row.pricingMode==='INCLUDED'?$tr('包含组合价'):$tr('单独计价')}}</template></el-table-column><el-table-column :label="$tr(&quot;操作&quot;)" width="80" v-if="canPrice"><template #default="{row}"><el-button link type="danger" @click="removeBundle(row)">{{ $tr("删除") }}</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane :label="$tr(&quot;价格历史&quot;)" name="history"><el-table :data="history" border max-height="430"><el-table-column prop="sku" label="SKU" width="125"/><el-table-column prop="productName" :label="$tr(&quot;商品&quot;)" min-width="150"/><el-table-column prop="priceVersion" :label="$tr(&quot;版本&quot;)" width="70"/><el-table-column :label="$tr(&quot;原价&quot;)" width="110"><template #default="{row}">{{row.oldPrice==null?'—':money(row.oldPrice)}}</template></el-table-column><el-table-column :label="$tr(&quot;新价&quot;)" width="110"><template #default="{row}">{{money(row.newPrice)}}</template></el-table-column><el-table-column :label="$tr(&quot;来源&quot;)" width="110"><template #default="{row}">{{sourceName(row.sourceType)}}</template></el-table-column><el-table-column prop="changeReason" :label="$tr(&quot;原因&quot;)" min-width="160"/><el-table-column prop="operatorName" :label="$tr(&quot;操作人&quot;)" width="100"/><el-table-column prop="createTime" :label="$tr(&quot;时间&quot;)" width="165"/></el-table></el-tab-pane>
      <el-tab-pane :label="$tr(&quot;历史搭售&quot;)" name="soldBundles"><el-table :data="soldBundles" border max-height="430"><el-table-column prop="mainSku" :label="$tr(&quot;主商品SKU&quot;)" width="140"/><el-table-column prop="mainProductName" :label="$tr(&quot;主商品&quot;)" min-width="150"/><el-table-column prop="addonSku" :label="$tr(&quot;搭售SKU&quot;)" width="140"/><el-table-column prop="addonProductName" :label="$tr(&quot;搭售商品&quot;)" min-width="150"/><el-table-column :label="$tr(&quot;数量比&quot;)" width="100"><template #default="{row}">{{row.mainQty}} : {{row.addonQty}}</template></el-table-column><el-table-column prop="sourceDocNo" :label="$tr(&quot;最近销售单&quot;)" width="180"/></el-table></el-tab-pane></template></el-tabs><template #footer><el-button @click="profileDialog=false">{{ $tr("关闭") }}</el-button></template></el-dialog>
    <el-dialog v-model="bindingDialog" :title="binding.editing?$tr('编辑商品绑定'):$tr('新增商品绑定')" width="680px" append-to-body><el-form label-width="125px" class="binding-form"><el-form-item :label="$tr(&quot;商品&quot;)" required><el-select v-model="binding.productId" filterable :disabled="!!binding.editing" :placeholder="$tr(&quot;选择成品商品&quot;)" style="width:100%"><el-option v-for="p in bindingProducts" :key="p.productId" :label="`${p.sku} · ${p.productName}（${typeName(p.productType)}）`" :value="p.productId"/></el-select></el-form-item><el-form-item :label="$tr(&quot;直播成交价&quot;)" required><el-input-number v-model="binding.fixedUnitPrice" :min="0.0001" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;达人佣金率 %&quot;)"><el-input-number v-model="binding.commissionPercent" :min="0" :max="100" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;平台扣点率 %&quot;)"><el-input-number v-model="binding.platformPercent" :min="0" :max="100" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;税率 %&quot;)"><el-input-number v-model="binding.taxPercent" :min="0" :max="100" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;包装费&quot;)"><el-input-number v-model="binding.packFee" :min="0" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;物流费&quot;)"><el-input-number v-model="binding.shipFee" :min="0" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;鉴定费&quot;)"><el-input-number v-model="binding.certFee" :min="0" :precision="4" style="width:100%"/></el-form-item><el-form-item :label="$tr(&quot;绑定状态&quot;)"><el-radio-group v-model="binding.bindingStatus"><el-radio value="0">{{ $tr("启用") }}</el-radio><el-radio value="1">{{ $tr("停用") }}</el-radio></el-radio-group></el-form-item><el-form-item :label="$tr(&quot;备注/改价原因&quot;)"><el-input v-model="binding.bindingRemark" type="textarea" :rows="2"/></el-form-item></el-form><template #footer><el-button @click="bindingDialog=false">{{ $tr("取消") }}</el-button><el-button type="primary" :loading="saving" @click="saveBinding">{{ $tr("保存绑定") }}</el-button></template></el-dialog>
    <el-dialog v-model="bundleDialog" :title="$tr(&quot;新增搭售配置&quot;)" width="620px" append-to-body><el-form label-width="115px"><el-form-item :label="$tr(&quot;主商品&quot;)"><el-select v-model="bundle.mainProductId" filterable style="width:100%"><el-option v-for="p in mainProducts" :key="p.productId" :value="p.productId" :label="`${p.sku} · ${p.productName}`"/></el-select></el-form-item><el-form-item :label="$tr(&quot;搭售商品&quot;)"><el-select v-model="bundle.addonProductId" filterable style="width:100%" :placeholder="$tr(&quot;选择已在库的配件商品&quot;)"><el-option v-for="p in addonProducts" :key="p.productId" :value="p.productId" :label="$tr('{0} · {1}（账面库存 {2}）', [p.sku, p.productName, p.totalStockQty])"/></el-select></el-form-item><el-form-item :label="$tr(&quot;主商品数量&quot;)"><el-input-number v-model="bundle.mainQty" :min="1" :precision="0"/></el-form-item><el-form-item :label="$tr(&quot;搭售数量&quot;)"><el-input-number v-model="bundle.addonQty" :min="1" :precision="0"/></el-form-item><el-form-item :label="$tr(&quot;计价方式&quot;)">{{ $tr("包含组合价") }}</el-form-item></el-form><template #footer><el-button @click="bundleDialog=false">{{ $tr("取消") }}</el-button><el-button type="primary" :loading="saving" @click="saveBundle">{{ $tr("保存") }}</el-button></template></el-dialog>
    <BindingImportDialog v-model="excelDialog" :rows="excelRows" :products="bindingProducts" :saving="saving" @submit="confirmExcel" />
  </div>
</template>
<script setup name="JewelryInfluencer">
import { translateText } from '@/locales/translate'
import { saveAs } from 'file-saver'
import { jewelryProductType } from '@/utils/jewelryProduct'
import { listJewelryProductOptions, listJewelryInfluencers, listJewelryInfluencerPlatforms, saveJewelryInfluencer, getJewelryInfluencerProductPrices, saveJewelryInfluencerBindings, previewJewelryInfluencerBindings, confirmJewelryInfluencerBindings, getJewelryInfluencerBundleConfigs, saveJewelryInfluencerBundleConfig, deleteJewelryInfluencerBundleConfig, getJewelryInfluencerPriceHistory, getJewelryInfluencerBundleItems } from '@/api/jewelry/erp'
import BindingImportDialog from './BindingImportDialog.vue'
import request from '@/utils/request'
import useUserStore from '@/store/modules/user'
const { proxy } = getCurrentInstance()
const userStore = useUserStore()
const canEditProfile = computed(() => userStore.permissions?.includes('*:*:*') || userStore.permissions?.includes('jewelry:influencer:edit'))
const canPrice = computed(() => userStore.permissions?.includes('*:*:*') || userStore.permissions?.includes('jewelry:influencer:price'))
const rows=ref([]),total=ref(0),loading=ref(false),profileDialog=ref(false),bindingDialog=ref(false),bundleDialog=ref(false),excelDialog=ref(false),saving=ref(false)
const profileRef=ref(),activeTab=ref('basic'),platforms=ref([]),products=ref([]),bindings=ref([]),bundles=ref([]),history=ref([]),soldBundles=ref([]),excelRows=ref([])
const query=reactive({pageNum:1,pageSize:10,keyword:'',priceStatus:''})
const blankProfile=()=>({influencerId:null,influencerCode:'',platformCode:'',externalInfluencerId:'',influencerName:'',platform:'',platformAccount:'',salesChannel:'',contactPhone:'',status:'0',remark:''})
const profile=reactive(blankProfile())
const blankBinding=()=>({productId:null,editing:false,fixedUnitPrice:null,commissionPercent:0,platformPercent:0,taxPercent:0,packFee:0,shipFee:0,certFee:0,bindingStatus:'0',bindingRemark:''})
const binding=reactive(blankBinding())
const blankBundle=()=>({mainProductId:null,addonProductId:null,mainQty:1,addonQty:1,pricingMode:'INCLUDED'})
const bundle=reactive(blankBundle())
const profileRules={influencerName:[{required:true,message:translateText('请输入达人/主播名称')}],platformCode:[{required:true,message:translateText('请选择平台')}]}
const usableBinding=productId=>bindings.value.some(b=>Number(b.productId)===Number(productId) && b.priceStatus==='PRICED' && b.bindingStatus==='0' && b.fixedUnitPrice!=null && b.commissionRate!=null && b.platformRate!=null && b.taxRate!=null)
const bindingProducts=computed(()=>products.value.filter(p=>p.productType==='FINISHED'))
const mainProducts=computed(()=>products.value.filter(p=>p.productType==='FINISHED' && usableBinding(p.productId)))
const addonProducts=computed(()=>products.value.filter(p=>p.productType==='ACCESSORY' && Number(p.totalStockQty||0)>0))
const typeName=t=>jewelryProductType(t)?.label||t||'—'
const money=n=>Number(n||0).toFixed(4)
const percent=n=>Number((Number(n||0)*100).toFixed(4))
const sourceName=t=>({FIRST_SALE:translateText('首笔销售'),ADMIN_CHANGE:translateText('管理员改价'),PROFILE_BINDING:translateText('档案绑定'),PROFILE_UPDATE:translateText('档案更新')}[t]||t||'—')
async function load(){loading.value=true;try{const r=await listJewelryInfluencers(query);rows.value=r.rows||[];total.value=r.total||0}finally{loading.value=false}}
function onPlatformChange(code){const p=platforms.value.find(x=>x.platformCode===code);profile.platform=p?.platformName||'';if(!profile.salesChannel)profile.salesChannel=profile.platform}
async function refreshDetails(){if(!profile.influencerId)return;const id=profile.influencerId;const [b,c,h,s]=await Promise.all([getJewelryInfluencerProductPrices(id),getJewelryInfluencerBundleConfigs(id),getJewelryInfluencerPriceHistory(id),getJewelryInfluencerBundleItems(id)]);bindings.value=b.data||[];bundles.value=c.data||[];history.value=h.data||[];soldBundles.value=s.data||[]}
async function openProfile(row){Object.assign(profile,blankProfile(),row||{});activeTab.value=row&&!canEditProfile.value&&canPrice.value?'bindings':'basic';profileDialog.value=true;const [p,g]=await Promise.all([listJewelryInfluencerPlatforms(),listJewelryProductOptions({status:'0'})]);platforms.value=p.data||[];products.value=g.data||[];bindings.value=[];bundles.value=[];history.value=[];soldBundles.value=[];if(row)await refreshDetails()}
async function saveProfile(){await profileRef.value.validate();await saveJewelryInfluencer({...profile});proxy.$modal.msgSuccess(translateText('保存成功'));profileDialog.value=false;load()}
function openBinding(row){Object.assign(binding,blankBinding());if(row)Object.assign(binding,{...row,editing:true,commissionPercent:percent(row.commissionRate),platformPercent:percent(row.platformRate),taxPercent:percent(row.taxRate),fixedUnitPrice:Number(row.fixedUnitPrice),packFee:Number(row.packFee||0),shipFee:Number(row.shipFee||0),certFee:Number(row.certFee||0)});bindingDialog.value=true}
async function saveBinding(){if(!binding.productId||Number(binding.fixedUnitPrice)<=0)return proxy.$modal.msgError(translateText('请选择成品商品并填写大于0的直播价'));if(!bindingProducts.value.some(p=>Number(p.productId)===Number(binding.productId)))return proxy.$modal.msgError(translateText('达人只能绑定成品商品'));if(Number(binding.commissionPercent)+Number(binding.platformPercent)+Number(binding.taxPercent)>=100)return proxy.$modal.msgError(translateText('佣金、平台扣点和税率之和必须小于100%'));saving.value=true;try{await saveJewelryInfluencerBindings(profile.influencerId,[{...binding}]);proxy.$modal.msgSuccess(translateText('商品绑定已保存'));bindingDialog.value=false;await refreshDetails();load()}finally{saving.value=false}}
async function openBundle(){const r=await listJewelryProductOptions({status:'0'});products.value=r.data||[];Object.assign(bundle,blankBundle());bundleDialog.value=true}
async function saveBundle(){if(!bundle.mainProductId||!bundle.addonProductId)return proxy.$modal.msgError(translateText('请选择主商品和搭售商品'));if(!addonProducts.value.some(p=>Number(p.productId)===Number(bundle.addonProductId)))return proxy.$modal.msgError(translateText('搭售商品必须是当前已在库的配件商品'));saving.value=true;try{await saveJewelryInfluencerBundleConfig(profile.influencerId,{...bundle});proxy.$modal.msgSuccess(translateText('搭售配置已保存'));bundleDialog.value=false;await refreshDetails()}finally{saving.value=false}}
async function removeBundle(row){await proxy.$modal.confirm(translateText('确定删除这条搭售配置吗？'));await deleteJewelryInfluencerBundleConfig(profile.influencerId,row.configId);await refreshDetails()}
async function downloadTemplate(){const blob=await request({url:'/jewelry/influencer/bindings/template',method:'get',responseType:'blob'});saveAs(blob,`${translateText('达人商品绑定模板')}.xlsx`)}
async function previewExcel(upload){const r=await previewJewelryInfluencerBindings(profile.influencerId,upload.raw);excelRows.value=r.data||[];excelDialog.value=true}
async function confirmExcel(draftRows){saving.value=true;try{const r=await confirmJewelryInfluencerBindings(profile.influencerId,draftRows);if(!r.data?.saved){excelRows.value=r.data?.rows||[];proxy.$modal.msgWarning(translateText('仍有错误，请根据行内提示修改后再次提交'));return}proxy.$modal.msgSuccess(translateText('成功导入 {0} 行', [r.data.count]));excelDialog.value=false;await refreshDetails();load()}finally{saving.value=false}}
load()
</script>
<style scoped>
.profile-form { max-width: 640px; }
.tab-actions { margin: 12px 0; padding-left: 125px; }
.toolbar { display:flex; align-items:center; gap:10px; margin: 12px 0; }
.binding-form { display:grid; grid-template-columns: 1fr 1fr; column-gap:16px; }
.binding-form .el-form-item:first-child, .binding-form .el-form-item:last-child { grid-column: 1 / -1; }
.mb12 { margin-bottom:12px; }
</style>
