<template>
  <div class="proposal-page">
    <header class="page-head">
      <div><span class="eyebrow">PROJECT APPLICATION</span><h1>立项申请</h1><p>按项目模板明确目标、人员计划和交付标准，自主启动或提交审批。</p></div>
      <el-button v-hasPermi="['business:project:proposal:add']" type="primary" icon="Plus" @click="openForm()">新建立项申请</el-button>
    </header>

    <el-alert title="按模板办理立项" description="轻量协作与持续服务由负责人自主启动；受控交付提交归属老板审批。新模板无需个人薪资、奖金或强制预算，历史申请继续原策略。" type="success" :closable="false" show-icon />

    <el-tabs v-model="activeTab" class="proposal-tabs" @tab-change="loadActive">
      <el-tab-pane label="我的申请" name="mine">
        <el-card shadow="never">
          <el-table :data="mineRows" v-loading="loading" empty-text="还没有立项申请" @row-click="openDetail">
            <el-table-column label="申请" min-width="230"><template #default="{row}"><b>{{ row.projectName }}</b><small>{{ row.proposalNo }}</small></template></el-table-column>
            <el-table-column prop="sponsorOwnerName" label="归属老板" width="140" />
            <el-table-column prop="companyName" label="归属公司" min-width="150" />
            <el-table-column label="治理方式" min-width="170"><template #default="{row}"><b>{{ managementLabel[row.managementMode] || row.managementMode }}</b><small>{{ closeMethodLabel[row.closeMethod] || row.closeMethod }}</small></template></el-table-column>
            <el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusTone[row.status] || 'info'">{{ statusLabel[row.status] || row.status }}</el-tag></template></el-table-column>
            <el-table-column label="计划周期" width="210"><template #default="{row}">{{ planPeriod(row) }}</template></el-table-column>
            <el-table-column label="操作" width="235" fixed="right"><template #default="{row}"><div class="row-actions" @click.stop>
              <el-button v-if="row.canEdit" link type="primary" @click="openForm(row)">编辑</el-button>
              <el-button v-if="row.canEdit" link type="success" @click="submitRow(row)">{{ launchLabel(row) }}</el-button>
              <el-button v-if="row.status==='PENDING'" link type="warning" @click="withdrawRow(row)">撤回</el-button>
              <el-button v-if="row.status==='APPROVED'&&row.createdProjectId" link @click="openProject(row)">查看项目</el-button>
            </div></template></el-table-column>
          </el-table>
        </el-card>
      </el-tab-pane>

      <el-tab-pane v-if="canReview && reviewRows.length" :label="`待审批 (${reviewRows.length})`" name="review">
        <el-card shadow="never">
          <el-alert title="这里处理受控交付模板和历史遗留待审批记录；只有实际归属审批人可以批准新受控项目。" type="warning" :closable="false" show-icon style="margin-bottom:12px" />
          <el-table :data="reviewRows" v-loading="loading" empty-text="没有待审批记录" @row-click="openDetail">
            <el-table-column label="项目" min-width="230"><template #default="{row}"><b>{{ row.projectName }}</b><small>{{ row.proposalNo }}</small></template></el-table-column>
            <el-table-column prop="applicantName" label="申请人/负责人" width="145" />
            <el-table-column prop="companyName" label="归属公司" min-width="150" />
            <el-table-column label="治理方式" min-width="170"><template #default="{row}"><b>{{ managementLabel[row.managementMode] || row.managementMode }}</b><small>{{ closeMethodLabel[row.closeMethod] || row.closeMethod }}</small></template></el-table-column>
            <el-table-column label="预算" width="140"><template #default="{row}">{{ row.noBudget==='1' ? '不设置预算' : money(row.budgetLimit,row.baseCurrency) }}</template></el-table-column>
            <el-table-column label="计划周期" width="210"><template #default="{row}">{{ planPeriod(row) }}</template></el-table-column>
            <el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><div class="row-actions" @click.stop><el-button v-if="row.canReview" link type="success" @click="reviewRow(row,'APPROVED')">批准</el-button><el-button v-if="row.canReview" link type="warning" @click="reviewRow(row,'RETURNED')">退回</el-button><el-button link @click="openDetail(row)">详情</el-button></div></template></el-table-column>
          </el-table>
        </el-card>
      </el-tab-pane>

      <el-tab-pane v-if="canReview" label="全部立项申请" name="directory">
        <el-card shadow="never"><el-table :data="directoryRows" v-loading="loading" empty-text="暂无立项申请"><el-table-column prop="projectName" label="项目名称" min-width="230"/><el-table-column prop="applicantName" label="申请人/负责人" width="150"/><el-table-column prop="sponsorOwnerName" label="归属老板" width="150"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="statusTone[row.status] || 'info'">{{ statusLabel[row.status] || row.status }}</el-tag></template></el-table-column><el-table-column label="权限" width="120"><template #default="{row}"><span class="muted">仅目录可见</span></template></el-table-column></el-table></el-card>
      </el-tab-pane>
    </el-tabs>

    <el-dialog v-model="formVisible" :title="form.proposalId ? '修改立项申请' : '新建立项申请'" width="min(1180px,97vw)" append-to-body>
      <el-form ref="formRef" :model="form" :rules="rules" label-width="112px">
        <el-alert v-if="!isNewTemplate" title="历史申请保留原启动及成本规则，不能通过修改模板改变在办单据语义。" type="warning" :closable="false" show-icon />
        <el-row :gutter="16">
          <el-col :span="24"><el-form-item label="项目模板"><el-select v-if="isNewTemplate" v-model="form.templateVersion" style="width:100%" @change="templateChanged"><el-option v-for="item in options.templates || []" :key="item.templateVersion" :label="`${item.templateName} · ${item.authorizationMode==='MANUAL_APPROVAL'?'归属老板审批':'自主启动'}`" :value="item.templateVersion" /></el-select><el-tag v-else>历史版本 LEGACY_V1</el-tag><small class="field-help">{{ templateHint }}</small></el-form-item></el-col>
          <el-col :span="12"><el-form-item label="申请人/负责人"><el-input :model-value="userStore.nickName || userStore.name" disabled /></el-form-item></el-col>
          <el-col :span="12"><el-form-item label="归属老板" prop="sponsorOwnerUserId"><el-select v-model="form.sponsorOwnerUserId" style="width:100%" placeholder="选择项目归属老板"><el-option v-for="item in options.bosses" :key="item.userId" :label="bossOptionLabel(item)" :value="item.userId" /></el-select><small class="field-help">{{ isControlled(form) ? '该模板须由另一位归属老板审批后启动。' : '用于归属、异常提醒、治理及后续结算责任。' }}</small></el-form-item></el-col>
          <el-col :span="12"><el-form-item label="项目名称" prop="projectName"><el-input v-model="form.projectName" maxlength="160" show-word-limit /></el-form-item></el-col>
          <el-col :span="12"><el-form-item label="归属公司" prop="companyDeptId"><el-select v-model="form.companyDeptId" style="width:100%" placeholder="请选择归属公司" @change="refreshStaffOptions"><el-option v-for="item in options.companies" :key="item.deptId" :label="item.deptName" :value="item.deptId" /></el-select></el-form-item></el-col>
          <el-col :span="8"><el-form-item label="项目类型"><el-select v-model="form.projectType" style="width:100%"><el-option v-for="(label,value) in typeLabel" :key="value" :label="label" :value="value" /></el-select></el-form-item></el-col>
          <el-col :span="8"><el-form-item label="核算方式"><el-select v-model="form.accountingMode" style="width:100%"><el-option v-for="(item,value) in accountingOptions" :key="value" :label="`${item.label}（${item.description}）`" :value="value" /></el-select></el-form-item></el-col>
          <el-col :span="8"><el-form-item label="管理模式"><el-select v-model="form.managementMode" :disabled="isNewTemplate" style="width:100%"><el-option v-for="(item,value) in managementOptions" :key="value" :label="item.label" :value="value" /></el-select></el-form-item></el-col>
          <el-col :span="24"><el-alert class="governance-tip" :title="managementOptions[form.managementMode]?.title" :description="managementOptions[form.managementMode]?.description" type="info" :closable="false" show-icon /></el-col>
          <el-col :span="12"><el-form-item label="结项方式"><el-select v-model="form.closeMethod" :disabled="isNewTemplate" style="width:100%"><el-option v-for="(item,value) in closeMethodOptions" :key="value" :label="item.label" :value="value" /></el-select><small class="field-help">{{ closeMethodOptions[form.closeMethod]?.description }}</small></el-form-item></el-col>
          <el-col v-if="form.managementMode==='KEY_CONTROL'" :span="12"><el-form-item label="监管原因"><el-input v-model="form.managementReason" type="textarea" :rows="2" maxlength="1000" show-word-limit placeholder="说明为何需要重点监管及主要监管事项" /></el-form-item></el-col>
          <el-col v-if="isNewTemplate || form.closeMethod!=='DIRECT'" :span="24"><el-form-item label="成果与验收" :required="isNewTemplate"><el-input v-model="form.acceptanceCriteria" type="textarea" :rows="3" maxlength="2000" show-word-limit placeholder="列明验收指标、成果清单、通过条件和验收人" /></el-form-item></el-col>
          <el-col :span="24"><el-form-item label="项目目标" prop="objective"><el-input v-model="form.objective" type="textarea" :rows="3" maxlength="1000" show-word-limit placeholder="说明要解决的问题和可验收结果" /></el-form-item></el-col>
          <el-col :span="24"><el-form-item label="立项理由" prop="applicationReason"><el-input v-model="form.applicationReason" type="textarea" :rows="3" maxlength="2000" show-word-limit placeholder="说明现状/问题与机会是什么" /></el-form-item></el-col>
          <el-col :span="16"><el-form-item label="计划周期" required><div class="plan-period-line"><el-date-picker v-model="form.planStartDate" type="date" value-format="YYYY-MM-DD" placeholder="开始日期" style="width:100%" @change="refreshStaffOptions" /><span>至</span><el-date-picker v-model="form.planEndDate" type="date" value-format="YYYY-MM-DD" :disabled="openEnded" :disabled-date="disablePlanEndDate" :placeholder="openEnded ? '不限期' : '结束日期'" style="width:100%" @change="recomputeAllStaffCosts" /><el-checkbox v-if="!isNewTemplate" v-model="openEnded" @change="handleOpenEndedChange">不限期</el-checkbox></div></el-form-item></el-col>
          <el-col :span="8"><el-form-item label="优先级"><el-select v-model="form.priority" style="width:100%"><el-option label="低" value="LOW"/><el-option label="中" value="MEDIUM"/><el-option label="高" value="HIGH"/></el-select></el-form-item></el-col>
          <el-col :span="24"><el-form-item label="预算上限" :required="!isNewTemplate"><div class="budget-line"><el-input-number v-model="form.budgetLimit" :disabled="isNewTemplate && noBudget" :min="0" :precision="2" controls-position="right"/><el-select v-model="form.baseCurrency" style="width:110px"><el-option label="CNY" value="CNY"/><el-option label="VND" value="VND"/><el-option label="USD" value="USD"/></el-select><el-checkbox v-if="isNewTemplate" v-model="noBudget" @change="value=>{if(value)form.budgetLimit=null}">不设置预算</el-checkbox><small class="field-help">{{ isNewTemplate ? '预算选填；填写时不能低于已估算外部支出。人员成本按确认投入另行计价。' : '历史规则：预算不能低于后台核对的预计总成本。' }}</small></div></el-form-item></el-col>

          <el-col :span="24"><div class="plan-section"><div class="plan-section-head"><div><h3>收入测算</h3><p>{{ isNewTemplate ? '收入测算可选，用于记录预期和假设。' : '盈利型和混合型项目至少填写一项正常预测。' }}</p></div><el-button size="small" type="primary" plain @click="addRevenue">增加收入</el-button></div><el-table :data="form.revenueLines" size="small" empty-text="成本型或价值型项目可以不填直接收入"><el-table-column label="场景" width="120"><template #default="{row}"><el-select v-model="row.scenario"><el-option label="保守" value="CONSERVATIVE"/><el-option label="正常" value="BASE"/><el-option label="乐观" value="OPTIMISTIC"/></el-select></template></el-table-column><el-table-column label="收入方式" width="145"><template #default="{row}"><el-select v-model="row.revenueType"><el-option v-for="(label,value) in revenueTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="收入项目" min-width="150"><template #default="{row}"><el-input v-model="row.itemName" placeholder="商品或服务"/></template></el-table-column><el-table-column label="预计金额" width="165"><template #default="{row}"><el-input-number v-model="row.expectedAmount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="预计回款" width="145"><template #default="{row}"><el-date-picker v-model="row.expectedDate" value-format="YYYY-MM-DD" style="width:100%"/></template></el-table-column><el-table-column label="依据" min-width="170"><template #default="{row}"><el-input v-model="row.assumptionText" placeholder="单价、数量、转化率等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.revenueLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></el-col>

          <el-col :span="24"><div class="plan-section"><div class="plan-section-head"><div><h3>支出计划</h3><p>逐笔说明花在哪里，不能只写一个预算总额。</p></div><el-button size="small" type="primary" plain @click="addExpense">增加支出</el-button></div><el-table :data="form.expenseLines" size="small" empty-text="暂无外部支出"><el-table-column label="类别" width="145"><template #default="{row}"><el-select v-model="row.expenseCategory"><el-option v-for="(label,value) in expenseCategoryLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="支出项目" min-width="150"><template #default="{row}"><el-input v-model="row.itemName"/></template></el-table-column><el-table-column label="具体用途" min-width="190"><template #default="{row}"><el-input v-model="row.purpose"/></template></el-table-column><el-table-column label="金额" width="165"><template #default="{row}"><el-input-number v-model="row.amount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="发生时间" width="145"><template #default="{row}"><el-date-picker v-model="row.occurDate" value-format="YYYY-MM-DD" style="width:100%"/></template></el-table-column><el-table-column label="收款方" min-width="130"><template #default="{row}"><el-input v-model="row.counterparty"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.expenseLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></el-col>

          <el-col :span="24"><div class="plan-section"><div class="plan-section-head"><div><h3>人员计划</h3><p>{{ isNewTemplate ? '每人独立填写参与日期和计划工作量。日历决定可用容量，单位政策独立定义一人天；计划不代表实际投入或薪资成本。人员可在启动后继续安排。' : '历史申请保留原成本快照，保存时由后台按原规则核对；人员选择不展示其他人的内部费率。' }}</p></div><el-button size="small" type="primary" plain :disabled="isNewTemplate && (!form.companyDeptId || !form.planStartDate || !form.planEndDate)" @click="addStaffing">增加人员</el-button></div>
            <el-table :data="form.staffingLines" size="small" empty-text="暂无人员计划，可在项目启动后安排">
              <el-table-column label="人员" min-width="210"><template #default="{row}"><el-select v-model="row.userId" filterable style="width:100%" placeholder="选择人员" @change="staffChanged(row)"><el-option v-for="item in options.staff" :key="item.userId" :label="staffOptionLabel(item)" :value="item.userId" :disabled="staffAlreadySelected(item.userId,row)" /></el-select></template></el-table-column>
              <el-table-column label="岗位/角色" min-width="125"><template #default="{row}">{{ row.roleName || '—' }}</template></el-table-column>
              <template v-if="isNewTemplate">
                <el-table-column label="参与开始" min-width="150"><template #default="{row}"><el-date-picker v-model="row.planStartDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></template></el-table-column>
                <el-table-column label="参与结束" min-width="150"><template #default="{row}"><el-date-picker v-model="row.planEndDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></template></el-table-column>
                <el-table-column label="计划工作量" min-width="145"><template #default="{row}"><el-input-number v-model="row.inputQuantity" :min="0.0001" :max="row.inputUnit==='PERCENTAGE'?100:9999999" :precision="4" /></template></el-table-column>
                <el-table-column label="单位" min-width="145"><template #default="{row}"><el-select v-model="row.inputUnit"><el-option v-for="(label,value) in inputUnitLabel" :key="value" :label="label" :value="value" /></el-select></template></el-table-column>
                <el-table-column label="工作日历" min-width="220"><template #default="{row}"><el-select v-model="row.calendarId" filterable><el-option v-for="item in calendarChoices(row)" :key="item.calendarId" :value="item.calendarId" :label="`${item.calendarName} · 日容量 ${Number(item.dailyMinutes)/60} 小时 · v${item.version}`" /></el-select></template></el-table-column>
                <el-table-column label="人天单位政策" min-width="240"><template #default="{row}"><el-select v-model="row.unitPolicyId" filterable><el-option v-for="item in unitChoices(row)" :key="item.unitPolicyId" :value="item.unitPolicyId" :label="`${item.policyName} · 1人天=${Number(item.minutesPerDay)/60}小时 · v${item.version}`" /></el-select></template></el-table-column>
              </template>
              <el-table-column v-else label="历史预计成本" min-width="175"><template #default="{row}">{{ row.estimatedCost==null?'由后台核对':money(row.estimatedCost,row.costCurrency||form.baseCurrency) }}</template></el-table-column>
              <el-table-column label="说明" min-width="150"><template #default="{row}"><el-input v-model="row.note" placeholder="可选" /></template></el-table-column>
              <el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.staffingLines.splice($index,1)">删</el-button></template></el-table-column>
            </el-table></div></el-col>

          <el-col :span="24"><div class="plan-section"><div class="plan-section-head"><div><h3>量化目标</h3><p>{{ isNewTemplate ? '量化指标可选；成果与验收标准仍需明确。' : '至少设置一项结果、财务、进度、质量或价值目标。' }}</p></div><el-button size="small" type="primary" plain @click="addTarget">增加目标</el-button></div><el-table :data="form.targetLines" size="small"><el-table-column label="类型" width="125"><template #default="{row}"><el-select v-model="row.targetType"><el-option v-for="(label,value) in targetTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="目标名称" min-width="180"><template #default="{row}"><el-input v-model="row.targetName"/></template></el-table-column><el-table-column label="目标值" width="145"><template #default="{row}"><el-input-number v-model="row.targetValue" :min="0" :precision="2"/></template></el-table-column><el-table-column label="单位" width="110"><template #default="{row}"><el-input v-model="row.unit" placeholder="元、件、%"/></template></el-table-column><el-table-column label="完成日期" width="145"><template #default="{row}"><el-date-picker v-model="row.dueDate" value-format="YYYY-MM-DD" style="width:100%"/></template></el-table-column><el-table-column label="验收依据" min-width="210"><template #default="{row}"><el-input v-model="row.acceptanceEvidence" placeholder="报表、合同、交付文件等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.targetLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></el-col>

          <el-col v-if="isNewTemplate && form.staffingLines?.length" :span="24"><el-alert title="人员计划尚未形成实际成本，下方相关合计显示未知；未计价不代表零成本。" type="info" :closable="false" show-icon /></el-col>
          <el-col :span="24"><el-alert v-if="isNewTemplate" title="此处仅汇总收入与外部支出估算。人员成本按实际投入另行计价，当前不形成总成本或利润结论。" type="info" :closable="false" show-icon /><div class="finance-summary"><div><span>预计收入</span><b>{{ money(planSummary.revenue,form.baseCurrency) }}</b></div><div><span>外部支出</span><b>{{ money(planSummary.external,form.baseCurrency) }}</b></div><div><span>人员成本</span><b>{{ isNewTemplate ? '待实际计价' : money(planSummary.personnel,form.baseCurrency) }}</b></div><template v-if="!isNewTemplate"><div><span>预计总成本</span><b>{{ money(planSummary.total,form.baseCurrency) }}</b></div><div><span>预计利润</span><b :class="planSummary.profit<0?'danger-text':'success-text'">{{ money(planSummary.profit,form.baseCurrency) }}</b></div><div><span>利润率</span><b>{{ planSummary.margin===null?'—':`${planSummary.margin.toFixed(2)}%` }}</b></div></template></div></el-col>
          <el-col :span="24"><el-form-item label="主要风险" :required="!isNewTemplate"><el-input v-model="form.riskSummary" type="textarea" :rows="2" maxlength="2000" show-word-limit placeholder="列出最可能影响收入、成本和进度的风险"/></el-form-item></el-col>
        </el-row>
      </el-form>
      <template #footer><el-button @click="formVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveForm">保存立项申请</el-button></template>
    </el-dialog>

    <el-drawer v-model="detailVisible" size="min(720px,94vw)" append-to-body>
      <template #header><div><span class="eyebrow">{{ detail.proposalNo }}</span><h2>{{ detail.projectName }}</h2></div></template>
      <div class="detail-grid"><div><span>项目模板</span><b>{{ options.templates.find(t=>t.templateVersion===detail.templateVersion)?.templateName || detail.templateVersion || '历史版本 LEGACY_V1' }}</b></div><div><span>项目负责人</span><b>{{ detail.applicantName }}</b></div><div><span>观察老板</span><b>{{ detail.sponsorOwnerName }}</b></div><div><span>管理模式</span><b>{{ managementLabel[detail.managementMode] || detail.managementMode }}</b></div><div><span>结项方式</span><b>{{ closeMethodLabel[detail.closeMethod] || detail.closeMethod }}</b></div><div><span>计划周期</span><b>{{ planPeriod(detail) }}</b></div><div><span>预算上限</span><b>{{ money(detail.budgetLimit,detail.baseCurrency) }}</b></div></div>
      <section class="detail-section"><h3>经营测算</h3><div class="finance-summary compact"><div><span>预计收入</span><b>{{ money(detail.estimatedRevenue,detail.baseCurrency) }}</b></div><div><span>外部支出</span><b>{{ money(detail.estimatedExternalCost,detail.baseCurrency) }}</b></div><div><span>人员成本</span><b>{{ newTemplate(detail) ? '待实际计价' : money(detail.estimatedPersonnelCost,detail.baseCurrency) }}</b></div><template v-if="!newTemplate(detail)"><div><span>预计总成本</span><b>{{ money(detail.estimatedTotalCost,detail.baseCurrency) }}</b></div><div><span>预计利润</span><b>{{ money(detail.expectedProfit,detail.baseCurrency) }}</b></div></template><div><span>计划人数</span><b>{{ detail.plannedHeadcount || 0 }} 人</b></div></div></section>
      <section v-if="detail.revenueLines?.length" class="detail-section"><h3>收入测算明细</h3><el-table :data="detail.revenueLines" size="small"><el-table-column label="场景"><template #default="{row}">{{ scenarioLabel[row.scenario] }}</template></el-table-column><el-table-column prop="itemName" label="收入项目"/><el-table-column label="预计金额"><template #default="{row}">{{ money(row.expectedAmount,detail.baseCurrency) }}</template></el-table-column><el-table-column prop="assumptionText" label="测算依据"/></el-table></section>
      <section v-if="detail.expenseLines?.length" class="detail-section"><h3>支出计划明细</h3><el-table :data="detail.expenseLines" size="small"><el-table-column prop="itemName" label="支出项目"/><el-table-column prop="purpose" label="具体用途"/><el-table-column label="金额"><template #default="{row}">{{ money(row.amount,detail.baseCurrency) }}</template></el-table-column><el-table-column prop="counterparty" label="收款方"/></el-table></section>
      <section v-if="detail.staffingLines?.length" class="detail-section"><h3>人员计划</h3><el-table :data="detail.staffingLines" size="small"><el-table-column label="人员"><template #default="{row}">{{ row.userName || '历史岗位汇总' }}</template></el-table-column><el-table-column prop="roleName" label="岗位"/><template v-if="newTemplate(detail)"><el-table-column label="参与区间"><template #default="{row}">{{ shortDate(row.planStartDate) }} 至 {{ shortDate(row.planEndDate) }}</template></el-table-column><el-table-column label="计划工作量"><template #default="{row}">{{ row.inputQuantity }} {{ inputUnitLabel[row.inputUnit] }}</template></el-table-column></template><el-table-column v-else label="历史预计成本"><template #default="{row}">{{ money(row.estimatedCost,row.costCurrency||detail.baseCurrency) }}</template></el-table-column></el-table><p v-if="newTemplate(detail)">计划不作为已确认实际投入，人员成本在项目执行后独立计价。</p></section>
      <section v-if="detail.targetLines?.length" class="detail-section"><h3>量化目标</h3><el-table :data="detail.targetLines" size="small"><el-table-column prop="targetName" label="目标"/><el-table-column label="目标值"><template #default="{row}">{{ row.targetValue }} {{ row.unit }}</template></el-table-column><el-table-column prop="dueDate" label="完成日期"/><el-table-column prop="acceptanceEvidence" label="验收依据"/></el-table></section>
      <section class="detail-section"><h3>项目目标</h3><p>{{ detail.objective }}</p></section><section class="detail-section"><h3>立项理由</h3><p>{{ detail.applicationReason }}</p></section><section v-if="detail.managementReason" class="detail-section"><h3>重点监管原因</h3><p>{{ detail.managementReason }}</p></section><section v-if="detail.acceptanceCriteria" class="detail-section"><h3>验收标准</h3><p>{{ detail.acceptanceCriteria }}</p></section><section v-if="detail.reviewComment" class="detail-section review-comment"><h3>审批/撤回意见</h3><p>{{ detail.reviewComment }}</p></section>
      <section class="detail-section"><h3>操作记录</h3><el-timeline><el-timeline-item v-for="event in detail.events || []" :key="event.eventId" :timestamp="event.createTime"><b>{{ eventLabel[event.eventType] || event.eventType }}</b><p>{{ event.operatorName }}<span v-if="event.comment"> · {{ event.comment }}</span></p></el-timeline-item></el-timeline></section>
      <div class="drawer-actions"><el-button v-if="detail.canEdit" type="primary" @click="openForm(detail)">修改</el-button><el-button v-if="detail.canEdit" type="success" @click="submitRow(detail)">{{ launchLabel(detail) }}</el-button><el-button v-if="detail.canReview" type="success" @click="reviewRow(detail,'APPROVED')">审批立项</el-button><el-button v-if="detail.canReview" type="warning" @click="reviewRow(detail,'RETURNED')">退回修改</el-button><el-button v-if="detail.status==='APPROVED'&&detail.createdProjectId" @click="openProject(detail)">查看正式项目</el-button></div>
    </el-drawer>
  </div>
</template>

<script setup name="BusinessProjectProposals">
import { ElMessage, ElMessageBox } from 'element-plus'
import useUserStore from '@/store/modules/user'
import { listProjectProposals, listProposalReviews, listProposalDirectory, getProjectProposal, getProjectProposalOptions, getProjectProposalStaffOptions, addProjectProposal, updateProjectProposal, submitProjectProposal, withdrawProjectProposal, reviewProjectProposal } from '@/api/business/proposal'
import { useBusinessRefreshOnReactivated } from '@/utils/businessRefresh'

const route=useRoute(),router=useRouter(), userStore=useUserStore(), loading=ref(false), saving=ref(false), activeTab=ref('mine')
const mineRows=ref([]),reviewRows=ref([]),directoryRows=ref([]),options=reactive({bosses:[],companies:[],staff:[],templates:[],calendars:[],unitPolicies:[]})
const formVisible=ref(false),detailVisible=ref(false),formRef=ref(),detail=ref({}),noBudget=ref(false),openEnded=ref(false)
const form=ref({})
const canReview=computed(()=>userStore.roles.includes('admin')||userStore.permissions.includes('*:*:*')||userStore.permissions.includes('business:project:proposal:review'))
const statusLabel={DRAFT:'草稿',PENDING:'待审批',RETURNED:'已退回',WITHDRAWN:'已撤回',APPROVED:'已批准'}
const statusTone={DRAFT:'info',PENDING:'warning',RETURNED:'danger',WITHDRAWN:'info',APPROVED:'success'}
const typeLabel={GENERAL:'通用',LIVE:'直播',JEWELRY:'珠宝',ECOMMERCE:'电商',OPERATIONS:'运营',INTERNAL:'内部',OTHER:'其他'}
const accountingOptions={PROFIT:{label:'盈利型',description:'看收入、成本和赚了多少'},COST:{label:'成本型',description:'看花了多少，有没有超预算'},VALUE:{label:'价值型',description:'看投入多少，目标有没有完成'},HYBRID:{label:'混合型',description:'既看赚了多少，也看目标完成情况'}}
const accountingLabel=Object.fromEntries(Object.entries(accountingOptions).map(([key,item])=>[key,item.label]))
const revenueTypeLabel={SALES:'商品销售',SERVICE:'服务费',COMMISSION:'佣金',ADVERTISING:'广告',SUBSCRIPTION:'订阅',LIVE:'直播收入',SAVING:'成本节约',OTHER:'其他'}
const expenseCategoryLabel={PROCUREMENT:'采购',MARKETING:'推广',PLATFORM:'平台服务',TRAVEL:'差旅',OUTSOURCING:'外包',EQUIPMENT:'设备',LOGISTICS:'物流',OTHER:'其他'}
const targetTypeLabel={FINANCIAL:'财务',RESULT:'结果',SCHEDULE:'进度',QUALITY:'质量',VALUE:'价值'}
const scenarioLabel={CONSERVATIVE:'保守',BASE:'正常',OPTIMISTIC:'乐观'}
const managementOptions={LIGHT:{label:'轻量',title:'轻量管理：保留核心执行闭环',description:'适合周期短、范围清晰、风险较低的项目；保留任务、工时、成本和KPI，风险按异常登记。'},STANDARD:{label:'标准',title:'标准管理：完整的常规项目过程',description:'启用周度跟踪、里程碑、风险台账和预算预警，适合多数跨成员项目。'},KEY_CONTROL:{label:'重点监管',title:'重点监管：高风险或公司级项目',description:'强化里程碑、风险、预算分级预警和治理变更审批，立项时必须说明监管原因。'}}
const managementLabel={LIGHT:'轻量',STANDARD:'标准',KEY_CONTROL:'重点监管',SIMPLE:'轻量',DELIVERY:'标准'}
const closeMethodOptions={DIRECT:{label:'直接结项',description:'负责人提交结项申请，由老板检验通过后关闭项目。'},RESULT_ACCEPTANCE:{label:'成果验收',description:'负责人提交交付资料，由老板验收通过后关闭项目。'},STAGED_ACCEPTANCE:{label:'阶段验收',description:'负责人逐里程碑提交成果，均由老板验收；全部通过后再申请结项。'}}
const closeMethodLabel=Object.fromEntries(Object.entries(closeMethodOptions).map(([key,item])=>[key,item.label]))
const eventLabel={SELF_AUTHORIZED:'按模板自主启动',CREATE:'创建草稿',EDIT:'修改草稿',SUBMIT:'提交审批',RESUBMIT:'重新提交',WITHDRAW:'撤回申请',RETURN:'退回修改',APPROVE:'批准立项',OWNER_LAUNCH:'负责人启动项目'}
const rules={projectName:[{required:true,message:'请输入项目名称',trigger:'blur'}],sponsorOwnerUserId:[{required:true,message:'请选择观察老板',trigger:'change'}],companyDeptId:[{required:true,message:'请选择归属公司',trigger:'change'}],objective:[{required:true,message:'请填写项目目标',trigger:'blur'}],applicationReason:[{required:true,message:'请填写立项理由',trigger:'blur'}]}

const emptyStaffing=()=>({planStartDate:form.value.planStartDate||null,planEndDate:form.value.planEndDate||null,inputUnit:'DAY',inputQuantity:1,calendarId:defaultCalendar(),unitPolicyId:defaultUnitPolicy(),userId:null,userName:'',roleName:'',costPolicyId:null,costPolicyVersion:null,monthlyCostSnapshot:null,standardWorkDaysSnapshot:null,dailyCostSnapshot:null,costCurrency:null,estimatedCost:null,note:''})
const freshForm=()=>({projectName:'',templateVersion:'LIGHT_V1',sponsorOwnerUserId:null,companyDeptId:null,projectType:'GENERAL',accountingMode:'COST',managementMode:'LIGHT',closeMethod:'DIRECT',managementReason:'',acceptanceCriteria:'',objective:'',applicationReason:'',planStartDate:null,planEndDate:null,priority:'MEDIUM',baseCurrency:'CNY',budgetLimit:null,noBudget:'1',revenueModel:'',peakCashNeed:null,riskSummary:'',revenueLines:[],expenseLines:[],staffingLines:[],targetLines:[]})
const isNewTemplate=computed(()=>!!form.value.templateVersion&&form.value.templateVersion!=='LEGACY_V1')
const newTemplate=item=>!!item?.templateVersion&&item.templateVersion!=='LEGACY_V1'
const isControlled=item=>item?.templateVersion==='CONTROLLED_V1'
const launchLabel=item=>isControlled(item)?'提交立项审批':'启动项目'
const templateHint=computed(()=>!isNewTemplate.value?'沿用原规则及存量快照。':isControlled(form.value)?'受控交付：审批后启动，按成果验收完成交付。':form.value.templateVersion==='SERVICE_V1'?'持续服务：自主启动，以有限日期窗口管理本周期成果与复核。':'轻量协作：自主启动，明确目标和交付标准即可；人员计划、预算、项目指标可后续补充。')
const defaultCalendar=()=>options.calendars.find(c=>coversWindow(c,form.value.planStartDate,form.value.planEndDate))?.calendarId??null
const defaultUnitPolicy=()=>options.unitPolicies.find(p=>coversWindow(p,form.value.planStartDate,form.value.planEndDate))?.unitPolicyId??null
const shortDate=value=>value?String(value).slice(0,10):''
const coversWindow=(policy,from,to)=>(!from||!policy.effectiveFrom||shortDate(policy.effectiveFrom)<=shortDate(from))&&(!to||!policy.effectiveTo||shortDate(policy.effectiveTo)>=shortDate(to))
const calendarChoices=row=>options.calendars.filter(c=>coversWindow(c,row.planStartDate,row.planEndDate))
const unitChoices=row=>options.unitPolicies.filter(p=>coversWindow(p,row.planStartDate,row.planEndDate))
const inputUnitLabel={DAY:'人天',HOUR:'小时',PERCENTAGE:'计划容量比例%'}
function templateChanged(){const template=options.templates.find(item=>item.templateVersion===form.value.templateVersion);if(template)Object.assign(form.value,{managementMode:template.managementMode,closeMethod:template.closeMethod});openEnded.value=false}

const number=value=>Number(value)||0
const planSummary=computed(()=>{const revenues=form.value.revenueLines||[],expenses=form.value.expenseLines||[],staffing=form.value.staffingLines||[];const revenue=revenues.filter(row=>row.scenario==='BASE').reduce((sum,row)=>sum+number(row.expectedAmount),0),external=expenses.reduce((sum,row)=>sum+number(row.amount),0),pending=staffing.some(row=>row.estimatedCost==null)||isNewTemplate.value&&staffing.length>0,personnel=pending?null:staffing.reduce((sum,row)=>sum+number(row.estimatedCost),0),total=pending?null:external+personnel,profit=pending?null:revenue-total;return{revenue,external,personnel,total,profit,margin:profit===null||!revenue?null:profit*100/revenue}})
function addRevenue(){form.value.revenueLines.push({scenario:'BASE',revenueType:'SALES',itemName:'',expectedAmount:0,expectedDate:null,assumptionText:''})}
function addExpense(){form.value.expenseLines.push({expenseCategory:'OTHER',itemName:'',purpose:'',counterparty:'',amount:0,occurDate:null,expenseType:'ONE_TIME',hasQuotation:'0'})}
function addStaffing(){form.value.staffingLines.push(emptyStaffing())}
function addTarget(){form.value.targetLines.push({targetType:'RESULT',targetName:'',targetValue:0,unit:'',dueDate:null,acceptanceEvidence:''})}
async function ensureOptions(){if(options.bosses.length&&options.companies.length)return;const res=await getProjectProposalOptions();Object.assign(options,res.data||{})}
function plannedDays(){if(!form.value.planStartDate||openEnded.value||!form.value.planEndDate)return null;const start=new Date(`${form.value.planStartDate}T00:00:00`),end=new Date(`${form.value.planEndDate}T00:00:00`);return Math.max(1,Math.floor((end-start)/86400000)+1)}
function syncStaffRow(row,item){if(!item)return;Object.assign(row,{userId:item.userId,userName:item.nickName||item.accountName,roleName:item.positionName||'项目成员'});if(isNewTemplate.value)Object.assign(row,{costPolicyId:null,costPolicyVersion:null,monthlyCostSnapshot:null,standardWorkDaysSnapshot:null,dailyCostSnapshot:null,costCurrency:null,estimatedCost:null})}
function staffChanged(row){Object.assign(row,{costPolicyId:null,costPolicyVersion:null,monthlyCostSnapshot:null,standardWorkDaysSnapshot:null,dailyCostSnapshot:null,costCurrency:null,estimatedCost:null});syncStaffRow(row,options.staff.find(item=>Number(item.userId)===Number(row.userId)))}
function recomputeAllStaffCosts(){if(isNewTemplate.value)return;const days=plannedDays();for(const row of form.value.staffingLines||[]){const monthly=row.monthlyCostSnapshot,daily=row.dailyCostSnapshot;row.estimatedCost=monthly==null?null:days===null?Number(monthly):daily==null?null:Number((Number(daily)*days).toFixed(2))}}
async function refreshStaffOptions(){const params={effectiveDate:form.value.planStartDate||undefined};if(form.value.companyDeptId)params.companyDeptId=form.value.companyDeptId;const res=await getProjectProposalStaffOptions(params);options.staff=res.data||[];for(const row of form.value.staffingLines||[]){if(!row.userId)continue;const item=options.staff.find(option=>Number(option.userId)===Number(row.userId));if(item)syncStaffRow(row,item);else Object.assign(row,{...emptyStaffing(),note:row.note||''})}}
const staffOptionLabel=item=>{const name=item.nickName&&item.nickName!==item.accountName?`${item.nickName}（${item.accountName}）`:item.nickName||item.accountName;return `${name} · ${item.companyName||'未归属公司'} · ${item.positionName||'项目成员'}`}
const staffAlreadySelected=(userId,current)=>form.value.staffingLines?.some(row=>row!==current&&Number(row.userId)===Number(userId))
async function loadMine(){const res=await listProjectProposals({pageNum:1,pageSize:100});mineRows.value=res.rows||[]}
async function loadReview(){if(!canReview.value)return;const res=await listProposalReviews({pageNum:1,pageSize:100});reviewRows.value=res.rows||[]}
async function loadDirectory(){if(!canReview.value)return;const res=await listProposalDirectory({pageNum:1,pageSize:100});directoryRows.value=res.rows||[]}
async function loadActive(){loading.value=true;try{if(activeTab.value==='mine')await loadMine();else if(activeTab.value==='review')await loadReview();else await loadDirectory()}finally{loading.value=false}}
async function refreshAll(){await Promise.all([loadMine(),canReview.value?loadReview():Promise.resolve()]);if(activeTab.value==='directory')await loadDirectory()}
async function openForm(row){await ensureOptions();const source=row?.proposalId?(await getProjectProposal(row.proposalId)).data:freshForm();const legacyMode=source.managementMode==='SIMPLE'?'LIGHT':source.managementMode==='DELIVERY'?'STANDARD':source.managementMode;const legacyClose=source.closeMethod||(source.managementMode==='DELIVERY'?'RESULT_ACCEPTANCE':'DIRECT');form.value={...freshForm(),...source,templateVersion:source.templateVersion||(row?.proposalId?'LEGACY_V1':'LIGHT_V1'),managementMode:legacyMode,closeMethod:legacyClose,revenueLines:source.revenueLines||[],expenseLines:source.expenseLines||[],staffingLines:(source.staffingLines||[]).map(row=>({...row,planStartDate:shortDate(row.planStartDate)||null,planEndDate:shortDate(row.planEndDate)||null})),targetLines:source.targetLines||[]};openEnded.value=!newTemplate(form.value)&&!!row?.proposalId&&!!source.planStartDate&&!source.planEndDate;noBudget.value=isNewTemplate.value&&(source.noBudget==='1'||source.budgetLimit==null);if(isNewTemplate.value)templateChanged();await refreshStaffOptions();formVisible.value=true;nextTick(()=>formRef.value?.clearValidate())}
async function saveForm(){await formRef.value.validate();if(!form.value.planStartDate)return ElMessage.warning('请选择计划开始日期');if((isNewTemplate.value||!openEnded.value)&&!form.value.planEndDate)return ElMessage.warning('请选择有限的项目计划结束日期');if(form.value.planEndDate&&form.value.planStartDate>form.value.planEndDate)return ElMessage.warning('计划结束日期不能早于开始日期');if(form.value.managementMode==='KEY_CONTROL'&&!form.value.managementReason?.trim())return ElMessage.warning('重点监管项目请填写监管原因');if((isNewTemplate.value||form.value.closeMethod!=='DIRECT')&&!form.value.acceptanceCriteria?.trim())return ElMessage.warning('请填写成果清单和验收依据');if((!isNewTemplate.value||!noBudget.value)&&form.value.budgetLimit==null)return ElMessage.warning('请填写预算或选择不设置预算');const staffing=form.value.staffingLines||[];if(!isNewTemplate.value&&!staffing.length||staffing.some(row=>!row.userId))return ElMessage.warning('请在人员计划中选择具体人员');if(new Set(staffing.map(row=>String(row.userId))).size!==staffing.length)return ElMessage.warning('同一人员不能重复选择');if(isNewTemplate.value)for(const row of staffing){if(!row.planStartDate||!row.planEndDate||row.planStartDate>row.planEndDate||row.planStartDate<form.value.planStartDate||row.planEndDate>form.value.planEndDate)return ElMessage.warning('人员参与日期必须在项目计划窗口内');if(!(Number(row.inputQuantity)>0)||row.inputUnit==='PERCENTAGE'&&Number(row.inputQuantity)>100||!row.calendarId||!row.unitPolicyId)return ElMessage.warning('请填写有效工作量并选择日历与单位政策')}if(isControlled(form.value)&&String(form.value.sponsorOwnerUserId)===String(options.applicantUserId))return ElMessage.warning('受控项目必须由另一位归属老板审批');saving.value=true;try{const payload={...form.value,estimatedBonusCost:0,planEndDate:isNewTemplate.value?form.value.planEndDate:openEnded.value?null:form.value.planEndDate,noBudget:isNewTemplate.value&&noBudget.value?'1':'0',budgetLimit:isNewTemplate.value&&noBudget.value?null:form.value.budgetLimit};const res=payload.proposalId?await updateProjectProposal(payload):await addProjectProposal(payload);formVisible.value=false;ElMessage.success(isNewTemplate.value?'立项申请已保存，人员实际成本另行确认计价':'历史立项申请已保存，成本按原规则由后台核对');await refreshAll();if(res.data?.proposalId)await openDetail(res.data)}finally{saving.value=false}}

async function openDetail(row){const res=await getProjectProposal(row.proposalId);detail.value=res.data||{};detailVisible.value=true}
async function submitRow(row){const controlled=isControlled(row);await ElMessageBox.confirm(controlled?`确认提交“${row.projectName}”给归属老板审批吗？批准后才会创建正式项目。`:`确认启动“${row.projectName}”吗？系统将按该申请的模板和冻结规则检查资料。` ,controlled?'提交立项审批':'负责人确认启动',{type:'warning',confirmButtonText:controlled?'确认提交':'确认并启动'});const res=await submitProjectProposal(row.proposalId);ElMessage.success(res.data?.status==='PENDING'?'已提交归属老板审批，项目尚未启动':'项目已按适用模板启动');detailVisible.value=false;await refreshAll();if(res.data?.createdProjectId)openProject(res.data)}
async function withdrawRow(row){const result=await ElMessageBox.prompt('可以填写撤回说明','撤回立项申请',{inputPlaceholder:'可选'});await withdrawProjectProposal(row.proposalId,{comment:result.value});ElMessage.success('申请已撤回');detailVisible.value=false;await refreshAll()}
async function reviewRow(row,decision){let comment='';if(decision==='RETURNED'){const result=await ElMessageBox.prompt('请填写退回原因，申请人修改后可以重新提交','退回立项申请',{inputValidator:value=>!!value?.trim()||'必须填写退回原因'});comment=result.value}else await ElMessageBox.confirm(`批准“${row.projectName}”后将立即创建正式项目，并由 ${row.applicantName} 负责执行。确认批准吗？`,'批准立项',{type:'warning'});await reviewProjectProposal(row.proposalId,{decision,comment});ElMessage.success(decision==='APPROVED'?'立项已批准，项目已进入执行':'申请已退回修改');detailVisible.value=false;await refreshAll()}
function openProject(row){router.push({path:'/business/projects',query:{id:row.createdProjectId}})}
const bossOptionLabel=item=>item.nickName&&item.nickName!==item.userName?`${item.nickName}（${item.userName}）`:item.nickName||item.userName
const money=(value,currency='CNY')=>value===null||value===undefined?'—':`${Number(value).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`
const planPeriod=item=>item?.planStartDate?`${item.planStartDate} 至 ${item.planEndDate||'不限期'}`:'—'
function handleOpenEndedChange(value){if(value)form.value.planEndDate=null;recomputeAllStaffCosts()}
function disablePlanEndDate(date){return !!form.value.planStartDate&&date.getTime()<new Date(`${form.value.planStartDate}T00:00:00`).getTime()}
onMounted(async()=>{activeTab.value=route.query.tab==='directory'&&canReview.value?'directory':'mine';await ensureOptions();await refreshAll();if(route.query.id)await openDetail({proposalId:Number(route.query.id)})})
useBusinessRefreshOnReactivated(refreshAll)
</script>

<style scoped>
.proposal-page{min-height:calc(100vh - 84px);padding:24px;background:#f4f6f8}.page-head{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:16px}.eyebrow{font-size:11px;letter-spacing:.16em;color:#3977c5}.page-head h1{margin:4px 0;font-size:27px;color:#172033}.page-head p{margin:0;color:#778394}.proposal-tabs{margin-top:16px}.proposal-tabs :deep(.el-tabs__content){overflow:visible}.el-table b,.el-table small{display:block}.el-table small{margin-top:4px;color:#8994a2}.row-actions{display:flex;gap:8px}.row-actions .el-button+.el-button{margin-left:0}.budget-line{display:flex;align-items:center;gap:12px}.detail-grid{display:grid;grid-template-columns:repeat(2,1fr);border:1px solid #e1e6eb;border-radius:10px}.detail-grid div{padding:14px;border-right:1px solid #e1e6eb;border-bottom:1px solid #e1e6eb}.detail-grid div:nth-child(2n){border-right:0}.detail-grid div:nth-last-child(-n+2){border-bottom:0}.detail-grid span,.detail-grid b{display:block}.detail-grid span{color:#8793a1;font-size:12px}.detail-grid b{margin-top:6px}.detail-section{margin-top:18px;padding:16px;border:1px solid #e3e8ed;border-radius:10px;background:#fff}.detail-section h3{margin:0 0 10px;font-size:15px}.detail-section p{margin:0;line-height:1.7;white-space:pre-wrap}.review-comment{border-left:3px solid #d8892f;background:#fffaf2}.drawer-actions{position:sticky;bottom:0;display:flex;flex-wrap:wrap;gap:8px;margin-top:18px;padding:14px 0;background:#fff}.drawer-actions .el-button+.el-button{margin-left:0}.muted{color:#9099a5;font-size:12px}@media(max-width:760px){.proposal-page{padding:14px}.page-head{align-items:flex-start;flex-direction:column;gap:14px}.page-head>.el-button{width:100%}.detail-grid{grid-template-columns:1fr}.detail-grid div,.detail-grid div:nth-child(2n){border-right:0;border-bottom:1px solid #e1e6eb}.detail-grid div:last-child{border-bottom:0}.budget-line{align-items:flex-start;flex-direction:column}.el-dialog .el-col{max-width:100%;flex:0 0 100%}.plan-period-line{grid-template-columns:1fr}.plan-period-line>span{display:none}}
.governance-tip{margin:-4px 0 16px}.field-help{display:block;margin-top:5px;color:#8793a1;line-height:1.45}.plan-period-line{display:grid;grid-template-columns:minmax(130px,1fr) auto minmax(130px,1fr) auto;align-items:center;gap:10px;width:100%}.plan-period-line>span{color:#7f8a99}
.plan-section{margin:10px 0 18px;padding:16px;border:1px solid #dfe6ee;border-radius:10px;background:#fafbfd}.plan-section-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.plan-section-head h3{margin:0;color:#26364d}.plan-section-head p{margin:5px 0 0;color:#7d8998;font-size:12px}.plan-section :deep(.el-input-number){width:100%}.finance-summary{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:4px 0 18px}.finance-summary>div{padding:13px;border-radius:8px;background:#edf4fb}.finance-summary span,.finance-summary b{display:block}.finance-summary span{font-size:12px;color:#6f7f91}.finance-summary b{margin-top:5px;color:#24364b}.finance-summary.compact{margin:0}.danger-text{color:#d7474f!important}.success-text{color:#16945e!important}
@media(max-width:760px){.plan-period-line{grid-template-columns:1fr}.plan-period-line>span{display:none}}
@media(max-width:900px){.finance-summary{grid-template-columns:repeat(2,1fr)}.plan-section{overflow-x:auto}.plan-section .el-table{min-width:850px}}
</style>
