<template>
  <div class="proposal-plan-details">
    <template v-if="kind==='targets'"><div class="plan-section"><div class="plan-section-head"><div><h3 :class="{'required-section':requiredPlanSections.targets}">项目验收目标</h3><p>{{ requiredPlanSections.targets ? '启动前至少填写一项可验收目标，可先保存草稿。' : '选填，可填写数值目标或成果验收要求。' }}</p></div><el-button size="small" type="primary" plain @click="addTarget">增加目标</el-button></div><el-table :data="form.targetLines" size="small"><el-table-column label="类型" :label-class-name="form.targetLines?.length ? 'required-column' : ''" width="125"><template #default="{row}"><el-select v-model="row.targetType" @change="changeTargetType(row)"><el-option v-for="(label,value) in targetTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="目标名称" :label-class-name="form.targetLines?.length ? 'required-column' : ''" min-width="180"><template #default="{row}"><el-input v-model="row.targetName" maxlength="160"/></template></el-table-column><el-table-column label="目标值" :label-class-name="form.targetLines?.some(row=>row.targetType!=='DELIVERY') ? 'required-column' : ''" width="145"><template #default="{row}"><span v-if="row.targetType==='DELIVERY'">通过验收</span><el-input-number v-else v-model="row.targetValue" :min="0" :max="99999999999999.99" :precision="4"/></template></el-table-column><el-table-column label="单位" :label-class-name="form.targetLines?.some(row=>row.targetType!=='DELIVERY') ? 'required-column' : ''" width="140"><template #default="{row}"><span v-if="row.targetType==='DELIVERY'">—</span><el-select v-else v-model="row.unit" filterable placeholder="选择单位" aria-label="目标单位" style="width:100%"><el-option v-if="row.unit && !targetUnitOptions.includes(row.unit)" :label="row.unit" :value="row.unit"/><el-option v-for="unit in targetUnitOptions" :key="unit" :label="unit" :value="unit"/></el-select></template></el-table-column><el-table-column label="完成日期" width="145"><template #default="{row}"><el-date-picker v-model="row.dueDate" value-format="YYYY-MM-DD" :disabled-date="disableStaffStartDate" style="width:100%"/><small v-if="lineDateIssue(row.dueDate)" class="danger-text">{{ lineDateIssue(row.dueDate) }}</small></template></el-table-column><el-table-column label="验收依据" :label-class-name="form.targetLines?.length ? 'required-column' : ''" min-width="210"><template #default="{row}"><el-input v-model="row.acceptanceEvidence" maxlength="500" placeholder="报表、合同、交付文件等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.targetLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></template>
    <template v-else><div class="plan-section"><div class="plan-section-head"><div><h3 :class="{'required-section':requiredPlanSections.revenue}">收入测算</h3><p>{{ requiredPlanSections.revenue ? '启动前填写正常场景预计收入，合计须大于0；可先保存草稿。' : '收入测算可选，用于记录预期和假设；添加后请填写行内必填项。' }}</p></div><el-button size="small" type="primary" plain @click="addRevenue">增加收入</el-button></div><el-table :data="form.revenueLines" size="small" :empty-text="requiredPlanSections.revenue ? '请添加正常场景收入预测' : '收入测算选填，可按需要增加'"><el-table-column label="场景" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="120"><template #default="{row}"><el-select v-model="row.scenario"><el-option label="保守" value="CONSERVATIVE"/><el-option label="正常" value="BASE"/><el-option label="乐观" value="OPTIMISTIC"/></el-select></template></el-table-column><el-table-column label="收入方式" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="145"><template #default="{row}"><el-select v-model="row.revenueType"><el-option v-for="(label,value) in revenueTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="收入项目" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" min-width="150"><template #default="{row}"><el-input v-model="row.itemName" maxlength="160" placeholder="商品或服务"/></template></el-table-column><el-table-column label="预计金额" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="165"><template #default="{row}"><el-input-number v-model="row.expectedAmount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="发生方式" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="125"><template #default="{row}"><el-select v-model="row.occurrenceType" placeholder="一次性"><el-option label="一次性" value="ONE_TIME"/><el-option label="每日" value="DAILY"/><el-option label="每周" value="WEEKLY"/><el-option label="每月" value="MONTHLY"/></el-select></template></el-table-column><el-table-column label="预计回款 / 开始" width="145"><template #default="{row}"><el-date-picker v-model="row.expectedDate" value-format="YYYY-MM-DD" :disabled-date="disableStaffStartDate" style="width:100%"/><small v-if="lineDateIssue(row.expectedDate)" class="danger-text">{{ lineDateIssue(row.expectedDate) }}</small></template></el-table-column><el-table-column label="依据" min-width="170"><template #default="{row}"><el-input v-model="row.assumptionText" maxlength="1000" placeholder="单价、数量、转化率等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.revenueLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></template>
  </div>
</template>
<script setup>
defineProps({kind:String,form:Object,requiredPlanSections:Object,targetTypeLabel:Object,targetUnitOptions:Array,revenueTypeLabel:Object,disableStaffStartDate:Function,lineDateIssue:Function})
const emit=defineEmits(['add-target','add-revenue','change-target-type'])
const addTarget=()=>emit('add-target')
const addRevenue=()=>emit('add-revenue')
const changeTargetType=row=>emit('change-target-type',row)
</script>
<style scoped>
.plan-section{margin:10px 0 18px;padding:16px;border:1px solid #dfe6ee;border-radius:10px;background:#fafbfd}.plan-section-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.plan-section-head h3{margin:0;color:#26364d}.plan-section-head p{margin:5px 0 0;color:#7d8998;font-size:12px}.plan-section :deep(.el-input-number){width:100%}.required-section::before{content:'*';color:var(--el-color-danger);margin-right:4px}.danger-text{color:#d7474f}
</style>
