<template>
  <div class="proposal-plan-details">
    <template v-if="kind==='targets'"><div class="plan-section form-section"><div class="plan-section-head"><div><h3 :class="{'required-section':requiredPlanSections.targets}"><span class="section-index">{{ sectionNumber }}</span>项目验收目标</h3><p>{{ requiredPlanSections.targets ? '至少填写一项验收目标' : '选填' }}</p></div><el-button size="small" type="primary" plain @click="addTarget">增加目标</el-button></div><el-table :data="form.targetLines" size="small"><el-table-column label="类型" :label-class-name="form.targetLines?.length ? 'required-column' : ''" width="125"><template #default="{row}"><el-select v-model="row.targetType" @change="changeTargetType(row)"><el-option v-for="(label,value) in targetTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="目标名称" :label-class-name="form.targetLines?.length ? 'required-column' : ''" min-width="180"><template #default="{row}"><el-input v-model="row.targetName" maxlength="160"/></template></el-table-column><el-table-column label="目标值" :label-class-name="form.targetLines?.some(row=>row.targetType!=='DELIVERY') ? 'required-column' : ''" width="145"><template #default="{row}"><span v-if="row.targetType==='DELIVERY'">通过验收</span><el-input-number v-else v-model="row.targetValue" :min="0" :max="99999999999999.99" :precision="4"/></template></el-table-column><el-table-column label="单位" :label-class-name="form.targetLines?.some(row=>row.targetType!=='DELIVERY') ? 'required-column' : ''" width="140"><template #default="{row}"><span v-if="row.targetType==='DELIVERY'">—</span><el-select v-else v-model="row.unit" filterable placeholder="选择单位" aria-label="目标单位" style="width:100%"><el-option v-if="row.unit && !targetUnitOptions.includes(row.unit)" :label="row.unit" :value="row.unit"/><el-option v-for="unit in targetUnitOptions" :key="unit" :label="unit" :value="unit"/></el-select></template></el-table-column><el-table-column :label="dateType==='date' ? '完成日期' : '完成月份'" width="145"><template #default="{row}"><ProposalMonthPicker :date-type="dateType" v-model="row.dueDate" :start-date="form.planStartDate" :end-date="planEndDate" deadline /><small v-if="lineDateIssue(row.dueDate)" class="danger-text">{{ lineDateIssue(row.dueDate) }}</small></template></el-table-column><el-table-column label="验收依据" :label-class-name="form.targetLines?.length ? 'required-column' : ''" min-width="210"><template #default="{row}"><el-input v-model="row.acceptanceEvidence" maxlength="500" placeholder="报表、合同、交付文件等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.targetLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></template>
    <template v-else><div class="plan-section form-section"><div class="plan-section-head"><div><h3 :class="{'required-section':requiredPlanSections.revenue}"><span class="section-index">{{ sectionNumber }}</span>收入测算<span v-if="!requiredPlanSections.revenue" class="optional-label">（选填）</span></h3><p>可选择项目开始月前 6 个月；有限期项目最晚可选结束月后 6 个月，不限期项目不限制结束月份</p></div><el-button size="small" type="primary" plain @click="addRevenue">增加收入</el-button></div><el-table :data="form.revenueLines" size="small" :empty-text="requiredPlanSections.revenue ? '请添加收入预测' : '暂无收入测算'"><el-table-column label="收入方式" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="145"><template #default="{row}"><el-select v-model="row.revenueType"><template #label="{ label }">{{ legacyRevenueTypeLabels[row.revenueType] || label }}</template><el-option v-for="(label,value) in revenueTypeLabel" :key="value" :label="label" :value="value"/></el-select></template></el-table-column><el-table-column label="收入项目" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" min-width="150"><template #default="{row}"><el-input v-model="row.itemName" maxlength="160" placeholder="商品或服务"/><small v-if="row.scenario && row.scenario!=='BASE'" class="legacy-revenue-note">历史备选收入，未计入当前测算</small></template></el-table-column><el-table-column label="预计金额" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="165"><template #default="{row}"><el-input-number v-model="row.expectedAmount" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="发生方式" :label-class-name="form.revenueLines?.length ? 'required-column' : ''" width="125"><template #default="{row}"><el-select v-model="row.occurrenceType" placeholder="一次性"><el-option label="一次性" value="ONE_TIME"/><el-option label="每日" value="DAILY"/><el-option label="每周" value="WEEKLY"/><el-option label="每月" value="MONTHLY"/></el-select></template></el-table-column><el-table-column :label="dateType==='date' ? '收入日期 / 开始' : '收入月份 / 开始'" width="145"><template #default="{row}"><ProposalMonthPicker :date-type="dateType" v-model="row.expectedDate" :start-date="form.planStartDate" :end-date="planEndDate" :before-start-months="6" :after-end-months="6" /><small v-if="lineDateIssue(row.expectedDate,'revenue')" class="danger-text">{{ lineDateIssue(row.expectedDate,'revenue') }}</small></template></el-table-column><el-table-column label="依据" min-width="170"><template #default="{row}"><el-input v-model="row.assumptionText" maxlength="1000" placeholder="单价、数量、转化率等"/></template></el-table-column><el-table-column width="55"><template #default="{$index}"><el-button link type="danger" @click="form.revenueLines.splice($index,1)">删</el-button></template></el-table-column></el-table></div></template>
  </div>
</template>
<script setup>
import ProposalMonthPicker from './ProposalMonthPicker.vue'
const legacyRevenueTypeLabels={ADVERTISING:'广告',SUBSCRIPTION:'订阅',SAVING:'成本节约'}
defineProps({kind:String,sectionNumber:String,form:Object,requiredPlanSections:Object,targetTypeLabel:Object,targetUnitOptions:Array,revenueTypeLabel:Object,planEndDate:String,lineDateIssue:Function,dateType:String})
const emit=defineEmits(['add-target','add-revenue','change-target-type'])
const addTarget=()=>emit('add-target')
const addRevenue=()=>emit('add-revenue')
const changeTargetType=row=>emit('change-target-type',row)
</script>
<style scoped>
.optional-label{font-size:13px;font-weight:500;color:#657587}.plan-section{margin:12px 0 22px;padding:22px;border:1px solid #d5e0ec;border-radius:12px;background:#fff;box-shadow:0 5px 16px rgba(36,74,119,.06)}.plan-section-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:18px;padding-bottom:14px;border-bottom:1px solid #e3eaf2}.plan-section-head h3{display:flex;align-items:center;gap:10px;margin:0;color:#1f3048;font-size:20px;line-height:32px}.plan-section-head p{margin:6px 0 0;color:#718096;font-size:13px}.section-index{display:inline-flex;align-items:center;justify-content:center;min-width:38px;height:28px;padding:0 7px;border-radius:7px;background:#e9f3ff;color:#2874c6;font-size:14px;font-weight:700;letter-spacing:.04em}.plan-section :deep(.el-input-number){width:100%}.required-section::before{content:'*';color:var(--el-color-danger);margin-right:-6px}.danger-text{color:#d7474f}.legacy-revenue-note{display:block;margin-top:4px;color:#7d8998;line-height:1.5}
</style>
