<template>
  <div class="app-container accounting-page">
    <header class="hero"><div><span>DAILY BUSINESS LEDGER</span><h1>公司每日收支</h1><p>按公司、项目和日期记录经营事实，确认后自动生成项目盈亏快照。</p></div><el-button type="primary" icon="Plus" @click="openFact()">录入收支</el-button></header>
    <el-card shadow="never" class="filter-card"><el-form :inline="true" :model="query"><el-form-item><el-select v-model="query.companyDeptId" clearable placeholder="两家公司" style="width:190px"><el-option v-for="c in data.companies" :key="c.companyDeptId" :label="c.companyName" :value="c.companyDeptId" /></el-select></el-form-item><el-form-item><el-select v-model="query.projectId" clearable filterable placeholder="全部本人项目" style="width:220px"><el-option v-for="p in filteredProjects" :key="p.projectId" :label="`${p.projectName} · ${p.initiatorName}`" :value="p.projectId" /></el-select></el-form-item><el-form-item><el-date-picker v-model="dates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" /></el-form-item><el-form-item><el-button type="primary" @click="load">查询</el-button><el-button @click="reset">今天</el-button></el-form-item></el-form></el-card>
    <section class="summary-grid"><article><span>确认收入</span><b>{{ money(summary.revenueAmount) }}</b></article><article><span>业务成本</span><b>{{ money(summary.businessCost) }}</b></article><article><span>人员成本</span><b>{{ money(summary.personnelCost) }}</b></article><article><span>核算调整</span><b>{{ signed(summary.adjustmentAmount) }}</b></article><article :class="Number(summary.profitAmount)<0?'loss':'profit'"><span>经营结果</span><b>{{ signed(summary.profitAmount) }}</b></article><article><span>已生成日报</span><b>{{ summary.resultCount || 0 }}</b></article></section>
    <el-card shadow="never" class="section-card"><div class="section-head"><div><h2>项目日结果</h2><p>每次确认、冲销或手动重算都会生成新版本，点击可查看计算分项。</p></div><el-button @click="openRecalculate">手动重算</el-button></div><el-table :data="data.results" @row-click="openResult" class="click-table"><el-table-column prop="bizDate" label="日期" width="105"/><el-table-column label="项目" min-width="190"><template #default="{row}"><b>{{ row.projectName }}</b><small>{{ row.companyName }} · {{ row.initiatorName }}立项</small></template></el-table-column><el-table-column label="收入" align="right"><template #default="{row}">{{ money(row.revenueAmount) }}</template></el-table-column><el-table-column label="业务成本" align="right"><template #default="{row}">{{ money(row.costAmount) }}</template></el-table-column><el-table-column label="人员成本" align="right"><template #default="{row}">{{ money(row.personnelCost) }}</template></el-table-column><el-table-column label="经营结果" align="right"><template #default="{row}"><b :class="Number(row.profitAmount)<0?'red':'green'">{{ signed(row.profitAmount) }}</b></template></el-table-column><el-table-column label="版本" width="70"><template #default="{row}">v{{ row.resultVersion }}</template></el-table-column></el-table></el-card>
    <el-card shadow="never" class="section-card"><div class="section-head"><div><h2>收支流水</h2><p>草稿可修改；确认后只允许冲销，不允许覆盖或删除。</p></div></div><el-table :data="data.facts"><el-table-column prop="bizDate" label="日期" width="105"/><el-table-column label="项目" min-width="170"><template #default="{row}">{{ row.projectName }}<small>{{ row.companyName }}</small></template></el-table-column><el-table-column prop="categoryName" label="类别"/><el-table-column prop="description" label="说明" min-width="180"/><el-table-column label="金额/数值" align="right"><template #default="{row}"><b>{{ row.factKind==='VALUE'?`${row.quantity} ${row.unit||''}`:`${signed(row.amount)} ${row.currency||''}` }}</b></template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="statusTone[row.status]">{{ statusLabel[row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" width="125"><template #default="{row}"><el-button v-if="row.status==='DRAFT'" link @click="openFact(row)">编辑</el-button><el-button v-if="row.status==='DRAFT'" link type="success" @click="confirmFact(row)">确认</el-button><el-button v-if="row.status==='CONFIRMED'" link type="danger" @click="reverseFact(row)">冲销</el-button></template></el-table-column></el-table></el-card>

    <el-dialog v-model="factDialog" :title="factForm.factId?'编辑收支草稿':'录入每日收支'" width="min(680px,94vw)" append-to-body><el-alert title="保存后先进入草稿；点击确认才会计入正式日报。" type="info" :closable="false" show-icon/><el-form :model="factForm" label-width="92px" class="dialog-form"><el-form-item label="归属项目" required><el-select v-model="factForm.projectId" :disabled="!!factForm.factId" filterable style="width:100%" @change="projectChanged"><el-option v-for="p in data.projects" :key="p.projectId" :label="`${p.projectName} · ${p.companyName||'未设置公司'}`" :value="p.projectId" /></el-select></el-form-item><el-form-item label="业务日期" required><el-date-picker v-model="factForm.bizDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="收支类别" required><el-select v-model="factForm.categoryId" style="width:100%"><el-option-group v-for="group in categoryGroups" :key="group.kind" :label="group.label"><el-option v-for="c in group.items" :key="c.categoryId" :label="c.categoryName" :value="c.categoryId" /></el-option-group></el-select></el-form-item><template v-if="selectedCategory?.factKind==='VALUE'"><el-form-item label="成果数值" required><el-input-number v-model="factForm.quantity" :precision="4" style="width:100%" /></el-form-item><el-form-item label="单位"><el-input v-model="factForm.unit" /></el-form-item></template><template v-else><el-form-item label="金额" required><el-input-number v-model="factForm.amount" :precision="4" style="width:100%" /></el-form-item><el-form-item label="币种"><el-input v-model="factForm.currency" maxlength="3" /></el-form-item></template><el-form-item label="收支说明" required><el-input v-model="factForm.description" type="textarea" :rows="3" maxlength="500" show-word-limit /></el-form-item><el-form-item label="对方单位"><el-input v-model="factForm.counterparty" /></el-form-item><el-form-item label="凭证附件"><file-upload v-model="factForm.attachmentUrls" :limit="10" :file-size="20" :file-type="['pdf','doc','docx','xls','xlsx','jpg','jpeg','png']" /></el-form-item><el-form-item label="备注"><el-input v-model="factForm.remark" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button @click="factDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveFact">保存草稿</el-button></template></el-dialog>
    <el-dialog v-model="recalcDialog" title="重算项目日结果" width="min(500px,94vw)" append-to-body><el-form :model="recalcForm" label-width="90px"><el-form-item label="项目" required><el-select v-model="recalcForm.projectId" filterable style="width:100%"><el-option v-for="p in data.projects" :key="p.projectId" :label="p.projectName" :value="p.projectId" /></el-select></el-form-item><el-form-item label="业务日期" required><el-date-picker v-model="recalcForm.bizDate" type="date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item></el-form><template #footer><el-button @click="recalcDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRecalculate">开始重算</el-button></template></el-dialog>
    <el-drawer v-model="resultDrawer" title="项目日结果计算明细" size="min(680px,96vw)" append-to-body><template v-if="resultDetail"><div class="result-title"><div><b>{{ resultDetail.projectName }}</b><span>{{ resultDetail.bizDate }} · v{{ resultDetail.resultVersion }}</span></div><strong :class="Number(resultDetail.profitAmount)<0?'red':'green'">{{ signed(resultDetail.profitAmount) }}</strong></div><el-alert :title="resultDetail.calculationDetail" type="info" :closable="false"/><el-table :data="resultDetail.items" class="item-table"><el-table-column prop="componentName" label="计算分项"/><el-table-column label="金额" align="right"><template #default="{row}">{{ signed(row.amount) }}</template></el-table-column><el-table-column prop="calculationDetail" label="来源说明" min-width="190"/></el-table><section class="personnel-detail"><div class="personnel-title"><div><h3>人员成本明细</h3><p>逐人展示本日计入该项目的内部核算成本</p></div><b>{{ money(resultDetail.personnelCost) }} {{ resultDetail.currency||'CNY' }}</b></div><el-table v-if="resultDetail.personnelItems?.length" :data="resultDetail.personnelItems" size="small"><el-table-column prop="componentName" label="人员" width="110"/><el-table-column label="核算金额" width="120" align="right"><template #default="{row}"><b>{{ money(row.amount) }}</b></template></el-table-column><el-table-column prop="calculationDetail" label="计算依据" min-width="260"/></el-table><el-empty v-else description="本日没有计入人员成本的参项人员" :image-size="70"/></section></template></el-drawer>
  </div>
</template>

<script setup name="BusinessAccounting">
import {ElMessage,ElMessageBox} from 'element-plus'
import {confirmBusinessOperatingFact,getBusinessAccountingDashboard,getBusinessDailyResult,recalculateBusinessProjectDay,reverseBusinessOperatingFact,saveBusinessOperatingFact} from '@/api/business/accounting'
const today=()=>new Date().toISOString().slice(0,10)
const route=useRoute()
const query=reactive({companyDeptId:route.query.companyDeptId?Number(route.query.companyDeptId):null,projectId:route.query.projectId?Number(route.query.projectId):null}),dates=ref([route.query.dateFrom||today(),route.query.dateTo||today()]),data=reactive({summary:{},results:[],facts:[],companies:[],projects:[],categories:[]}),saving=ref(false)
const factDialog=ref(false),factForm=reactive({}),recalcDialog=ref(false),recalcForm=reactive({}),resultDrawer=ref(false),resultDetail=ref(null)
const summary=computed(()=>data.summary||{}),filteredProjects=computed(()=>query.companyDeptId?data.projects.filter(p=>Number(p.companyDeptId)===Number(query.companyDeptId)):data.projects)
const selectedCategory=computed(()=>data.categories.find(c=>Number(c.categoryId)===Number(factForm.categoryId)))
const categoryGroups=computed(()=>['REVENUE','COST','ADJUSTMENT','VALUE'].map(kind=>({kind,label:{REVENUE:'收入',COST:'成本费用',ADJUSTMENT:'核算调整',VALUE:'非金额成果'}[kind],items:data.categories.filter(c=>c.factKind===kind)})).filter(g=>g.items.length))
const statusLabel={DRAFT:'草稿',CONFIRMED:'已确认',REVERSED:'已冲销'},statusTone={DRAFT:'info',CONFIRMED:'success',REVERSED:'warning'}
const money=v=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:4}),signed=v=>`${Number(v||0)>0?'+':''}${money(v)}`
async function load(){const res=await getBusinessAccountingDashboard({...query,dateFrom:dates.value?.[0],dateTo:dates.value?.[1]});Object.assign(data,res.data||{})}
function reset(){Object.assign(query,{companyDeptId:null,projectId:null});dates.value=[today(),today()];load()}
function openFact(row={}){Object.keys(factForm).forEach(k=>delete factForm[k]);Object.assign(factForm,{factId:null,projectId:null,bizDate:today(),categoryId:null,amount:null,quantity:null,currency:'CNY',unit:'',description:'',counterparty:'',attachmentUrls:'',remark:'',version:null,...row});factDialog.value=true}
function projectChanged(id){const p=data.projects.find(x=>Number(x.projectId)===Number(id));if(p)factForm.currency=p.currency||'CNY'}
async function saveFact(){if(!factForm.projectId||!factForm.categoryId||!factForm.bizDate)return ElMessage.warning('请完整选择项目、日期和类别');if(!factForm.description?.trim())return ElMessage.warning('请填写收支说明');saving.value=true;try{await saveBusinessOperatingFact(factForm);factDialog.value=false;await load();ElMessage.success('收支草稿已保存')}finally{saving.value=false}}
async function confirmFact(row){await ElMessageBox.confirm('确认后将计入正式日报，不能直接修改，确定吗？','确认入账',{type:'warning'});await confirmBusinessOperatingFact(row.factId);await load();ElMessage.success('已确认入账并生成日结果')}
async function reverseFact(row){const {value}=await ElMessageBox.prompt('请填写冲销原因','冲销已确认流水',{inputValidator:v=>!!v?.trim()||'必须填写冲销原因',type:'warning'});await reverseBusinessOperatingFact(row.factId,{reason:value});await load();ElMessage.success('已冲销并重新生成日结果')}
function openRecalculate(){Object.assign(recalcForm,{projectId:query.projectId||null,bizDate:dates.value?.[1]||today()});recalcDialog.value=true}
async function saveRecalculate(){if(!recalcForm.projectId||!recalcForm.bizDate)return ElMessage.warning('请选择项目和日期');saving.value=true;try{await recalculateBusinessProjectDay(recalcForm);recalcDialog.value=false;await load();ElMessage.success('项目日结果已生成新版本')}finally{saving.value=false}}
async function openResult(row){resultDetail.value=(await getBusinessDailyResult(row.resultId)).data;resultDrawer.value=true}
load()
</script>

<style scoped>
.accounting-page{min-height:calc(100vh - 84px);padding:24px;background:#f3f5f8}.hero{display:flex;align-items:flex-end;justify-content:space-between;padding:25px 30px;border-radius:16px;background:linear-gradient(120deg,#173750,#1c665f);color:#fff}.hero span{font-size:11px;letter-spacing:.17em;color:#85e1d2}.hero h1{margin:5px 0}.hero p{margin:0;color:#d0e1e3}.filter-card,.section-card{margin-top:14px;border-color:#dfe5ea}.filter-card :deep(.el-card__body){padding-bottom:2px}.summary-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin-top:14px}.summary-grid article{padding:16px;border:1px solid #dfe5ea;border-radius:12px;background:#fff}.summary-grid span,.summary-grid b{display:block}.summary-grid span{color:#7f8b99;font-size:12px}.summary-grid b{margin-top:8px;font-size:22px}.summary-grid .profit{border-top:3px solid #299b7b}.summary-grid .loss{border-top:3px solid #d54f57}.section-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.section-head h2{margin:0;font-size:18px}.section-head p{margin:5px 0 0;color:#8491a0;font-size:12px}.section-card small{display:block;margin-top:4px;color:#8a95a2}.click-table :deep(.el-table__row){cursor:pointer}.red{color:#cf454e}.green{color:#248465}.dialog-form{margin-top:18px}.result-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;padding:16px;border-radius:10px;background:#f5f8fa}.result-title b,.result-title span{display:block}.result-title span{margin-top:5px;color:#8692a0}.result-title strong{font-size:24px}.item-table{margin-top:14px}.personnel-detail{margin-top:22px;padding-top:18px;border-top:1px solid #e4e8ed}.personnel-title{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:12px}.personnel-title h3{margin:0;font-size:17px}.personnel-title p{margin:5px 0 0;color:#8491a0;font-size:12px}.personnel-title>b{color:#2c6f65}@media(max-width:760px){.accounting-page{padding:14px}.hero{align-items:flex-start;flex-direction:column;gap:16px;padding:22px}.hero .el-button{width:100%}.summary-grid{grid-template-columns:repeat(2,1fr)}.summary-grid article:last-child{grid-column:span 2}.filter-card :deep(.el-form-item){display:flex;margin-right:0}.filter-card :deep(.el-select),.filter-card :deep(.el-date-editor){width:100%!important}.section-head{align-items:flex-start;flex-direction:column;gap:10px}.personnel-title{align-items:flex-start;flex-direction:column;gap:8px}}
</style>
